### ISSUE TITLE
running latest release artifact (saml2aws_2.36.5_linux_amd64.tar.gz) and unable to execute without fatal error /lib64/libc.so.6: version

### ISSUE THREAD

**Issue by jgh9** [Versent/saml2aws#1010]
Unable to execute latest without fatal error on Amazon Linux 2:

```
./saml2aws: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by ./saml2aws)
./saml2aws: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by ./saml2aws)
./saml2aws: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by ./saml2aws)
```

I have previous versions download that I am able to execute with no error:
> saml2aws_a-1ft4mi889r61p-202303202305/bin/saml2aws --version
2.36.4

**Comment by jgh9** [comment]
this is in AWS and not latest Amazon Linux version

**Comment by Nuru** [comment]
Did you forget to set `CGO_ENABLED=0` when building the executables?

**Comment by jgh9** [comment]
> Did you forget to set `CGO_ENABLED=0` when building the executables?

I was executing latest release artifact (saml2aws_2.36.5_linux_amd64.tar.gz) posted. I was not building an executable.

**Comment by jgh9** [comment]
Additionally, receive same error in referenced package updates linked above. Unless I am analyzing incorrectly, It appears artifact was created and linked with newer version of Linux software libraries, and is not backwards compatible.

```
> wget https://github.com/Versent/saml2aws/releases/download/v2.36.6/saml2aws_2.36.6_linux_amd64.tar.gz
> tar xvf saml2aws_2.36.6_linux_amd64.tar.gz saml2aws
saml2aws
> ./saml2aws 
./saml2aws: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by ./saml2aws)
./saml2aws: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by ./saml2aws)
./saml2aws: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by ./saml2aws)

>  ldd saml2aws
./saml2aws: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by ./saml2aws)
./saml2aws: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by ./saml2aws)
./saml2aws: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by ./saml2aws)
        linux-vdso.so.1 (0x00007ffe01fe0000)
        libudev.so.1 => /lib64/libudev.so.1 (0x00007fedb6d39000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fedb698c000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fedb6f4d000)
        librt.so.1 => /lib64/librt.so.1 (0x00007fedb6784000)
        libcap.so.2 => /lib64/libcap.so.2 (0x00007fedb657b000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fedb623b000)
        libdw.so.1 => /lib64/libdw.so.1 (0x00007fedb5fea000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007fedb5de6000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fedb5bd0000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fedb59b2000)
        libelf.so.1 => /lib64/libelf.so.1 (0x00007fedb579a000)
        libz.so.1 => /lib64/libz.so.1 (0x00007fedb5585000)
        liblzma.so.5 => /lib64/liblzma.so.5 (0x00007fedb5360000)
        libbz2.so.1 => /lib64/libbz2.so.1 (0x00007fedb5150000)
```

**Comment by iainelder** [comment]
@jgh9 , I see the same error on Ubuntu 20.04. See #1026.

**Comment by chris-reeves** [comment]
This is a result of the merge of #951. That PR forces `CGO_ENABLED=1`, which introduces a dependency on `libc6`. As this is built on `ubuntu-latest` (currently 22.04) the minimum version of `libc` supported is 2.32, which is greater than that available in Ubuntu 20.04 and Debian stable.

**Comment by Nuru** [comment]
@jgh9 When I said
> Did you forget to set CGO_ENABLED=0 when building the executables?

The "you" I was referring to was the project build/release maintainer. And indeed, @chris-reeves has [confirmed they are using `CGO_ENABLED=1`](https://github.com/Versent/saml2aws/issues/1010#issuecomment-1505055624).

@chris-reeves I believe the path forward is to get the build to work on Ubuntu + cross-compile with `CGO_ENABLED=0`. In my tests, when using GitHub actions docker image for `ubuntu-latest` (Ubuntu-22.04), `goreleaser` works fine with `GGO_ENABLED=0` and the resulting binaries are fully portable. 


Side note: you might want to include in `goreleaser*.yml`:

```yaml
builds:
  - ldflags:
      # Reduce binary size by stripping DWARF, symbol table and debug info symbols
      - '-s -w'
```
to reduce the size of distributed artifacts.

**Comment by Nuru** [comment]
I don't have the setup to test binaries beyond confirming they are running, but did get the project to build on both macOS and Ubuntu 22.04 with `CGO_ENABLED=0` without complaint and the binaries did run. I am not set up to test U2F.

**Comment by jgh9** [comment]
> @jgh9 When I said
> 
> > Did you forget to set CGO_ENABLED=0 when building the executables?
> 
> The "you" I was referring to was the project build/release maintainer. And indeed, @chris-reeves has [confirmed they are using `CGO_ENABLED=1`](https://github.com/Versent/saml2aws/issues/1010#issuecomment-1505055624).

Understood, and thank _you_ for clarification :)
I, myself, have built a number of go-related applications as an open-source packager but it was slightly unclear what was being asked. I'm glad to see some movement on issue.

**Comment by jgh9** [comment]
Accidentally closed on latest comment, and re-opened with apologies. Github interface is odd for making comments with "close with comment" button being so close to "Comment"

**Comment by smlx** [comment]
Unfortunately U2F requires CGO. Building with Ubuntu 20.04 will broaden compatibility but the binary will still fail to run on e.g. Alpine or if libudev is missing.

Probably the build needs to be split on Linux into multiple binaries:
* `CGO_ENABLED=0` static builds without U2F support
* `CGO_ENABLED=1` dynamic builds on Ubuntu 20.04 for broad glibc/systemd compatibility (i.e. most Linux Distros) and U2F support
* `CGO_ENABLED=1` dynamic builds on Alpine for musl/eudev compatibility and U2F support ([example Dockerfile](https://github.com/Versent/saml2aws/pull/890#issuecomment-1502608847))

**Comment by jgh9** [comment]
> I quite like the approach suggested by @smlx, whereby the standard build is statically linked without U2F support (as before) and there's a separate build with Linux U2F support. This gives the portability and compatibility of the static binary by default, while those who need U2F support have a release build that has reasonable glibc compatibility (due to being built on ubuntu-20.04). PR to follow shortly (this doesn't address the Alpine/docker builds referenced in #890).

Completely agree. I'm not familiar with build process of project, but as a packager, myself, of a major open source Operating System we do handle building and distributing variables as discussed in thread.

**Comment by jgh9** [comment]
Please consider a new release based on this work...

**Comment by maximveksler** [comment]
Ouch...

**Comment by iainelder** [comment]
> Please consider a new release based on this work...

Yes, this issue got closed (automatically?) but the latest release `saml2aws_2.36.6_linux_amd64.tar.gz` still fails as above.

**Comment by jgh9** [comment]
> > Please consider a new release based on this work...
> 
> Yes, this issue got closed (automatically?) but the latest release `saml2aws_2.36.6_linux_amd64.tar.gz` still fails as above.

I recall testing this as well, and why I am encouraging project to create a new release. Thank you for bringing this up :)

**Comment by iainelder** [comment]
@jgh9, the problem seems to be solved as of 2.36.8.

There are now two assets to choose from:

* `saml2aws_2.36.8_linux_amd64.tar.gz` - saml2aws without U2F support
* `saml2aws-u2f_2.36.8_linux_amd64.tar.gz` - saml2aws with U2F support

The comments here had led me to believe that U2F support needed a version of glibc newer than Ubuntu 20 supports.

But I'm able to install both assets on Ubuntu 20. So I'm still not sure what was causing the problem in the first place.

Anyway, it seems to be fixed now. Thanks all for your help.

**Comment by chris-reeves** [comment]
> There are now two assets to choose from:
>     * `saml2aws_2.36.8_linux_amd64.tar.gz` - saml2aws without U2F support
>     * `saml2aws-u2f_2.36.8_linux_amd64.tar.gz` - saml2aws with U2F support
> 
> The comments here had led me to believe that U2F support needed a version of glibc newer than Ubuntu 20 supports.
> 
> But I'm able to install both assets on Ubuntu 20. So I'm still not sure what was causing the problem in the first place.

There were two related issues - the U2F support required non-static builds and the build pipeline was updated to use `ubuntu-latest` (22.04), so they did not work on 20.04. Now there's a U2F build (using shared libs) but built on 20.04 (so that 20.04 and below is still supported), and a static (non-U2F) build (which runs on pretty much anything).

**Comment by jgh9** [comment]
> > There are now two assets to choose from:
> 
> >     * `saml2aws_2.36.8_linux_amd64.tar.gz` - saml2aws without U2F support
> 
> >     * `saml2aws-u2f_2.36.8_linux_amd64.tar.gz` - saml2aws with U2F support
> 
> > 
> 
> > The comments here had led me to believe that U2F support needed a version of glibc newer than Ubuntu 20 supports.
> 
> > 
> 
> > But I'm able to install both assets on Ubuntu 20. So I'm still not sure what was causing the problem in the first place.
> 
> 
> 
> There were two related issues - the U2F support required non-static builds and the build pipeline was updated to use `ubuntu-latest` (22.04), so they did not work on 20.04. Now there's a U2F build (using shared libs) but built on 20.04 (so that 20.04 and below is still supported), and a static (non-U2F) build (which runs on pretty much anything).
> 
> 

It is great to explain in issue, however if helpful to others it may be good to roll into Readme or other supporting documentation related to artifacts.

**Comment by mapkon** [comment]
I think we should move this to the README and document it properly. @jgh9 Can you help with this?

**Comment by iainelder** [comment]
@chris-reeves quitely updated the README to explain the build for U2F  : https://github.com/Versent/saml2aws/commit/01560d31e0e7c5482cc86cc8b5c1c545ae63db7d . I just noticed it now.

For me it's good enough. If you want to make more changes you can ask me for a review.
