### ISSUE TITLE
2.36.6 errors on GoogleApps AGAIN

### ISSUE THREAD

**Issue by behobu** [Versent/saml2aws#1017]
Error authenticating to IdP.: page is missing saml assertion

Have only one profile in my .saml2aws, and it's the default.  It works if I downgrade back to 2.36.5 and nothing else on my system has changed. Please re-re-re-fix.

**Comment by chris-reeves** [comment]
This will be a different issue to the one @jgh9 reported, given that 2.36.5 works and the error is different.
