### ISSUE TITLE
Saml2AWS for Windows behind a corporate proxy 

### ISSUE THREAD

**Issue by pharindoko** [Versent/saml2aws#103]
Hello,

I tried to use Saml2AWS in Windows but I get an exception

**Issue**

Following error I get:

```
Authenticating as xxx@xxx ...
Post https://signin.aws.amazon.com/saml: Proxy Authorization Required
error retrieving AWS login form
github.com/versent/saml2aws.ParseAWSAccounts
```

**Tests**
I added HTTP_PROXY as systemvariable with the companies proxy like "http://Address:Port

**Additional Note**
When I use VirtualBox/Ubuntu/CNTLM on the **same** machine in the same network -> it works.

**Question:**
Does any one of you have further ideas how to get this accomplished ?

**Comment by tbugfinder** [comment]
Hi @pharindoko 
does use of proxy still work for you?

**Comment by alisade** [comment]
https://github.com/Versent/saml2aws/pull/739
