### ISSUE TITLE
using Firefox instead of Chromium

### ISSUE THREAD

**Issue by usairman82** [Versent/saml2aws#1034]
Greetings,

I was wondering if there was a known path to using Firefox instead of Chromium from the CLI?

When I tried replacing Chromium with Firefox in the code I get:
browser?time="2023-05-01T10:06:32-04:00" level=info msg="opening browser" URL="https://myapplications.azure.us/" provider=browser
time="2023-05-01T10:06:33-04:00" level=info msg="clean up browser" provider=browser
Error authenticating to IdP.: could not send message to server: SEC_ERROR_UNKNOWN_ISSUER
=========================== logs ===========================
navigating to "https://myapplications.azure.us/", waiting until "load"
============================================================

It opens the browser, then immediately stops.

Thank you!

**Comment by usairman82** [comment]
Thank you.  I eventually forked the repo and I've gotten it working well.  I'll probably expose a version where you can more easily choose a different browser from config instead of having to rebuild the project from source.  Thank you again.

**Comment by mapkon** [comment]
OK - that would be good. Maybe you can create a PR from your fork and we consider merging it. Do we still need this issue?
