### ISSUE TITLE
--download-browser-driver recurring failure

### ISSUE THREAD

**Issue by lucasgajewski** [Versent/saml2aws#1098]
Hi folks, 

I've been using saml2aws for a while now, but recently, it broke for me. 
Now, when I run the command listed bellow, I get the following error: 

```
$ saml2aws login --force --download-browser-driver
Using IdP Account default to access Browser https://aws-account-address/
To use saved password just hit enter.
? Username me@me.com
? Password **************

Authenticating as me@me.com ...
Downloading driver to /Users/me/Library/Caches/ms-playwright-go/1.20.0-beta-1647057403000
Downloaded driver successfully

/Users/me/Library/Caches/ms-playwright-go/1.20.0-beta-1647057403000/package/lib/cli/cli.js:263
    require(playwrightTestPackagePath).addTestCommand(_commander.program);
                                       ^

TypeError: require(...).addTestCommand is not a function
    at Object.<anonymous> (/Users/me/Library/Caches/ms-playwright-go/1.20.0-beta-1647057403000/package/lib/cli/cli.js:263:40)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
Error authenticating to IdP.: could not install driver: could not install browsers: could not install browsers: exit status 1
```

I removed the sensitive bits, but I've confirmed that I'm using the right web address and credentials and such for the AWS bit. 

I have tried fully removing and redownloading saml2aws, clearing my node cache, uninstalling node and go, and clearning out the Cache folder that the process is downloading Playwright to. 

When I take a look at the ` /Users/me/Library/Caches/ms-playwright` folder, it's empty. I assume that's where we expect the browsers to go. 

Any advice is appreciated!

**Comment by mapkon** [comment]
Did you follow the instructions here? https://github.com/Versent/saml2aws/pull/1006

**Comment by mikex99** [comment]
I'm also seeing this in my environment.  Mac with 2.36.10

**Comment by lucasgajewski** [comment]
This can be closed out. Updating to 2.36.11 seems to have fixed the issue.
