### ISSUE TITLE
Azure AD: PhoneAppNotification MFA with entropy is unusable with the `quiet` flag

### ISSUE THREAD

**Issue by eacherkan-aternity** [Versent/saml2aws#1128]
Azure AD has a PhoneAppNotification MFA mode, in which the mobile Microsoft Authenticator app is used. If the server is configured to do so, the user will need to input a code into the app. `saml2aws` supports this mode by displaying the code in the following message:
```
Phone approval required. Entropy is: 08
```
However, when running `saml2aws` with the `--quiet` flag, the message is suppressed, and the user has no way of knowing the code to input. This makes the PhoneAppNotification with entropy mode incompatible with `--quiet`.

**Comment by eacherkan-aternity** [comment]
Pull request: https://github.com/Versent/saml2aws/pull/1129

**Comment by mapkon** [comment]
The PR was merged
