### ISSUE TITLE
Segementation faults on Apple MacBook Pro M1

### ISSUE THREAD

**Issue by kbarlowgw** [Versent/saml2aws#1139]
Hiyas,

I've used homebrew to install saml2aws on an Apple MacBook Pro (M1 chip) and keep receiving the following segmentation fault:

`Using IdP Account default to access Browser ******************************************************
Authenticating as **************@******************** ...
INFO[0001] opening browser                               URL="******************************************************" provider=browser
INFO[0002] waiting ...                                   provider=browser
INFO[0032] clean up browser                              provider=browser
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x60 pc=0x104e1e8d8]

goroutine 1 [running]:
github.com/versent/saml2aws/v2/pkg/provider/browser.glob..func1({0x1054fcc98, 0x14000548000}, 0x140000b04d0)
	github.com/versent/saml2aws/v2/pkg/provider/browser/browser.go:98 +0x1b8
github.com/versent/saml2aws/v2/pkg/provider/browser.(*Client).Authenticate(0x1400000e7c8, 0x140000b04d0)
	github.com/versent/saml2aws/v2/pkg/provider/browser/browser.go:78 +0x214
github.com/versent/saml2aws/v2/cmd/saml2aws/commands.Login(0x14000020f00)
	github.com/versent/saml2aws/v2/cmd/saml2aws/commands/login.go:105 +0x458
main.main()
	github.com/versent/saml2aws/v2/cmd/saml2aws/main.go:191 +0x6ddc`

Is there anyway to remedy this?  It was working fine on my old macbook which had intel hardware... do I have to build from scratch?

**Comment by kbarlowgw** [comment]
As noted in the [other post on this issue](https://github.com/Versent/saml2aws/issues/1142), this is indeed hitting the 30s timeout in the playwrite API https://playwright.dev/docs/api/class-page#page-wait-for-request.

I was able to apply a patch locally and can confirm it fixes this issue:

```
	var timeout float64 = 300000
	r, _ := page.WaitForRequest(signin_re, playwright.PageWaitForRequestOptions{Timeout: &timeout})
```

**Comment by bsamartins** [comment]
Is there a fix for this?
Getting the same issue with another provider

```
[signal SIGSEGV: segmentation violation code=0x2 addr=0x60 pc=0x1009ca8e8]

goroutine 1 [running]:
github.com/versent/saml2aws/v2/pkg/provider/browser.glob..func1({0x1010a8c98, 0x14000496000}, 0x140001c24d0)
	github.com/versent/saml2aws/v2/pkg/provider/browser/browser.go:98 +0x1b8
github.com/versent/saml2aws/v2/pkg/provider/browser.(*Client).Authenticate(0x140001967b0, 0x140001c24d0)
	github.com/versent/saml2aws/v2/pkg/provider/browser/browser.go:78 +0x214
github.com/versent/saml2aws/v2/cmd/saml2aws/commands.Login(0x140001b6e80)
	github.com/versent/saml2aws/v2/cmd/saml2aws/commands/login.go:105 +0x458
main.main()
	github.com/versent/saml2aws/v2/cmd/saml2aws/main.go:191 +0x6ddc
```

**Comment by kbarlowgw** [comment]
I've created a pull request to apply my fix - a fixed 5m timeout: https://github.com/Versent/saml2aws/pull/1153

**Comment by gliptak** [comment]
was this fixed in current release?

**Comment by mapkon** [comment]
This was fixed
