### ISSUE TITLE
ADFS with MFA always fails

### ISSUE THREAD

**Issue by pwait** [Versent/saml2aws#114]
Looks like it's regressed - no longer asking for a security code, just lets me straight through to a failed login:

```
Response did not contain a valid SAML assertion
Please check your username and password is correct
```

**Comment by richardkeit** [comment]
@pwait - which version, which provider?

**Comment by pwait** [comment]
@richardkeit Provider [0] ADFS and MFA [1] VIP.

The only v2 I am able to use is the linux binaries, at v2.0.0. Windows (and choco, which is a minor behind) binaries don't seem to work at all with ADFS + VIP.
