### ISSUE TITLE
Segmentation fault on Macbook M2

### ISSUE THREAD

**Issue by mehtaruchir** [Versent/saml2aws#1142]
getting below error for saml2aws -a <profile> login command - specifically for macbook M2 , it works on intel x86 macbook

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x60 pc=0x1050428d8]

goroutine 1 [running]:
github.com/versent/saml2aws/v2/pkg/provider/browser.glob..func1({0x105720c98, 0x14000654000}, 0x1400012e4d0)
	github.com/versent/saml2aws/v2/pkg/provider/browser/browser.go:98 +0x1b8
github.com/versent/saml2aws/v2/pkg/provider/browser.(*Client).Authenticate(0x140000b0840, 0x1400012e4d0)
	github.com/versent/saml2aws/v2/pkg/provider/browser/browser.go:78 +0x214
github.com/versent/saml2aws/v2/cmd/saml2aws/commands.Login(0x14000020f40)
	github.com/versent/saml2aws/v2/cmd/saml2aws/commands/login.go:105 +0x458
github.com/versent/saml2aws/v2/cmd/saml2aws/commands.loginRefreshCredentials(0x140001122a0?, 0x0?)
	github.com/versent/saml2aws/v2/cmd/saml2aws/commands/console.go:105 +0x24
github.com/versent/saml2aws/v2/cmd/saml2aws/commands.loadOrLogin(0x14000022780, 0x0?, 0x140003fa060)
	github.com/versent/saml2aws/v2/cmd/saml2aws/commands/console.go:83 +0x118
github.com/versent/saml2aws/v2/cmd/saml2aws/commands.Console(0x140003fa060)
	github.com/versent/saml2aws/v2/cmd/saml2aws/commands/console.go:46 +0x80
main.main()
	github.com/versent/saml2aws/v2/cmd/saml2aws/main.go:195 +0x6db4

**Comment by mehtaruchir** [comment]
i found 1 behavior pattern, 

now on mac M2 , saml2aws MFA only waits for 30 seconds , if one can not finish the MFA auth from their provider in 30 seconds then we get NIL pointer Segmentation exception.

**Comment by kbarlowgw** [comment]
Sounds like the same issue I am having on the MacBook M1: https://github.com/Versent/saml2aws/issues/1139

**Comment by arobase-che** [comment]
Same on Framework Laptop 13, doesn't seem to be relative to Apple.

**Comment by kbarlowgw** [comment]
It seems to be playwright: https://playwright.dev/docs/api/class-page#page-wait-for-request

I was able to patch it locally: https://github.com/Versent/saml2aws/issues/1139#issuecomment-1761511702

**Comment by mehtaruchir** [comment]
I am still not able to patch it locally. I tried the steps given in #1139

**Comment by mehtaruchir** [comment]
[kbarlowgw](https://github.com/kbarlowgw) -- is it possible to create new release version. 2.36.13 ?

**Comment by kbarlowgw** [comment]
I don't have the ability to release the project.  You need the maintainers
to do that.

**Comment by gliptak** [comment]
is this fixed in current build? artifacts.zip at bottom of https://github.com/Versent/saml2aws/actions/runs/6855210834?pr=1162

**Comment by mehtaruchir** [comment]
not able to test this . artifact.zip. unfortunately.

**Comment by gliptak** [comment]
@mehtaruchir artifact.zip contains platforms specific executables enabling local testing

**Comment by tinaboyce** [comment]
> [kbarlowgw](https://github.com/kbarlowgw) -- is it possible to create new release version. 2.36.13 ? 

@mehtaruchir there is currently a new release version.  Are you able to see if the new version fixes the issue?
