### ISSUE TITLE
incorrect environment variable in docs: SAML_DUO_MFA_OPTION should be SAML2AWS_DUO_MFA_OPTION

### ISSUE THREAD

**Issue by matthewchao** [Versent/saml2aws#1166]
https://github.com/Versent/saml2aws/blame/f91a0bd7a67d84e0e6c36178394cc5feca994162/README.md#L244

I tried the latter based on the names of other environment variables in use; only SAML2AWS_DUO_MFA_OPTION was picked up by `saml2aws login ...`

**Comment by tinaboyce** [comment]
You are correct, the env variable is a typo. I made a Pull Request https://github.com/Versent/saml2aws/pull/1171/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R243 to fix this in the README in amongst some README and help command flag house-keeping.
