### ISSUE TITLE
Feature: Automatically set environment variables via a flag

### ISSUE THREAD

**Issue by darrenhaken** [Versent/saml2aws#117]
Some of the SDK libraries I use depend on AWS environment variables being set in order to work.

It would be useful if there was a flag to pass during login so they are set within the Bash/ZSH profile.

Example `saml2login --set-env-vars`

Any appetite for this?

**Comment by wolfeidau** [comment]
I don't think this is possible, mutating env vars in the parent shell is a security issue. 

```

**Comment by felipe1982** [comment]
Couldn't we just `source` the script, such as `. saml2aws [...]` (or `$(saml2aws)`) and then saml2aws just prints the BASH commands required to set the current environment properly? This allows saml2aws to remain _"secure"_ will at the same time giving the user the opportunity to set their environment they way they desire for they workflow.

I have been using [Awsume](/trek10inc/awsume) which works similar to this. The command `awsume` is actually an alias for `. awsume` which sets the current shell environment.

**Comment by unfor19** [comment]
I know this is an old issue, but in case someone needs the "export VARS" message, like it appears in the AWS SSO page, here's how I managed to achieve it-

```bash
saml2aws exec env | grep '^AWS_SESSION_TOKEN\|ACCESS_KEY\|SECRET_ACCESS_KEY' | sort | sed -e 's/^/export /'
```

The above code generates the following message
```bash
export AWS_ACCESS_KEY_ID=.....
export AWS_SECRET_ACCESS_KEY=.....
export AWS_SESSION_TOKEN=......
```

And then it's just a simple copy-paste, which is great, because sometimes I use the creds on a remote server, so it's very useful.

**Comment by mapkon** [comment]
There is a workaround documented [here](https://github.com/Versent/saml2aws/issues/117#issuecomment-879041352). Closing the issue - if someone needs this worked on, I am welcome to coordinate the PR merge.
