### ISSUE TITLE
Please help on Okta MFA

### ISSUE THREAD

**Issue by kevbook** [Versent/saml2aws#118]
Sorry, I never ask these questions on repo issues. [`v2.0.3` on mac 10.13.2]

Config for multi-account done exactly as here http://saml-doc.okta.com/SAML_Docs/How-to-Configure-SAML-2.0-for-Amazon-Web-Service.html

* When I setup Okta with NO MFA - things work just fine. 
* But with MFA setup on AWS (google authenticator) - I do `saml2aws login --verbose` or `saml2aws login --verbose --mfa="totp"`

```
Response did not contain a valid SAML assertion
Please check your username and password is correct
```

**Comment by wolfeidau** [comment]
Have you tried disabling MFA and logging in?

Just to ensure your basic configuration is working.

**Comment by kevbook** [comment]
Oh yea basic works just fine with multiple AWS accounts, using `saml2aws` & okta web.
But `saml2aws` gives me the above error when MFA is enabled

**Comment by chamila-c** [comment]
Any chance this is related to https://github.com/Versent/saml2aws/issues/84 ?

**Comment by kevbook** [comment]
Seems like when MFA on Okta is setup on okta org level, this works. But not if MFA is setup at the AWS app level.

**Comment by kevbook** [comment]
See this as well. https://github.com/Nextdoor/nd_okta_auth/issues/2

**Comment by etendards** [comment]
Is this still an issue?  How do we enable MFA with CLI?

**Comment by wolfeidau** [comment]
OK I need to fire up my okta developer account and take a look at the output of --debug. 

I didn't even know you could do per app configuration of MFA.

**Comment by wolfeidau** [comment]
@pwmcintyre How are you configuring this at the moment?

**Comment by emmanuel** [comment]
I'm experiencing this same issue with 2.5.0 on macOS; my organization has Okta configured for MFA on a per-application basis (i.e., MFA is enabled for AWS, but not all apps in the tenant). (Based on my understanding of the underlying issue, neither the version of `saml2aws` nor my OS are relevant, however.) 

I have cycles to prepare a patch for this functionality, but I think I'll need a little guidance to do so effectively. Can someone help me sort out how to diagnose what Okta does differently in the per-application case vs. in the tenant-wide case?

**Comment by emmanuel** [comment]
... looks like I have to rescind my offer here; I was mistaken about having cycles for this. My organization is switching to org-wide MFA tomorrow, so there's no justification for investing dev effort in support of app-level MFA. 

Apologies for the offer-then-retraction.

**Comment by katiegamanji** [comment]
Hello, 

We are looking for a solution to use MFA at the application level. Any updates on this issue? 

Or any indications on how can this be solved?

**Comment by sagar-srivastava** [comment]
I confirm, app level MFA enforcement accounts are failing while it works for Org level exactly as @kevbook mentioned

**Comment by MukeshSingh28** [comment]
The same issue persist for me too. Expecting for a solution sooner or later. Thank you

**Comment by Meroje** [comment]
I had a look at this, and it seems there is no way to handle this mfa setup without running a browser capable of running javascript.

**Comment by dmmsonos** [comment]
Can anyone on this thread confirm that they saw the app-level MFA issue with Duo specifically? I see that the code for Duo is fairly different from the other cases. Would save me the time of setting up an evaluation Duo account to find out what I already suspect...

**Comment by dmmsonos** [comment]
Good news for anyone using Duo MFA with Okta: 

**saml2aws works with application-level MFA for Duo**

🎉

**Comment by alsmola** [comment]
I think this should fix Okta with TOTP MFA: https://github.com/Versent/saml2aws/pull/369

**Comment by joshk0** [comment]
repeating myself from PR for visibility:

> I can confirm this works for me and to be more precise, it fixes the case where an app level MFA policy is enabled on AWS. This change is not necessary _unless_ that is the case, and it fixes interaction with all second factors, not just TOTP.
