### ISSUE TITLE
Feature: Support for OneLogin as IDP

### ISSUE THREAD

**Issue by cjbischoff** [Versent/saml2aws#121]
Just looking to see if any plans to support OneLogin for an IDP

**Comment by pavelnikolov** [comment]
Next week I am planning to work on a PR to add support for OneLogin. Any tips would be appreciated.

**Comment by mumoshu** [comment]
@pavelnikolov I'd suggest using the `Generate SAML Assertion` API documented [here](https://developers.onelogin.com/api-docs/1/saml-assertions/generate-saml-assertion). Basically, you can consume id/pass and otp from user input, and then pass it to the API to obtain a SAML assertion, which is then used for [`AssumeRoleWithSAML`](https://github.com/Versent/saml2aws/blob/73cefb0097ea8ee0949aed261af9999294dd6c5f/cmd/saml2aws/commands/login.go#L242).

**Comment by pavelnikolov** [comment]
This comment comes just on time because I literally just resumed my work on this task! Thank you, I’ll review it.

**Comment by pavelnikolov** [comment]
I've got it working. I'll just need to add better test coverage and I'll send a PR. Just wondering what's your preference for provider specific configuration. OneLogin needs 3 additional params `app_id`, `client_id` and `client_secret`. I'm saving `client_*` into the keychain and `app_id` in the config. I have two options - either add interface method that would allow additional provider config (requires some refactoring); or add provider specific config into the common cfg struct (which I don't like).

**Comment by cjbischoff** [comment]
@pavelnikolov Wow thank you - will take a peek

**Comment by pavelnikolov** [comment]
As mentioned in my previous comment, I would like to refactor the code. OneLogin requires four additional params:
* app_id - your application connector id
* subdomain - your organisation unique identifier. Usually used to access OL dashboard https://<subdomain>.onelogin.com
* client_id - Used for generating tokens for authentication with OL APIs.
* client_secret - same as above. I store these two in the keychain. Client ID and client secret are application credentials and not user credentials. 
I’ve added these to the common config and populate them conditionally. Client ID and secret are added as flags during configuration. I would prefer adding app-specific configuration, secrets and flags. However, I wanted to keep this PR minimal.

**Comment by cjbischoff** [comment]
@pavelnikolov Do you have an example of adding/running saml2aws using OneLogin?  I attempted via the prompted method and received the following
```
? Password ***
? Confirm ***
OneLogin provider requires --client_id and --client_secret flags to be set.```

Then I attemped to use the cli option format to add

```
./saml2aws configure -a PROFILE --idp-provider OneLogin --username username@email.com --url https://api.us.onelogin.com --skip-prompt --subdomain SUBDOMAIN --client_id 1234567890 --client_secret  1234567890```

Following error

```
saml2aws: error: unknown long flag '--client_id', try --help
```

**Comment by wolfeidau** [comment]
I am going to call this ticket done, I think there is definitely work that can be done on making the setup experience better. I am open to suggestions, I will take a swipe at it in the next few weeks when I add support for openid auth for one of the providers.

Cheers 🎉

**Comment by pavelnikolov** [comment]
I’ll push a PR with some documentation soon.

**Comment by pitbulk** [comment]
https://github.com/onelogin/onelogin-python-aws-assume-role
