### ISSUE TITLE
Feature: Support RSA SecurID MFA/SMS tokens

### ISSUE THREAD

**Issue by luckylittle** [Versent/saml2aws#122]
### Allow this behavior via the saml2aws CLI tool
1. Log in with your AD credentials on the ADFS portal - e.g. `https://fs.EXAMPLE.com/adfs/ls/idpinitiatedsignon`
2. Enter your RSA SecurID passcode/PIN - e.g. `1234`
3. Receive a token on your mobile phone
4. Enter the tokencode to be authenticated - e.g. `12345678`
### Requirements
- Directory Service
- ADFS2
- RSA SecurID
- Mobile phone

**Comment by wolfeidau** [comment]
This is now supported with some caveats.

**Comment by Buhtigs** [comment]
We use RSA with SMS together with ADFS2. If I try to login, I do not receive any SMS. It seems like there is no trigger to send SMS. 
Does this work for someone? 

@wolfeidau What are the "caveats"?
