### ISSUE TITLE
Disabling private mode in the Edge browser

### ISSUE THREAD

**Issue by mwalkowski** [Versent/saml2aws#1234]
Hello Everyone,

By default, the parameter `--browser-type=msedge` launches the browser in private mode. Is there a way to change this behavior? One of my clients has quite specific requirements, and the private mode is a slight blocker for us. Alternatively, please give me a hint on where I can adjust the configuration.

I also tried with `browser-executable-path`, but I don't know how to modify the list of parameters with which Edge is invoked.

**Comment by mapkon** [comment]
No, not that I am aware of, but I have also not looked for and wide. Probably asking on the playwright repo might surface better answers

**Comment by timharris777** [comment]
My PR solves this issue: https://github.com/Versent/saml2aws/pull/1267
