### ISSUE TITLE
Bump the MacOS runners to use non-deprecated runners (Probably MacOS-14)

### ISSUE THREAD

**Issue by mapkon** [Versent/saml2aws#1302]
### Context

Jobs are failing with this message
```This is a scheduled macOS-11 brownout. The macOS-11 environment is deprecated and will be removed on June 28th, 2024.```

This is because the MacOS-11 environment is deprecated. We need to bump it to the latest. 

### Expected Outcomes

- Bump the MacOS runners in the workflows to use the latest environment. 
  - The changes should be made in the `.github/workflows/go.yml` 
  - I think we should test with `MacOS-14`, which if successfully should be the runner of choice moving forward
- Ascertain that the subsequent builds work fine
  - Attempt a local release and check binary compatibility
  - Ensure that the coverage reports are created properly.
 
### References

- https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md

**Comment by tinaboyce** [comment]
This could be duplicating effort as according to https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-private-repositories, `macos-latest` already uses `macos-14`

**Comment by mapkon** [comment]
Thanks @tinaboyce 

@gliptak do we still need MacOS-11? I remember some reason why we maintained?

**Comment by gliptak** [comment]
maybe it was amd64 vs arm64? the least could be bumped to https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md at this point

**Comment by mapkon** [comment]
CC: @charlottecampbell193

**Comment by mapkon** [comment]
> maybe it was amd64 vs arm64? the least could be bumped to https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md at this point

What would be the material effect of just removing it?

**Comment by gliptak** [comment]
I think testing both amd64 and arm64 still of value

**Comment by charlottecampbell193** [comment]
Is there a reason we are testing on ubuntu-latest, macOS-latest, macos-12 and releasing on ubuntu-latest, ubuntu-20.04, macos-latest?

**Comment by gliptak** [comment]
@charlottecampbell193 testing is based on runner while releasing on cross platform GoReleaser

if applicable, please propose realignment
