### ISSUE TITLE
email and password autocomplete in Browser mode

### ISSUE THREAD

**Issue by lolgab** [Versent/saml2aws#1309]
It would be nice if the browser mode could autocomplete the email and password when logging in in Google. It's annoying having to type the password especially for people who use their browser's password manager, since the browser runs in a clean session (as it should).

**Comment by cjerdonek** [comment]
If you run `saml2aws --help`, you can see there is a `--browser-autofill ` option:
```
--browser-autofill

  Configures browser to autofill the username and password. (env: SAML2AWS_BROWSER_AUTOFILL)
```

**Comment by lolgab** [comment]
Oh wow, had no idea, that's wonderful, thank you

**Comment by lolgab** [comment]
It doesn't seem to work though. Maybe Google changed their login page.

**Comment by cjerdonek** [comment]
> It doesn't seem to work though. Maybe Google changed their login page.

Yeah, I'm not surprised. When I looked at the code implementing their auto-fill feature, it seemed to make some pretty strong assumptions about how the login page needs to be structured. The code can be find here (`autoFill()` function of `pkg/provider/browser/browser.go`):
https://github.com/Versent/saml2aws/blob/953bb29bdfde76a240ec6a8bac8463ff3a5c5f9f/pkg/provider/browser/browser.go#L205

Thus, I would keep this issue but retitle it to something like, "Make `--browser-autofill` feature work with Google's login page."

**Comment by cjerdonek** [comment]
Btw, this issue is related to making `--auto-fill` work with Google's login page: https://github.com/Versent/saml2aws/issues/1295

**Comment by lolgab** [comment]
Thank you, I will follow that issue then 👍
