### ISSUE TITLE
W10, pointing to wrong drive.

### ISSUE THREAD

**Issue by shanep2300** [Versent/saml2aws#131]
Not sure why it's pointing to U:\ as that is a network drive and it's disconnected. Aws files found in C:\Users\<user>

v2.2.0

`open U:\.saml2aws.438714100.tmp: The system cannot find the path specified.
Failed to save configuration file
github.com/versent/saml2aws/pkg/cfg.(*ConfigManager).SaveIDPAccount
        /Users/markw/go/src/github.com/versent/saml2aws/pkg/cfg/cfg.go:108
github.com/versent/saml2aws/cmd/saml2aws/commands.Configure
        /Users/markw/go/src/github.com/versent/saml2aws/cmd/saml2aws/commands/configure.go:38
main.main
        /Users/markw/go/src/github.com/versent/saml2aws/cmd/saml2aws/main.go:112
runtime.main
        /usr/local/Cellar/go/1.9.2/libexec/src/runtime/proc.go:195
runtime.goexit
        /usr/local/Cellar/go/1.9.2/libexec/src/runtime/asm_amd64.s:2337
failed to save configuration
github.com/versent/saml2aws/cmd/saml2aws/commands.Configure
        /Users/markw/go/src/github.com/versent/saml2aws/cmd/saml2aws/commands/configure.go:40
main.main
        /Users/markw/go/src/github.com/versent/saml2aws/cmd/saml2aws/main.go:112
runtime.main
        /usr/local/Cellar/go/1.9.2/libexec/src/runtime/proc.go:195
runtime.goexit
        /usr/local/Cellar/go/1.9.2/libexec/src/runtime/asm_amd64.s:2337`

**Comment by davidobrien1985** [comment]
How did you install `saml2aws`?
What does your `$env:PATH` look like?

**Comment by shanep2300** [comment]
Installed using Chocolatey

`PATH=C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\RSA SecurID Token Common;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\nodejs\;C:\Program Files\PuTTY\;C:\Program Files\Git\cmd;C:\ProgramData\chocolatey\bin;C:\Program Files\Amazon\AWSCLI\;C:\Users\spollock\AppData\Roaming\npm;C:\Users\spollock\AppData\Local\atom\bin;C:\Program Files\Microsoft VS Code\bin`

**Comment by shanep2300** [comment]
Fixed by completely uninstalling saml2aws and chocolatey. including any variables added from chocolatey. Reinstalled chocolatey and saml2aws and it worked perfectly. Not sure how it changed randomly from C:\ to U:\ before though.

**Comment by wolfeidau** [comment]
Great news! Thanks for your feedback.

**Comment by srigumm** [comment]
I am seeing this issue in my machine, I installed it through choco in my windows box.. looks like its a hidden bug triggered thorugh something. Fixing this issue could help someone.
![image](https://user-images.githubusercontent.com/44202047/73547110-4ff56500-440c-11ea-878a-f325e26eb5f4.png)
,

**Comment by srigumm** [comment]
@wolfeidau  please help to resolve this issue.. 
My system path variable is not pointing to h: drive at all.
