### ISSUE TITLE
-a Flag not picking profile

### ISSUE THREAD

**Issue by mksquared** [Versent/saml2aws#137]
Anyone having issues with 2.1.0 with -a not allowing to pick the correct saml2aws profile when using exec.

**Comment by briceburg** [comment]
I confirm that version 2.1.0 breaks idp profile selection on the `exec ` command;

```
saml2aws -a PROFILE exec -- ls
``` 
fails to run under the specified profile. It used the default.

```
saml2aws -a PROFILE login
``` 

appears to work.

**Comment by briceburg** [comment]
The `2.2.0` release appears to fix exec, although is not available to homebrew. A PR has been created to get this published; https://github.com/Versent/homebrew-taps/pull/5

**Comment by wolfeidau** [comment]
This was merged.
