### ISSUE TITLE
error retieving mfa response

### ISSUE THREAD

**Issue by jupalls** [Versent/saml2aws#145]
We are using pingfed with DUO MFA. I feel the logic to extractFormData() is looking for "form" may not always work. In our case we reposting to duo at the form.init(). I can make PR with a possible fix once the https://github.com/kataras/iris/issues/605 is fixed. At present not able to build the code du to broken gokg.in issue

                           
DEBU[0021] POST                                          actionURL= provider=pingfed
Post : unsupported protocol scheme ""
error retieving mfa response

**Comment by wolfeidau** [comment]
At this point Pingfed only supports Ping MFA, supporting DUO MFA would require some integration work and testing.
