### ISSUE TITLE
Add feature for non-interactive logging into an account

### ISSUE THREAD

**Issue by behrangsa** [Versent/saml2aws#147]
Hi,

When I run `saml2aws -p dev login`, at first I am prompted with something like this:

```
Using IDP Account default to access ADFS https://sts.example.com
To use saved password just hit enter.
Username [behrangsa@example.com]:
```

I press enter then I am presented with:

```
Password:
```

My password is saved, so I press enter and go to the next step:

```
Authenticating as behrangsa@example.com ...
Please choose the role you would like to assume:
Account: cloud-dev (123456789000)
[ 0 ]:  cloud-dev-developer
[ 1 ]:  cloud-dev-readonly

Account: cloud-management (123456789111)
[ 2 ]:  cloud-management-readonly

Account: cloud-prod (123456789222)
[ 3 ]:  cloud-prd-readonly
[ 4 ]:  cloud-prd-support
```

As this is for my `dev` AWS profile (I ran saml2aws with `-p dev`), I choose 0 and then I get authenticated.

Ideally I am looking for a way to do something like this, without any interactivity:

```
$ saml2aws -p dev --account 123456789000 --role cloud-dev-developer
```

It would be nice if `saml2aws` could do this. Then I can create shell aliases for quickly logging into `dev`, `prd`, etc. accounts or create a crontab entry to refresh the tokens once every 60 minutes.

**Comment by jwdinkel** [comment]
Would it make sense to enumerate the roles using the current function list-roles https://github.com/Versent/saml2aws/pull/126 ?

If a unique short code could be generated for each account and role, we could then use it for the saml2aws login --role-code=shortcode

If the list can be stored to a config file allowing an alias to be typed for each line, then perhaps the idea of picking dev/test/prod for certain projects could be easier.

**Comment by arecker** [comment]
> If a unique short code could be generated for each account and role,
> we could then use it for the saml2aws login --role-code=shortcode

You can already specify a --role option to pick a role non
interactively.  You just need to know the ARN (which includes the
account number).  So enumerating them and selecting by index isn't
necessary.

**Comment by emmanuel** [comment]
Tip: use `saml2aws list-roles` to retrieve the list of role ARNs that you have access to.

**Comment by emmanuel** [comment]
I login in non-interactively every day. To do so, use the `--role` flag, as @arecker mentioned, and combine that with the `--skip-prompt` flag for a single-command login. My command looks like:

```
saml2aws login --idp-account=$SAML2AWS_IDP_ACCOUNT_NAME --role=$AWS_ROLE_ARN --skip-prompt
```

I believe this issue can be closed.

**Comment by behrangsa** [comment]
@emmanuel I started doing the same since a couple of weeks ago.

So I think now we can close this ticket now.

For people who might stumble upon this in the future, here's what you need to do (assuming you have already logged in once and have instructed saml2aws to save your credentials in Key Chain, etc.)

```
$ saml2aws login [-p <profile-name>] \
                 --role=<role arn> \
                 --skip-prompt
```

This will work if you have only one IDP account. If you have more, you can select it explicitly:

```
$ saml2aws login [-p <profile-name>] \
                 --idp-account=<idp account> \
                 --role=<role arn> \
                 --skip-prompt
```
