### ISSUE TITLE
Okta Push MFA fails on Windows, succeeds on OSX/Linux

### ISSUE THREAD

**Issue by wwboynton** [Versent/saml2aws#149]
In OSX and Linux, I can run `saml2aws login` against Okta as a provider with Okta Push for MFA without issues. 

Within Windows, however, built from the same source, it seems like the same exact login call fails.

The exact place where it fails is here, on line `268` of `saml2aws/pkg/provider/okta/okta.go` where `err` is not equal to `nil`:

```go
	case IdentifierPushMfa:

		fmt.Printf("\nWaiting for approval, please check your Okta Verify app ...")

		// loop until success, error, or timeout
		for {

			res, err = oc.client.Do(req)
			if err != nil {
				return "", errors.Wrap(err, "error retrieving verify response")
			}
# ...
```

Stack trace follows:

```powershell
Using IDP Account PDR to access Okta https://xxxxx.okta.com/home/amazon_aws/xxxxx/xxx
To use saved password just hit enter.
Username [wboynton@xxxxxxx.com]:
Password:
Authenticating as wboynton@xxxxxxxx.com ...
  1) PUSH MFA authentication
  2) UNSUPPORTED: OKTA TOKEN:SOFTWARE:TOTP
Select which MFA option to use: 1
Waiting for approval, please check your Okta Verify app ...Post https://intersections.okta.com/api/v1/authn/factors/opfi
p6xmv8wjCe8zE0x7/verify: http: ContentLength=60 with Body length 0
error retrieving verify response
github.com/versent/saml2aws/pkg/provider/okta.verifyMfa
        c:/gopath/src/github.com/versent/saml2aws/pkg/provider/okta/okta.go:268
github.com/versent/saml2aws/pkg/provider/okta.(*Client).Authenticate
        c:/gopath/src/github.com/versent/saml2aws/pkg/provider/okta/okta.go:128
github.com/versent/saml2aws/cmd/saml2aws/commands.Login
        c:/gopath/src/github.com/versent/saml2aws/cmd/saml2aws/commands/login.go:54
main.main
        c:/gopath/src/github.com/versent/saml2aws/cmd/saml2aws/main.go:104
runtime.main
        C:/go/src/runtime/proc.go:183
runtime.goexit
        C:/go/src/runtime/asm_amd64.s:2086
error verifying MFA
github.com/versent/saml2aws/pkg/provider/okta.(*Client).Authenticate
        c:/gopath/src/github.com/versent/saml2aws/pkg/provider/okta/okta.go:130
github.com/versent/saml2aws/cmd/saml2aws/commands.Login
        c:/gopath/src/github.com/versent/saml2aws/cmd/saml2aws/commands/login.go:54
main.main
        c:/gopath/src/github.com/versent/saml2aws/cmd/saml2aws/main.go:104
runtime.main
        C:/go/src/runtime/proc.go:183
runtime.goexit
        C:/go/src/runtime/asm_amd64.s:2086
error authenticating to IdP
github.com/versent/saml2aws/cmd/saml2aws/commands.Login
        c:/gopath/src/github.com/versent/saml2aws/cmd/saml2aws/commands/login.go:56
main.main
        c:/gopath/src/github.com/versent/saml2aws/cmd/saml2aws/main.go:104
runtime.main
        C:/go/src/runtime/proc.go:183
runtime.goexit
        C:/go/src/runtime/asm_amd64.s:2086
```

Unfortunately, using the `--verbose` flag doesn't actually show the content of `err` to determine why it might be failing. All I know is the same machine, running from the same network segment, built from master (but booted into linux) will succeed using the same call. This rules out any configuration issue in Okta, and makes it seem like the issue is in some part of the way saml2aws in Windows sends/receives the call to see if the MFA push has been approved/denied yet.

Based on the fact that line `287` (of the `"WAITING"` case) never gets to print a `.`, it seems like `err != nil` on the very first loop through.

I'm not sure where to go from here, but if there's anything you'd like me to do to troubleshoot, please let me know. As of now, this is totally breaking on Windows for Okta Verify Push.

**Comment by wolfeidau** [comment]
Heya I would love to know whether https://github.com/Versent/saml2aws/tree/fix_update_transport_defaults helps as i have adjusted all the timeouts in line with the stdlib.

Reading over the code and i can't see anything obvious.

**Comment by chad-cook** [comment]
Can confirm im getting this as well.

**Comment by chad-cook** [comment]
Disregard the above. Under version 2.3.0 there is an issue. If you manually update to 2.5.0 the issue is fixed. Please see https://github.com/Versent/saml2aws/issues/177 for bug of choco not publishing the latest.

**Comment by wolfeidau** [comment]
Now updated to the latest version.
