### ISSUE TITLE
Support Awscli profile function

### ISSUE THREAD

**Issue by jitesh88** [Versent/saml2aws#153]
support profile function to be able to execute awscli commands under different accounts without having to login each time.

i.e.
aws ec2 describe-instances --profile mode0Prod
aws ec2 describe-instances --profile mode0NonProd

**Comment by valtaz** [comment]
Hey @jitesh88 
if you login with profile flag (--profile="mode0Prod"), you can use the command as you mention

`-p, --profile="saml"     The AWS profile to save the temporary credentials`

**Comment by jitesh88** [comment]
thanks, that works. would be good to have this documented in the usage section. cheers
