### ISSUE TITLE
Okta TOTP doesn't work

### ISSUE THREAD

**Issue by Russell-IO** [Versent/saml2aws#160]
Okta Verify supports TOTP mode when Push isn't enrolled / available
This is identical to Google Authenticator, however the API name returned back from Okta is different.

**Comment by Russell-IO** [comment]
Have adjusted the relevant code in the Okta provider,

**Comment by Russell-IO** [comment]
If anyone else is blocked, there is an unofficial release here: https://github.com/Russell-IO/saml2aws/releases/tag/v2.4.1-russ, PR into mainstream is pending

**Comment by wolfeidau** [comment]
Merged and released as 2.4.1.

Cheers for the fix!

**Comment by Russell-IO** [comment]
👍
