### ISSUE TITLE
Parallel execution not possible

### ISSUE THREAD

**Issue by Rukenshia** [Versent/saml2aws#162]
Hello,

I'm part of a team that manages over 90 different AWS accounts and I switch between them regularly, hence I have the need to have multiple AWS credentials at the same time. Our IDP (KeyCloak) requires MFA. I have a small script that runs saml2aws sequentially right now but sometimes the MFA token expires in that time. I now tried speeding up that by making the `saml2aws login` calls in parallel, but it seems like the builtin Credentials manager that saves my credentials to the OS X Keychain gets race conditions there and is unable to save them. The error message I get is:

```
Invalid record was encountered
error storing password in keychain
```

## A modest proposal

Either we try to resolve the issue with the credentials manager (which might be very tricky), or we add a flag that just skips saving the credentials in the keychain (`--no-save` or something). I'm not sure if it will be enough to only skip saving credentials in the keychain or if we might have to output the AWS credentials instead of saving them in the local file as well. What do you think? Is there another (easier) solution maybe?

I'd be happy to try and help out with my suggestion as well.

**Comment by xavipanda** [comment]
wonder why this has been closed, such a legit request.. i have 20 accounts to login, cant do saml2aws & , has to be one by one with the TOTP??... is that a requirement to actually take 3-5minutes to login in the accounts ??

**Comment by Rukenshia** [comment]
hey,

I closed my original request as I ended up creating my own saml2aws for the specific use case I had - it probably would still make sense to have it but I didn't want to keep a ticket open when I already moved on to avoid bloating the issues here :)
