### ISSUE TITLE
"error authenticating mfa" when using ping provider with 2fa (via pingid)

### ISSUE THREAD

**Issue by mcleane** [Versent/saml2aws#166]
Users are unable to authenticate via saml2aws with the following error when attempting to authenticate via their ping provider when 2fa is enabled.
```
Post : unsupported protocol scheme ""
error authenticating mfa
```

On May 1, 2018, PingId released an update to the out-of-the-both UI to change to asynchronous calls to the PingId server.

Extract from release notes:
```
Enhancements
PingID out-of-the-box UI supports asynchronous calls to the PingID server
PingID out-of-the box UI now uses asynchronous calls to the PingID server when performing authentication. This capability further increases PingID's capacity to support high volumes of simultaneous authentication requests, and strengthens the resiliency of the PingID service. It also provides the infrastructure required to enable administrators to customize the authentication timeout value; a feature planned for future release.
```

saml2aws was written based on the previous implementation of a synchronous call to the PingId server. 

Until changes are made to the code, users will be unable to authenticate with saml2aws when a ping provider with 2fa is used.

**Comment by wolfeidau** [comment]
Thanks to @Anton0 this has been resolved in #169
