### ISSUE TITLE
Chocolatey not publishing latest build

### ISSUE THREAD

**Issue by chad-cook** [Versent/saml2aws#177]
Chocolatey is only publishing 2.3.0 instead of 2.5.0 

![greenshot 2018-06-05 16 41 28](https://user-images.githubusercontent.com/16995512/40959245-79309804-68df-11e8-8da0-adef537cff42.png)

This is possibly linked to https://github.com/Versent/saml2aws/issues/130

**Comment by SteveMadigan** [comment]
How can I get 2.5.0 without choco?

**Comment by chad-cook** [comment]
https://github.com/Versent/saml2aws/releases

**Comment by gliptak** [comment]
The Appveyor build is broken https://ci.appveyor.com/project/davidobrien1985/saml2aws/branch/master

**Comment by wolfeidau** [comment]
Now updated to the latest version.
