### ISSUE TITLE
Save a default role

### ISSUE THREAD

**Issue by xiaket** [Versent/saml2aws#188]
Being in a company that uses lots of roles, the selection of a specific role can be quite painful. Most of the time we'll be using a test role so I would suggest that we could store the last used AWS role somewhere and re-use it as the default value for role selection after authentication.

Or perhaps we could ask the user to configure a default role somewhere in the `configure` subcommand?

**Comment by munkyboy** [comment]
there is a `--role` argument. https://github.com/Versent/saml2aws/blob/master/cmd/saml2aws/main.go#L61

Does that do what you expect?

**Comment by xiaket** [comment]
@munkyboy Thanks! I guess I can do with a wrapper script around saml2aws and use this argument.
