### ISSUE TITLE
ADFS2 can't find IDP authentication form submit URL

### ISSUE THREAD

**Issue by jbruett** [Versent/saml2aws#21]
Trying to auth to ADFS v2 environment and getting the following using version 1.4.0.  I don't control/have access to ADFS.  Let me know if there is anything else I can try for you.

C:\Users\jbruett>saml2aws --profile ADFS2 login
Hostname []: adfs.******.com
Username []: jbruett
Password: ***********

ADFS https://adfs.******.com
Authenticating to ADFS...
main.go:66: error authenticating to adfs: unable to locate IDP authentication form submit URL

C:\Users\jbruett>saml2aws --profile ADFS2 login
Hostname []: adfs.****.com/adfs/ls/IdpInitiatedSignon.aspx
Username []: jbruett
Password: ***********

ADFS https://adfs.******.com/adfs/ls/IdpInitiatedSignon.aspx
Authenticating to ADFS...
main.go:66: error authenticating to adfs: unable to locate IDP authentication form submit URL

C:\Users\jbruett>saml2aws --profile ADFS2 login
Hostname []: adfs.******.com
Username []: jbruett@******.com
Password: ***********

ADFS https://adfs.******.com
Authenticating to ADFS...
main.go:66: error authenticating to adfs: unable to locate IDP authentication form submit URL

C:\Users\jbruett>saml2aws --profile ADFS2 login
Hostname []: adfs.****.com/adfs/ls/IdpInitiatedSignon.aspx
Username []: jbruett@****.com
Password: ***********

ADFS https://adfs.******.com/adfs/ls/IdpInitiatedSignon.aspx
Authenticating to ADFS...
main.go:66: error authenticating to adfs: unable to locate IDP authentication form submit URL

**Comment by wolfeidau** [comment]
Gday 

I am guessing you have miss read the README, you need to use `--provider="ADFS2"` not `--profile`, that is used to update the AWS CLI profile.

Cheers

**Comment by jbruett** [comment]
ok, so that was definitely the case, sorry for that..however it's still failing.  our setup uses DUO MFA immediately after ADFS login, is that supported, I'm thinking not as I don't see it in the documentation anywhere.

**Comment by wolfeidau** [comment]
I don't have access to DUO MFA worst luck, would need some debugging at your end to come up with a solution on this.

**Comment by mapkon** [comment]
Is this ticket still valid? I would like to start closing some of these tickets

**Comment by mapkon** [comment]
Closing as there has been no meaningful traction in years
