### ISSUE TITLE
DUO MFA response format changes

### ISSUE THREAD

**Issue by bwhaley** [Versent/saml2aws#211]
Yesterday (2018/8/21) we found that Duo changed the format of its MFA response status in a way that broke saml2aws. I have patched it in a fork and would be happy to submit the update here but not sure if the change was global or somehow account specific. Anyone else using Duo care to comment on whether `saml2aws` is now broken for you?

**Comment by amcbride** [comment]
Yes, broken for me aws well with okta + duo

**Comment by wolfeidau** [comment]
This should be fixed for for Okta.
