### ISSUE TITLE
v2.8.0 broken on ubuntu 14.04

### ISSUE THREAD

**Issue by jfleong** [Versent/saml2aws#219]
https://github.com/Versent/saml2aws/pull/210 introduced support for the linux secret_service which actually breaks saml2aws on my ubuntu 14.04 box. I did not have dbus installed or gnome-keyring which I tried to install but couldn't for the life of me get everything to play nicely together. Has anyone else seen this issue?

**Comment by wolfeidau** [comment]
I am currently refactoring this to use some of the code from https://github.com/99designs/keyring to remove the CGO dependency and simplify builds. 

Have you tried downgrading or do you required the latest version?
