### ISSUE TITLE
saml2aws login suddenly stopped working

### ISSUE THREAD

**Issue by srflaxu40** [Versent/saml2aws#224]
```
~/kops-drivers/bin$ saml2aws login
Using IDP Account default to access JumpCloud https://sso.jumpcloud.com/saml2/redacted
To use saved password just hit enter.
Username [johnson.redacted@redacted.com]: 
Password: *************

Authenticating as johnson.redacted@redacted.com ...
unable to locate IDP authentication form submit URL
error authenticating to IdP
github.com/versent/saml2aws/cmd/saml2aws/commands.Login
	/Users/markw/go/src/github.com/versent/saml2aws/cmd/saml2aws/commands/login.go:56
main.main
	/Users/markw/go/src/github.com/versent/saml2aws/cmd/saml2aws/main.go:106
runtime.main
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/proc.go:195
runtime.goexit
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/asm_amd64.s:2337
```

Can no longer use `saml2aws login` on sso endpoints.  It seems that maybe something between it and IdP (JumpCloud)?

Trying with verbose flag gives same error.

**Comment by vr00n** [comment]
Same here

**Comment by btsteve** [comment]
Same Here

**Comment by fogfish** [comment]
JumpCloud has changed the layout of they login screen.  I hope you guys know how to fix it. I am also escalating this issue to JumpCloud support team.

**Comment by fogfish** [comment]
What I can say here that they replace a traditional web form with scripted version. Therefore 
https://github.com/Versent/saml2aws/blob/master/pkg/provider/jumpcloud/jumpcloud.go#L66 code is not able to detect an action to post data.

I really do not understand, why this guys do not thing about compatibility.

**Comment by jefmsmit** [comment]
Hi everyone. I'm Jeff from JumpCloud. 
We did change our login page today in order to make the experience the same for authentication for SAML as well as other uses. We did not realize that this library was scraping our old form.

**Comment by btsteve** [comment]
> Hi everyone. I'm Jeff from JumpCloud.
> We did change our login page today in order to make the experience the same for authentication for SAML as well as other uses. We did not realize that this library was scraping our old form.

Can you guys help fix this?

**Comment by fogfish** [comment]
Thank you for reaching us! 
Do you have any suggestions how to fix an issue?

**Comment by jefmsmit** [comment]
We have reverted the changes for now and everything should be working again. We will figure out how to work with y'all prior to releasing it again. Thanks for understanding.

**Comment by btsteve** [comment]
I think they rolled back the change

**Comment by fogfish** [comment]
@jefmsmit Thank a lot for support! I can confirm that it works.

**Comment by srflaxu40** [comment]
Does anyone here know of an alternative for this?

https://github.com/Versent/saml2aws/issues/230

It appears that AWS STS endpoints only work with a registered MFA device's ARN which I don't believe JC supports.
