### ISSUE TITLE
Can't read AWS env vars after exec sub command

### ISSUE THREAD

**Issue by dfevre** [Versent/saml2aws#23]
The readme file says that the `exec` sub command exports the following environment variables -
* AWS_ACCESS_KEY_ID
* AWS_SECRET_ACCESS_KEY
* AWS_SESSION_TOKEN
* AWS_SECURITY_TOKEN
* EC2_SECURITY_TOKEN

I'm having trouble seeing them.
```
saml2aws exec --provider=Ping -- echo AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
```
returns
```
Running command as: arn:aws:sts::<blah>:assumed-role/admin/me
AWS_ACCESS_KEY_ID=
```

I was expecting to be able to see the value of the `AWS_ACCESS_KEY_ID` environment variable.

**Comment by wolfeidau** [comment]
@dfevre be careful that the shell doesn't replace `$AWS_ACCESS_KEY_ID` before it runs. 

You will need to use bash and a command string to stop that.

Any issues post here.

**Comment by dfevre** [comment]
Thanks @wolfeidau. I ended up escaping the `$` and it worked.
```
saml2aws exec --provider=Ping -- echo AWS_ACCESS_KEY_ID=\$AWS_ACCESS_KEY_ID
```
