### ISSUE TITLE
saml2aws login to work with updated JumpCloud login flow

### ISSUE THREAD

**Issue by jefmsmit** [Versent/saml2aws#230]
The week of October 8th, 2018 JumpCloud will update the login flow. This previously resulted in issue #224 

Please note that JumpCloud is not explicitly or implicitly supporting saml2aws. The following describes a way that this could work in the future. This too is subject to change.

1. GET Request to get XSRF token
- URL: https://console.jumpcloud.com/userconsole/xsrf
- Response body: {"xsrf": "<Some Long Token Here>"}
- The returned token needs to be used as the value for the `X-Xsrftoken` header on subsequent requests.

2. POST to auth endpoint
- URL: https://console.jumpcloud.com/userconsole/auth
- Headers: 
  - X-Xsrftoken: value is token from previous request
  - Accept: application/json
  - Content-Type: application/json
- Request Body: 
```
{
	"context": "sso",
	"redirectTo": "saml2/aws",
	"email": <user email> string required
	"password": <user password> string required
	"otp": <OTP for MFA> string only required if user has MFA
}
```
`context` and `redirectTo` are required to be the values above.

- If MFA required for user and OTP not provided
  - status code = 401
  - response body : `{"message": "MFA required."}`
- Successful auth
  - status code = 200
  - response body: `{"redirectTo": "https://sso.jumpcloud.com/saml2/aws"}`

3. GET request to `redirectTo` url in auth response to get SAMLResponse

**Comment by jefmsmit** [comment]
These changes can be implemented prior to our release the week of 10/8/2018.

**Comment by srflaxu40** [comment]
@jefmsmit how will users that use jumpcloud retrieve temporary AWS STS tokens without saml2aws for command line use?  Is there an alternative even if with the aws sdk?  From researching it appears the AWS SDK route requires individual MFA protected access for users.

**Comment by jefmsmit** [comment]
@srflaxu40 I am unclear on other options here. I assume someone could implement functionality similar to `saml2aws`. Alternatively, the `saml2aws` community should be able to implement the changes with the steps outlined above.

**Comment by srflaxu40** [comment]
@jefmsmit https://console.jumpcloud.com/userconsole/auth seems to return 404 even when posting on the command-line with the describe headers.  Any advice?

**Comment by jefmsmit** [comment]
Interesting. I can imagine using a GET instead of a POST could cause that, but you said you're POSTing. Can you share a redacted version of your POST body?

**Comment by srflaxu40** [comment]
@jefmsmit - values is the body in my post below:

```
values = { 
                "context": "sso",
                "redirectTo": "saml2/auth",
                "email": email,
                "password": password,
                "otp": mfa 
             }   

    headers = {'X-Xsrftoken': xsrfToken, 'Accept': 'application/json', 'Content-Type': 'application/json'}

    r = requests.post("https://console.jumpcloud.com/userconsole/auth", headers=headers, data=values, allow_redirects=True)
```

**Comment by jefmsmit** [comment]
Have you tried doing this with Postman instead of curl? Postman will handle cookies while curl makes that more difficult. 

Also, the email address and password must be for a user in JumpCloud and that user needs to be in a user group with the aws application: https://jumpcloud.desk.com/customer/en/portal/articles/2775691#authorize

**Comment by srflaxu40** [comment]
Yeah, same response (403/404) - I use a test user that exists in JC and they have all the groups.

**Comment by srflaxu40** [comment]
@jefmsmit can you send an example of this working?

One of the first things I did was try this in postman...  It seems like the endpoint is not valid for userconsole/auth..

![screen shot 2018-10-05 at 10 36 40 am](https://user-images.githubusercontent.com/3523153/46550726-b99e4700-c88a-11e8-8489-c7ab9b965582.png)
![screen shot 2018-10-05 at 10 36 54 am](https://user-images.githubusercontent.com/3523153/46550727-ba36dd80-c88a-11e8-9d35-760142f9a829.png)

**Comment by jefmsmit** [comment]
Here are screen shots of both my body and headers. I got a 200 response with a "redirectTo" body.
<img width="1078" alt="screen shot 2018-10-05 at 12 34 54 pm" src="https://user-images.githubusercontent.com/5996/46553858-dd1dbd80-c89b-11e8-8a54-748d28c80747.png">
<img width="1078" alt="screen shot 2018-10-05 at 12 35 09 pm" src="https://user-images.githubusercontent.com/5996/46553866-df801780-c89b-11e8-831a-4f301d3a78dd.png">

**Comment by jefmsmit** [comment]
Also, our "redirectTo" fields are different in our request bodies.

**Comment by srflaxu40** [comment]
what should the `redirectTo` field be in the body?

**Comment by jefmsmit** [comment]
`saml2/aws`

**Comment by srflaxu40** [comment]
I get the same 403 with curl too:

```
#!/bin/bash


curl -X POST \
     -H "Accept: application/json" \
     -H "Content-Type: application/json" \
     -H "X-Xsrftoken: v7MYvEvEcg5EkgwBx2JR52tgCki2FFoP" \
     -w "%{http_code}" \
     --data '{"context": "sso", "redirectTo": "saml2/auth", "email": "redacted@gmail.com", "password": "redacted", "otp": "476595"}' \
     https://console.jumpcloud.com/userconsole/auth


echo $http_code

```

**Comment by jefmsmit** [comment]
Just curious what happens if you change the `"redirectTo" : "saml2/auth"` to `"redirectTo" : "saml2/aws"`

**Comment by srflaxu40** [comment]
Hey, also I noticed - the xsrf token I am returning from the page is always the same...

**Comment by srflaxu40** [comment]
latest with diff user also in all groups and mfa enabled:

```
 1 #!/bin/bash
  2 
  3 
  4 curl -X POST \
  5      -H "Accept: application/json" \
  6      -H "Content-Type: application/json" \
  7      -H "X-Xsrftoken: redacted" \
  8      -w "%{http_code}" \
  9      --data '{"context": "sso", "redirectTo": "saml2/aws", "email": "redacted", "password": "redacted", "otp": "247202"}' \
 10      https://console.jumpcloud.com/userconsole/auth
 11 
 12 
 13 echo $http_code

```

**Comment by srflaxu40** [comment]
@jefmsmit This particular route in the application is not blacklisted somehow per chance to public access for now?  Maybe til release?

**Comment by srflaxu40** [comment]
correct

**Comment by jefmsmit** [comment]
Just noticed that your OTP token is hard coded in your script. Any chance that expired?

**Comment by srflaxu40** [comment]
@jefmsmit i update it every time i run it with the new one

**Comment by srflaxu40** [comment]
i still get the 403/404 and same xsrf token without mfa enabled

**Comment by jefmsmit** [comment]
The OTP token will expire in about a minute. I believe the XSRF token will expire after about 15 minutes. 
Can you please try the following and let me know.

1) curl to the xsrf endpoint _with verbose_:
2) Get _BOTH_ cookies: `_jumpcloud_user_console_` and `_xsrf`
3) Set XSRF header with response
4) Make sure to substitute those values with the ones listed below. And do so within a minute for the OTP and 15 minutes for the XSRF.

```
curl -X POST \
>       -H "Accept: application/json" \
>       -H "Content-Type: application/json" \
>       -H "X-Xsrftoken: RdY0WCZcYqROoDYGfAJn4KCNwRWFjABn" \
>       --data '{"context": "sso", "redirectTo": "saml2/aws", "email": "user@email.com", "password": "redacted", "otp": "redacted"}' \
>       --cookie "_xsrf=UmRZMFdDWmNZcVJPb0RZR2ZBSm40S0NOd1JXRmpBQm4=|1539027308221537213|78969c692403f05b066b89e94d5a85161a638c3b" \
>       --cookie "_jumpcloud_user_console_=4bc12707984fdfd3e50f90a3a6905173" \
>      https://console.jumpcloud.com/userconsole/auth
```

Anything different?

**Comment by srflaxu40** [comment]
same 403:
```
  1 #!/bin/bash
  2 
  3 
  4 curl -X POST \
  5      -H "Accept: application/json" \
  6      -H "Content-Type: application/json" \
  7      -H "X-Xsrftoken: he2eHKKjjqR4DI3fiUe7x5ZlPimnMPl0" \
  8      -w "%{http_code}" \
  9      --data '{"context": "sso", "redirectTo": "saml2/aws", "email": "redacted", "password": "redacted", "otp": "044418"}' \
 10      --cookie "_jumpcloud_user_console_=e79fb208452d8e25653894df634ae6df" \
 11      --cookie "_xsrf=WGhxaW5DUzdGMnYxc1pNSmQ0dGFJNk10a0R4bXI0OFg=|1539034830141491402|6acfadb920ee653bff6eabdea27c476168a79d10" \
 12      https://console.jumpcloud.com/userconsole/auth
 13 
 14 
 15 echo $http_code

```

**Comment by jefmsmit** [comment]
I played with this quite a bit this morning to try and duplicate your findings. 
The way I could get a 403 would be if I messed up the value for the `_xsrf` cookie, or used a value for the cookie that I didn't get when I got the value for the `X-Xsrftoken` header. 
I think in general, it would be a good idea to pass along all cookies from the response from `https://console.jumpcloud.com/userconsole/xsrf` to all subsequent calls. That is much harder to do in `curl`.

**Comment by byKirby** [comment]
So this may be the issue as it was for us. Granted, we've got our own CLI tool for authenticating with JumpCloud in order to export IAM roles, but I suspect the issue may be related to the `redirectTo` portion of things. Depending on how you've configured your JumpCloud links, the actual `redirectTo` value may be different. 

For example I have 3 separate JumpCloud application links that correspond to a different role in 3 separate AWS accounts. The `redirectTo` value should match up with how the JumpCloud application link was configured originally. 
Connecting to our DEV account, the application is configured with this url: https://sso.jumpcloud.com/saml2/AWS-DEV-ACCOUNT

So the `redirectTo` url we use is `saml2/AWS-DEV-ACCOUNT`

**Comment by jefmsmit** [comment]
@srflaxu40 could the configuration mentioned by @byKirby be causing your 403?

**Comment by wolfeidau** [comment]
Great to see you got the root of the issue, I don't think any of the team at Versent has looked at this as we don't currently use Jumpcloud internally.

As always happy to accept a PR to fix it.

**Comment by srflaxu40** [comment]
@jefmsmit would you happen to know what would cause a:

```{"message":"invalid character 'o' looking for beginning of value"}```

400 response?

**Comment by srflaxu40** [comment]
I think the xsrf value needs encoding or escaping perhaps..

**Comment by srflaxu40** [comment]
actually, seeing this on any requests now? is there something up?

**Comment by jefmsmit** [comment]
@wolfeidau I think the steps outlined above are basically the pseudo code changes that could be used to create the PR.

**Comment by btsteve** [comment]
> Great to see you got the root of the issue, I don't think any of the team at Versent has looked at this as we don't currently use Jumpcloud internally.
> 
> As always happy to accept a PR to fix it.

I think we have it working but it only seems to compile if we place the updated file in the vendor's directory.  This does not seem like the correct place to put it expscially since it is in the gitignore file. 
Where is the correct place to put the updated justcloud.go file?

**Comment by rsottilaro** [comment]
> Great to see you got the root of the issue, I don't think any of the team at Versent has looked at this as we don't currently use Jumpcloud internally.
> 
> As always happy to accept a PR to fix it.

@wolfeidau PR's up from us, sorry about the extra commit/comment spam.

@jefmsmit Thanks for the steps outline, it was very helpful.

**Comment by wolfeidau** [comment]
I think we can call this closed now. :tada:

**Comment by srflaxu40** [comment]
has anyone attempted to auth after they rolled out the new portal just now?

am getting:

```
~/$ saml2aws login
Using IDP Account default to access JumpCloud https://sso.jumpcloud.com/saml2/aws-endpoint
To use saved password just hit enter.
? Username john.doe@redacted.com
? Password *************

Authenticating as john.doe@redacted.com ...
? MFA Token 266932
Response did not contain a valid SAML assertion
Please check your username and password is correct

```
