### ISSUE TITLE
support of pre-authentication (basic,ntlm,ff)

### ISSUE THREAD

**Issue by tbugfinder** [Versent/saml2aws#244]
If the website to the IdP requires authentication, saml2aws fails with error 401.

```
User-Agent: saml2aws/1.0 (linux amd64) Versent
Accept-Encoding: gzip


request for url: https://pingserver/idp/startSSO.ping?PartnerSpId=urn:amazon:awsntlmprotected failed status: 401 Unauthorized

```

**Comment by GitzDoUrden** [comment]
We are experiencing this same issue.

**Comment by Gearheads** [comment]
hello, I am new here, and I have a fix for the NTLM issue that I would like to contribute if that is ok?
