### ISSUE TITLE
SAML URLs messed up

### ISSUE THREAD

**Issue by alexander-zimmermann** [Versent/saml2aws#258]
Hi all,

I configured the SAML URL w/ "https://****/idp/startSSO.ping?PartnerSpId=urn:amazon:webservices", but saml2aws tries later on to connect with "https://***/idp/startSSO.ping?PartnerSpId=urn:amazon:webservices/idp/startSSO.ping?PartnerSpId=urn:amazon:webservices".
It seems that saml2aws messed up somehow the configured URLs.

```
***@***:~$ saml2aws login 
Using IDP Account default to access Ping https://***/idp/startSSO.ping?PartnerSpId=urn:amazon:webservices
To use saved password just hit enter.
? Username A43374
? Password ****************
 
Authenticating as A43374 ...
error authenticating to IdP: error following: request for url: https://***/idp/startSSO.ping?PartnerSpId=urn:amazon:webservices/idp/startSSO.ping?PartnerSpId=urn:amazon:webservices failed status: 500 Server Error
***@***:~$ 
```

**Comment by mwkaufman** [comment]
In your ~/.saml2aws your url should be https://*** and your aws_urn urn:amazon:webservices, it will construct the idp/startSSO.ping part and append it to the URL base for the Ping provider.

**Comment by ewitkop** [comment]
What is you are using the trial version. I don't see that I have a custom URL with the trial version.
