### ISSUE TITLE
[MacOS] saml2aws login with self signed cert fails with x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by TheKangaroo** [Versent/saml2aws#276]
I use an ADFS identity provider with a self signed cert.
Even though my Mac accepts the cert as valid (e.g. it is in my KeyChain and curl accepts the exact same cert as trusted) I get 
```
error authenticating to IdP: error retrieving form: Get https://<url to ...aspx?> loginToRp=urn:amazon:webservices: x509: certificate signed by unknown authority
```

Is there any way to tell saml2aws to check and trust certs from my keychain?

My versions are:
MacOS 10.14.2
saml2aws 2.13.0
(aws aws-cli/1.16.90 Python/3.7.2 Darwin/18.2.0 botocore/1.12.80) not related as far as I understand.

Thank you in advance :)

**Comment by micahlmartin** [comment]
Did you try the `--skip-verify` flag?

**Comment by TheKangaroo** [comment]
Sure, it workes with `--skip-verify` but it's more of a workaround since I have the matching ca cert on my local machine and could verify if the remote cert is valid.

**Comment by mapkon** [comment]
Go will not validate a self signed cert when using https. However, you can workaround it while using `tls.Dial`, since it is lower level. This is not something we intend to implement.
