### ISSUE TITLE
Pass role as CLI flag

### ISSUE THREAD

**Issue by sidewinder12s** [Versent/saml2aws#28]
Can we add a flag that allows a user to pass in the role they want to assume?

**Comment by wolfeidau** [comment]
Great suggestion, a collegue also has a version which takes the username and pass as flags, i am looking to merge in some of that work. This would be a great addition to that.

**Comment by sidewinder12s** [comment]
We had avoided doing a password flag as it could inadvertently expose a users password in logs.

**Comment by jghaines** [comment]
In addition to this, I'd like to be able to authenticate, assume a parent role and then assume a sub-role in a single command. Is this the same request?:

```
saml2aws
  -a <ADFS account>
  --iam-role-arn arn:aws:iam::123456789000:role/<parent role> 
  --assume-role-arn arn:aws:iam::123456789001:role/<child role> 
  exec -- aws sts get-caller-identity
```

**Comment by elmobp** [comment]
What I've done is save the creds to a file encrypted with gpg, password prompted not via a cli flag I'll publish it next week if anyone interested
