### ISSUE TITLE
Support storing credentials in OS password manager

### ISSUE THREAD

**Issue by sidewinder12s** [Versent/saml2aws#29]
Thoughts on implementing something like keyring from python for storing username/password so users can better automate the running of saml2aws?

I had found this package with a little bit of googling: https://github.com/tmc/keyring

**Comment by wolfeidau** [comment]
Great question, I am currently messing with adding support for https://github.com/docker/docker-credential-helpers either by bundling it, or incorporating some of it into saml2aws.
