### ISSUE TITLE
Okta Login Error:Response did not contain a valid SAML assertion

### ISSUE THREAD

**Issue by cjbischoff** [Versent/saml2aws#315]
- Performing Login using Okta as IDP
- Here is the config file
```
[default]
app_id               =
url                  = https://COMPANY.okta.com/
username             = EMAIL
provider             = Okta
mfa                  = Auto
skip_verify          = false
timeout              = 0
aws_urn              = urn:amazon:webservices
aws_session_duration = 3600
aws_profile          = AWSPROFILE
subdomain            =
```
- successfully authenicated via username + password and then selection of MFA using TOTP
- when I performed the access using the following command `DUMP_CONTENT=true saml2aws login --verbose -a PROFILE`
- the last seem like a dump of a website vs SAML assertion
- within Okta console I have a single AWS Application that when selected directs to AWS to select a role (I have 2x)

**Comment by cjbischoff** [comment]
- Would having the APP ID make a different?
- Does saml2aws not handle multiple roles per Okta Application tile?

**Comment by cjbischoff** [comment]
- Per the documentation - https://github.com/Versent/saml2aws/blob/f4fdebe3436b5f135a316e470376858a68c4de7a/pkg/provider/okta/README.md; I have added the AWS application URL and still receive the error `Response did not contain a valid SAML assertion
Please check your username and password is correct`
- .samlaws file
```
[PROFILE]
app_id               = https://COMPANY.okta.com/home/amazon_aws/0oa1fgh7n922bIlY51d8/272
url                  = https://COMPANY.okta.com/
username             = EMAIL
provider             = Okta
mfa                  = Auto
skip_verify          = false
timeout              = 0
aws_urn              = urn:amazon:webservices
aws_session_duration = 3600
aws_profile          = PROFILE
subdomain            =
```

**Comment by georgeliaw** [comment]
@cjbischoff I believe you want to set
```url = https://COMPANY.okta.com/home/amazon_aws/0oa1fgh7n922bIlY51d8/272```
rather than `app_id`

**Comment by cjbischoff** [comment]
@georgeliaw  Thank that worked
