### ISSUE TITLE
Add logout

### ISSUE THREAD

**Issue by artkrz** [Versent/saml2aws#318]
Once login is successful and the role is chosen it can't be switched until credentials expire or are removed from the credentials file.

```
$ saml2aws login --skip-prompt
credentials are not expired skipping
```

It would be useful to have the ability to issue `logout` or `switch-role` commands.

**Comment by apicht** [comment]
I use `--force` with great success. That said, it would be very nice not to have to enter credentials again with an unexpired session.

**Comment by wolfeidau** [comment]
This is a great suggestion.

**Comment by hazeem-salim** [comment]
+1

**Comment by zacyang** [comment]
you could do ```saml2aws login --force``` to achieve the same goal

**Comment by zbentley** [comment]
For role-switching, `login --force` is a sufficient workaround. However, sometimes I really do want to log out, not switch. For example, when I'm testing code that talks to AWS, sometimes I want to test that it emits the correct error message when it can't authenticate.

**Comment by jsantos93** [comment]
Thanks you guys!!! The `--force` works just fine

**Comment by andris-cakuls** [comment]
> For role-switching, `login --force` is a sufficient workaround. However, sometimes I really do want to log out, not switch. For example, when I'm testing code that talks to AWS, sometimes I want to test that it emits the correct error message when it can't authenticate.

`saml2aws` by default stores the credentials in standard awscli location, usually `~/.aws/credentials`. You can delete that file to "log out".
