### ISSUE TITLE
Write diagnostic output to stderr

### ISSUE THREAD

**Issue by jghaines** [Versent/saml2aws#32]
Prompts and auth details should be written to stdout.

This is especially important when using the `exec` variant as I want to pipe the output of the subcommand ignoring the saml2aws output.

**Comment by wolfeidau** [comment]
Yes I need to tidy this up, I am just adding keychain support to save creds so I can sort this out.

**Comment by wolfeidau** [comment]
Discovered the other day that this cause issues on windows, I will need to write a simple writer which on *nix stderr, on windows stdout.

Still searching around for existing precedence.

**Comment by wolfeidau** [comment]
I have added a new --debug logger function which writes to stderr. 

Need to test this on windows in powershell cc @davidobrien1985

**Comment by d3v1an7** [comment]
Hey @wolfeidau! Am putting together a wrapper for a bunch of tools, and on non zero exit status I return stderr as a hint for the user. Problem is, looks like all output (including errors) for `saml2aws` seems to still be going to stdout...

<img width="606" alt="Screen Shot 2019-09-22 at 10 42 10 am" src="https://user-images.githubusercontent.com/4087799/65380777-f24a6100-dd25-11e9-93d9-8a1cafe9c0a3.png">

Tried adding `--debug`, but looks like that has been removed. Any plans to revisit this one?

**Comment by MichaelMallett** [comment]
Hi @wolfeidau I'm also keen for this, I can't see any mention of a --debug flag, and I can't seem to find anything in the commit history for one either?

**Comment by valtaz** [comment]
there is a --verbose flag for "Enable verbose logging"

**Comment by MichaelMallett** [comment]
Hi @valtaz, I can see the verbose flag, however from my testing it seems errors are still written to stdOut instead of stdErr, which is my issue.
