### ISSUE TITLE
Cant use saml2aws login ends up with Authentication failure

### ISSUE THREAD

**Issue by bharathkumar33** [Versent/saml2aws#320]
Hi Team

I am not able to use saml2aws on windows. while running saml2aws login I get below error message. It would be great if someone can help.

PS C:\temp> .\saml2aws.exe login
Using IDP Account default to access ADFS https://siteurl/
To use saved password just hit enter.
? Username first.last@domain.com.au
? Password **********
Authenticating as first.last@domain.com.au ...
error authenticating to IdP: error retrieving login response body: http: read on closed response body

**Comment by shyam** [comment]
I'm also facing the same issue. On OSX.?

**Comment by shyam** [comment]
This issue is fixed on the latest versions (Verified with 2.16.0).

**Comment by omgaz** [comment]
I'm seeing this on 2.22.1. I can authenticate via browser but not via CLI.

**Comment by wolfeidau** [comment]
Have you tried taking a look at the output we are scraping? This is how https://github.com/Versent/saml2aws#debugging-issues-with-idps 

Cheers

**Comment by omgaz** [comment]
Thanks @wolfeidau (next time rtfm, doh), that lead me to be able to debug. Managed to resolve:

Interestingly enough, `username={my email address}` doesn't work, neither does `username={my user id}`. However `username={domain}\{my user id}` works - which I don't need when I connect through the browser.

**Comment by ameza** [comment]
For anyone having this in 2024 make sure the 2FA being used matches the same configured in saml2aws as it won't work when 2FA codes from another password manager are used. If the command doesn't ask for the codes delete passwords stored in the apple keychain.

**Comment by mapkon** [comment]
Closing as there is a workaround
