### ISSUE TITLE
Running saml2aws against sudo freezes it

### ISSUE THREAD

**Issue by moritzheiber** [Versent/saml2aws#326]
I think somewhere between 2.14.0 and 2.15.0 (likely in either d0a1f1b3a79cdbfe21f8214fd3b914a515d4f242 or c8783c6716438aece9511ae91e22d1ce1f6a6e2e) `saml2aws` stopped working with `sudo`.

Steps to reproduce:

With `<= 2.14.0`:
```sh
$ sudo saml2aws --version
2.14.0
```

With `>=2.15.0`:
```sh
$ sudo saml2aws --version
[hangs until CTRL-C'd]
```
I think the process is getting confused about where to connect to for the Keyring service .. ? I'm not entirely sure though and I haven't had the time to trace the issue. Might be worth looking into though.

I'm running on Ubuntu Linux 18.04.2 LTS.

**Comment by iciclespider** [comment]
This is due to this PR: https://github.com/Versent/saml2aws/pull/272
