### ISSUE TITLE
Longer/configurable timeout

### ISSUE THREAD

**Issue by jghaines** [Versent/saml2aws#33]
When we enable (out-of-band) MFA on our ADFS, saml2aws times out before we can accept the MFA request

**Comment by ekiczek** [comment]
+1

**Comment by wolfeidau** [comment]
The timeouts are as follows, I think the one your tripping is ` IdleConnTimeout:       90 * time.Second,` does this sound correct? Or is it failing faster than that?

```
var DefaultTransport RoundTripper = &Transport{
        Proxy: ProxyFromEnvironment,
        DialContext: (&net.Dialer{
                Timeout:   30 * time.Second,
                KeepAlive: 30 * time.Second,
                DualStack: true,
        }).DialContext,
        MaxIdleConns:          100,
        IdleConnTimeout:       90 * time.Second,
        TLSHandshakeTimeout:   10 * time.Second,
        ExpectContinueTimeout: 1 * time.Second,
}
```

**Comment by mapkon** [comment]
@jghaines Is this an issue that is still occurring? I intend to close the ticket for house keeping purposes if there is no meaningful traction on it

**Comment by mapkon** [comment]
Closing this as there has been no traction.
