### ISSUE TITLE
Ability to run `saml2aws exec` against a specific AWS Profile

### ISSUE THREAD

**Issue by 85matthew** [Versent/saml2aws#335]
As a user I need to be able to utilize my local ~/.aws/config file in order to access various AWS accounts.

saml2aws currently does not appear to support this functionality. It will only allow you to pass a `profile` tag which needs to match the name of the profile name specified when running `saml2aws login`. (Without specifying, "SAML" is the default profile where the temporary credentials are stored)

After obtaining an initial temporary set of credentials to access a "hub" AWS account, (via `saml2aws login) I need the ability to assume-role into other "spoke" AWS accounts that are connected to my hub account.

Proposing a new flag in order to avoid breaking any existing functionality. Can utilize a flag called '--exec-profile'

**Comment by 85matthew** [comment]
I have a proposed PR to achieve this functionality. I would be glad to open a PR and get feedback.

I did see a couple other open issues that may be related but I was not confident based on the descriptions.

**Comment by wolfeidau** [comment]
Fixed by #336
