### ISSUE TITLE
Works only with sudo

### ISSUE THREAD

**Issue by MiyamotoAkira** [Versent/saml2aws#339]
I do not know if that is the expected behaviour (couldn't see a mention on the README file) but on Fedora 30, I can only use saml2aws (version 2.16.0) if I use sudo. Without sudo it hangs (both the release and building it myself using go)

**Comment by sidewinder12s** [comment]
Possibly the password manager integration?

**Comment by exolab** [comment]
> Possibly the password manager integration?

What do you mean by that?
