### ISSUE TITLE
fails to `go get`

### ISSUE THREAD

**Issue by tkinz27** [Versent/saml2aws#349]
Trying to install with `go get` (go 1.13 with module mode on) and getting

```
❯ go get github.com/versent/saml2aws@v2.16.0
go: finding github.com v2.16.0
go: finding github.com/versent/saml2aws v2.16.0
go: finding github.com/versent v2.16.0
go: finding github.com/robertkrimen/otto latest
go: finding github.com/Azure/go-ntlmssp latest
go: finding golang.org/x/net latest
go: github.com/versent/saml2aws imports
        github.com/versent/saml2aws/pkg/prompter imports
        github.com/AlecAivazis/survey: github.com/AlecAivazis/survey@v1.8.7: parsing go.mod:
        module declares its path as: gopkg.in/AlecAivazis/survey.v1
                but was required as: github.com/AlecAivazis/survey
```

Same issue with using `go get github.com/bersent/saml2aws@latest`

**Comment by tkinz27** [comment]
NOTE it builds just fine if I manually convert to go modules

`go mod init github.com/Versent/saml2aws`
`make install`

**Comment by tkinz27** [comment]
So I was about to make a pull request that switched the project over to go modules since I figured it would be easy, but looking at your Makefile, it looks like some bigger changes would be needed.

For instance, `gometalinter` is deprecated and not going to be updated to work with go modules.

If you are interested in being updated for go modules, I can make an attempt but wanted to check before I change up the Makefile a bunch. For instance I would switch out `gometalinter` for `golangci-lint`

**Comment by budougumi0617** [comment]
I created the pull request(https://github.com/Versent/saml2aws/pull/356) for this issue.

I agree to switch `gometalinter` to `golangci-lint`, but it pull request is minimal changes to resolve this issue.
