### ISSUE TITLE
saml2aws -i Ping does a segmentation violation and fails

### ISSUE THREAD

**Issue by pvangara** [Versent/saml2aws#35]
saml2aws  -p saml -i Ping login

Ping https://xxxx.xxxx.xx
Authenticating to Ping...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x13e46ea]

goroutine 1 [running]:
github.com/versent/saml2aws.(*PingFedClient).Authenticate(0xc42000e1d8, 0xc420146a20, 0xc42000e1d8, 0x0, 0x0, 0x1a)
	/Users/markw/Code/go/src/github.com/versent/saml2aws/pingfed.go:102 +0x4ca
github.com/versent/saml2aws/cmd/saml2aws/commands.Login(0x7fff5fbffc04, 0x4, 0x7fff5fbffc0c, 0x4, 0x14cd400, 0x5, 0x0)
	/Users/markw/Code/go/src/github.com/versent/saml2aws/cmd/saml2aws/commands/login.go:46 +0x398
main.main()
	/Users/markw/Code/go/src/github.com/versent/saml2aws/cmd/saml2aws/main.go:60 +0x29c

**Comment by wolfeidau** [comment]
Nice, can you tell me:

1. Which version of saml2aws your running?
2. Is your pingfed setup with MFA?

Cheers.

**Comment by pvangara** [comment]
Hi,
Thanks for looking into the issue:

Answer to your Q 1:
saml2aws --version
1.6.1
Answer to 2:
I can use pingfed via browser for AWS signing in - if that's what you are asking.

Thanks,
Ranga.

**Comment by pvangara** [comment]
go version
go version go1.8.3 darwin/amd64

**Comment by jason-riddle** [comment]
I ran into this as well.

Command:

```
saml2aws login --skip-verify --provider Ping
```

Stacktrace:

```
github.com/versent/saml2aws.(*PingFedClient).Authenticate
	/Users/markw/Code/go/src/github.com/versent/saml2aws/pingfed.go:63
github.com/versent/saml2aws/cmd/saml2aws/commands.Login
	/Users/markw/Code/go/src/github.com/versent/saml2aws/cmd/saml2aws/commands/login.go:65
main.main
	/Users/markw/Code/go/src/github.com/versent/saml2aws/cmd/saml2aws/main.go:73
runtime.main
	/usr/local/Cellar/go/1.8.1/libexec/src/runtime/proc.go:185
runtime.goexit
	/usr/local/Cellar/go/1.8.1/libexec/src/runtime/asm_amd64.s:2197
error authenticating to IdP
github.com/versent/saml2aws/cmd/saml2aws/commands.Login
	/Users/markw/Code/go/src/github.com/versent/saml2aws/cmd/saml2aws/commands/login.go:67
main.main
	/Users/markw/Code/go/src/github.com/versent/saml2aws/cmd/saml2aws/main.go:73
runtime.main
	/usr/local/Cellar/go/1.8.1/libexec/src/runtime/proc.go:185
runtime.goexit
	/usr/local/Cellar/go/1.8.1/libexec/src/runtime/asm_amd64.s:2197
```

Version:

```
saml2aws --version
Adding osx helper
1.8.1
```

**Comment by jason-riddle** [comment]
I could be wrong, but here's a guess at what's happening.

With curl, the following happens.

`curl --location --verbose 'https://<..snipped..>/idp/startSSO.ping?PartnerSpId=urn:amazon:webservices'`

```
* Connected to <snipped> (1.2.3.4) port 443 (#0)
> GET /idp/startSSO.ping?PartnerSpId=urn:amazon:webservices HTTP/1.1
<...>
< HTTP/1.1 302 Found
<...>
< Location: https://<...>/idp/XpBLj/resumeSAML20/idp/startSSO.ping
<...>
* Issue another request to this URL: 'https://<..>/idp/pe6CN/resumeSAML20/idp/startSSO.ping'
> GET /idp/pe6CN/resumeSAML20/idp/startSSO.ping HTTP/1.1
< HTTP/1.1 200 OK
```

However, even though the page returns an HTTP 200 OK, the html contains the following.

```
<!-- template name: state.not.found.error.page.template.html -->
```

So the 200 is misleading. What's weird is for our system you actually need to `get` the `/idp/startSSO.ping` once in order to get the `JSESSIONID` cookie, then make another `get` request to the same `/idp/startSSO.ping` with that cookie included then the request is successful, but as a caveat, we are using kerberos to authenticate.

**Comment by mapkon** [comment]
@jason-riddle Is this still occuring?

**Comment by mapkon** [comment]
Closing this due to lack of traction. Feel free3 to re-open if the issue reoccurs
