### ISSUE TITLE
Response did not contain a valid SAML assertion

### ISSUE THREAD

**Issue by devator-22** [Versent/saml2aws#358]
Getting this error when trying to connect to Okta. Has any run into this issue?

<img width="354" alt="Screen Shot 2019-10-09 at 2 49 48 PM" src="https://user-images.githubusercontent.com/54195350/66511036-323e7180-eaa4-11e9-8a92-05dbf5e40049.png">

**Comment by devator-22** [comment]
```
(base) user1-MBP:~ {hidden}$ saml2aws login --verbose
DEBU[0000] Running                                       command=login
DEBU[0000] check if Creds Exist                          command=login
DEBU[0000] Expand                                        name=/Users/user1/.aws/credentials pkg=awsconfig
DEBU[0000] resolveSymlink                                name=/Users/user1/.aws/credentials pkg=awsconfig
DEBU[0000] ensureConfigExists                            filename=/Users/user1/.aws/credentials pkg=awsconfig
Using IDP Account default to access Okta mycompany.com/
DEBU[0000] Get credentials                               helper=osxkeychain serverURL="mycompany.com/"
DEBU[0000] Get credentials                               helper=osxkeychain user={username}
To use saved password just hit enter.
? Username {hidden}
? Password {hidden}

DEBU[0022] building provider                             command=login idpAccount="account {\n  URL: mycompany.com/\n  Username: {username}\n  Provider: Okta\n  MFA: DUO\n  SkipVerify: false\n  AmazonWebservicesURN: urn:amazon:webservices\n  SessionDuration: 3600\n  Profile: sysops\n  RoleARN: \n}"
Authenticating as {username} ...
DEBU[0022] HTTP Req                                      URL="mycompany.com/api/v1/authn" http=client method=POST
DEBU[0024] HTTP Res                                      Status="200 OK" http=client
DEBU[0024] MFA                                           factorID=dsfcx5d3rrWatT0OQ356 mfaIdentifer="DUO WEB" oktaVerify="mycompany.com/api/v1/authn/factors/dsfcx5d3rrWatT0OQ356/verify" provider=okta
DEBU[0024] HTTP Req                                      URL="mycompany.com/api/v1/authn/factors/dsfcx5d3rrWatT0OQ356/verify" http=client method=POST
DEBU[0025] HTTP Res                                      Status="200 OK" http=client
DEBU[0025] HTTP Req                                      URL="https://api-0977de8f.duosecurity.com/frame/web/v1/auth?tx=TX%7CbWNhcnJpbGxvQGt5cnV1cy5jb218RElOWDdGNkgzTUVDVkpQTllDR1R8MTU3MDY0NzcxNg%3D%3D%7Ce214a05f597dc39d0e65832ea4e9d680a1c421f3" http=client method=POST
DEBU[0025] HTTP Res                                      Status="200 OK" http=client
? Select a DUO MFA Option Duo Push
DEBU[0062] HTTP Req                                      URL="https://api-0977de8f.duosecurity.com/frame/prompt" http=client method=POST
DEBU[0063] HTTP Res                                      Status="200 OK" http=client
DEBU[0063] HTTP Req                                      URL="mycompany.com/login/sessionCookieRedirect?checkAccountSetupComplete=true&redirectUrl=https%3A%2F%2Fkyruus.okta.com%2F&token=" http=client method=GET
DEBU[0063] HTTP Res                                      Status="200 OK" http=client
Response did not contain a valid SAML assertion
Please check your username and password is correct
(base) user1-MBP:~ user1$
 ```

Differently from #351 this is not using AzureAD

**Comment by dmmsonos** [comment]
If I remember correctly I ran into this when I was using the incorrect URL for the AWS Okta application. Might want to check that you're using the URL of the form:

`https://$YOUR_ORGANIZATION.okta.com/home/amazon_aws/$OKTA_APPLICATION_ID/$OKTA_OTHER_ID`

You should be able to grab a fully formed version of the URL from the "App Embed Link" pictured at the bottom of this image:

<img width="746" alt="Screen Shot 2019-10-09 at 3 56 19 PM" src="https://user-images.githubusercontent.com/43446033/66515700-94e83b00-eaad-11e9-8433-c21b4480f171.png">

**Comment by devator-22** [comment]
I entered the embedded link but I still got the same error

**Comment by devator-22** [comment]
I`m seeing some errors in DUO. Perhaps DUO is the culprit. 
<img width="1110" alt="Screen Shot 2019-10-09 at 4 44 22 PM" src="https://user-images.githubusercontent.com/54195350/66518897-3d010280-eab4-11e9-8430-510442d6a870.png">

**Comment by dmmsonos** [comment]
Ah, well, good luck! Sorry I can't be of more help. FWIW I am able to use Duo with Okta and saml2aws despite the docs suggesting it not possible when requiring MFA at the application level. Duo is implemented differently than other authenticators and does work.

**Comment by devator-22** [comment]
I appreciate your help. I will continue to troubleshoot this problem from the DUO side.

**Comment by devator-22** [comment]
It was duo policy restricting my login! It`s working now.

**Comment by borgstrom** [comment]
@devator-22 -- what part of the policy was restricting the login?  I have an issue with Duo where I can auth fine via a browser but when I try to use `saml2aws` I get the same error you get (`Response did not contain a valid SAML assertion`) and when I use `DUMP_CONTENT=true` all I see from the POST to the Duo api is:

```
{"message": "Authentication access denied.", "stat": "FAIL"}
```

**Comment by devator-22** [comment]
@borgstrom DUO policy could not recognize the OS from saml2aws so by default it was blocking it. I had to override that default behavior in the policy and it worked.

**Comment by noahlz** [comment]
> @borgstrom DUO policy could not recognize the OS from saml2aws so by default it was blocking it. I had to override that default behavior in the policy and it worked.

Can you please elaborate? I'm having the exact same issue. saml2aws is downloading html for my org's okta login page.  Can you please provide details or hints on where I can find documentation for "blocking OS that DUO did not recognize"?
