### ISSUE TITLE
Login Failure for Azure AD

### ISSUE THREAD

**Issue by jmoretti** [Versent/saml2aws#370]
Beginning this morning, the following command fails with the included error (personal info redacted) using saml2aws v2.18.0 on Mac and Linux:
`$ saml2aws login -a devops --verbose
DEBU[0000] Running                                       command=login
DEBU[0000] check if Creds Exist                          command=login
DEBU[0000] Expand                                        name=/home/user/.aws/credentials pkg=awsconfig
DEBU[0000] resolveSymlink                                name=/home/user/.aws/credentials pkg=awsconfig
DEBU[0000] ensureConfigExists                            filename=/home/user/.aws/credentials pkg=awsconfig
Using IDP Account devops to access AzureAD https://account.activedirectory.windowsazure.com
To use saved password just hit enter.
? Username username
? Password **********

DEBU[0008] building provider                             command=login idpAccount="account {\n  AppID: Appidguid\n  URL: https://account.activedirectory.windowsazure.com\n  Username: username\n  Provider: AzureAD\n  MFA: Auto\n  SkipVerify: false\n  AmazonWebservicesURN: urn:amazon:webservices\n  SessionDuration: 3600\n  Profile: devops\n  RoleARN: \n}"
Authenticating as username ...
DEBU[0008] HTTP Req                                      URL=/common/login http=client method=POST
Post /common/login: unsupported protocol scheme ""
error retrieving login results
github.com/versent/saml2aws/pkg/provider/aad.(*Client).Authenticate
        /Users/markw/go/src/github.com/versent/saml2aws/pkg/provider/aad/aad.go:675
github.com/versent/saml2aws/cmd/saml2aws/commands.Login
        /Users/markw/go/src/github.com/versent/saml2aws/cmd/saml2aws/commands/login.go:70
main.main
        /Users/markw/go/src/github.com/versent/saml2aws/cmd/saml2aws/main.go:139
runtime.main
        /usr/local/Cellar/go/1.13.3/libexec/src/runtime/proc.go:203
runtime.goexit
        /usr/local/Cellar/go/1.13.3/libexec/src/runtime/asm_amd64.s:1357
error authenticating to IdP
github.com/versent/saml2aws/cmd/saml2aws/commands.Login
        /Users/markw/go/src/github.com/versent/saml2aws/cmd/saml2aws/commands/login.go:72
main.main
        /Users/markw/go/src/github.com/versent/saml2aws/cmd/saml2aws/main.go:139
runtime.main
        /usr/local/Cellar/go/1.13.3/libexec/src/runtime/proc.go:203
runtime.goexit
        /usr/local/Cellar/go/1.13.3/libexec/src/runtime/asm_amd64.s:1357 `

**Comment by chrisbrownie** [comment]
I'm getting this too, confirmed across a couple of machines.

**Comment by jmoretti** [comment]
V2.19.0 resolved this issue. Thank you!

**Comment by adamist521** [comment]
still getting error with v2.23.0 ...
anything I could try?

```
$ saml2aws login --verbose
DEBU[0000] Running                                       command=login
DEBU[0000] check if Creds Exist                          command=login
DEBU[0000] Expand                                        name=/Users/01018554/.aws/credentials pkg=awsconfig
DEBU[0000] resolveSymlink                                name=/Users/01018554/.aws/credentials pkg=awsconfig
DEBU[0000] ensureConfigExists                            filename=/Users/01018554/.aws/credentials pkg=awsconfig
Using IDP Account default to access AzureAD https://account.activedirectory.windowsazure.com
DEBU[0000] Get credentials                               helper=osxkeychain serverURL="https://account.activedirectory.windowsazure.com"
DEBU[0000] Get credentials                               goMsg="The specified item could not be found in the keychain." helper=osxkeychain
To use saved password just hit enter.
? Username ***********@********
? Password ********

DEBU[0002] building provider                             command=login idpAccount="account {\n  AppID: **************** \n  URL: https://account.activedirectory.windowsazure.com\n  Username: ******@********\n  Provider: AzureAD\n  MFA: PhoneAppOTP\n  SkipVerify: false\n  AmazonWebservicesURN: urn:amazon:webservices\n  SessionDuration: 3600\n  Profile: saml\n  RoleARN: \n}"
Authenticating as ***********@********* ...
DEBU[0003] HTTP Req                                      URL="https://login.microsoftonline.com/common/login" http=client method=POST
DEBU[0004] HTTP Res                                      Status="200 OK" http=client
DEBU[0004] HTTP Req                                      URL="https://login.microsoftonline.com/kmsi" http=client method=POST
DEBU[0004] HTTP Res                                      Status="200 OK" http=client
DEBU[0004] HTTP Req                                      URL="https://account.activedirectory.windowsazure.com/" http=client method=POST
DEBU[0006] HTTP Res                                      Status="200 OK" http=client
DEBU[0006] HTTP Req                                      URL="https://login.microsoftonline.com/*******tenant_id*******/saml2?SAMLRequest=*********************************" http=client method=GET
DEBU[0006] HTTP Res                                      Status="200 OK" http=client
DEBU[0006] HTTP Req                                      URL= http=client method=post
post : unsupported protocol scheme ""
error reprocess results
github.com/versent/saml2aws/pkg/provider/aad.(*Client).reProcess
	/Users/markw/Code/notgopath/saml2aws/pkg/provider/aad/aad.go:1106
github.com/versent/saml2aws/pkg/provider/aad.(*Client).Authenticate
	/Users/markw/Code/notgopath/saml2aws/pkg/provider/aad/aad.go:1044
github.com/versent/saml2aws/cmd/saml2aws/commands.Login
	/Users/markw/Code/notgopath/saml2aws/cmd/saml2aws/commands/login.go:70
main.main
	/Users/markw/Code/notgopath/saml2aws/cmd/saml2aws/main.go:140
runtime.main
	/usr/local/Cellar/go/1.13.6/libexec/src/runtime/proc.go:203
runtime.goexit
	/usr/local/Cellar/go/1.13.6/libexec/src/runtime/asm_amd64.s:1357
failed to saml request reprocess
github.com/versent/saml2aws/pkg/provider/aad.(*Client).Authenticate
	/Users/markw/Code/notgopath/saml2aws/pkg/provider/aad/aad.go:1046
github.com/versent/saml2aws/cmd/saml2aws/commands.Login
	/Users/markw/Code/notgopath/saml2aws/cmd/saml2aws/commands/login.go:70
main.main
	/Users/markw/Code/notgopath/saml2aws/cmd/saml2aws/main.go:140
runtime.main
	/usr/local/Cellar/go/1.13.6/libexec/src/runtime/proc.go:203
runtime.goexit
	/usr/local/Cellar/go/1.13.6/libexec/src/runtime/asm_amd64.s:1357
error authenticating to IdP
github.com/versent/saml2aws/cmd/saml2aws/commands.Login
	/Users/markw/Code/notgopath/saml2aws/cmd/saml2aws/commands/login.go:72
main.main
	/Users/markw/Code/notgopath/saml2aws/cmd/saml2aws/main.go:140
runtime.main
	/usr/local/Cellar/go/1.13.6/libexec/src/runtime/proc.go:203
runtime.goexit
	/usr/local/Cellar/go/1.13.6/libexec/src/runtime/asm_amd64.s:1357
```

**Comment by sampritavh** [comment]
I faced same issue in the latest version of saml2aws. I tried it in both Ubuntu as well as windows 10 machine. I am using saml2aws version 2.27.1

**Comment by martinm82** [comment]
Same here with version 2.28.1 on macOS 10.14.6
