### ISSUE TITLE
CLI idp-provider flag doesn't support 'GoogleApps'

### ISSUE THREAD

**Issue by Lemmons** [Versent/saml2aws#373]
Reproduced by running `saml2aws configure --idp-provider=GoogleApps`.  This is a supported configuration, but is not supported on using the cli flags.

This can be seen to be not supported in the code here: https://github.com/Versent/saml2aws/blob/b45792557b64d1ab8b6d899bf3f5acbef9a4ddde/cmd/saml2aws/main.go#L56

**Comment by Apollorion** [comment]
Looking for this as well.
