### ISSUE TITLE
appveyor build broken

### ISSUE THREAD

**Issue by quintok** [Versent/saml2aws#374]
https://ci.appveyor.com/project/davidobrien1985/saml2aws/branch/master

ultimately this blocks the release to chocolatey

the first build that failed was the release of 2.18.0 - https://ci.appveyor.com/project/davidobrien1985/saml2aws/builds/28276858

As this is the case and it looks like a problem with dependencies I suspect it relates to the PR migrating to go modules - https://github.com/Versent/saml2aws/pull/347

My suspicion is that the appveyor build was not updated to use go modules which is causing the issue

**Comment by gliptak** [comment]
https://github.com/Versent/saml2aws/pull/432

**Comment by gliptak** [comment]
https://github.com/Versent/saml2aws/pull/437

**Comment by gliptak** [comment]
https://chocolatey.org/packages?q=saml2aws is current
