### ISSUE TITLE
How to change session duration from 1 hour to 8 hours

### ISSUE THREAD

**Issue by devator-22** [Versent/saml2aws#375]
My IAM role has CLI duration of 8 hours however when I login with `saml2aws` my session is still 1 hour. Is this a setting I can change in `saml2aws`?

Thanks for your help!

**Comment by tegamckinney** [comment]
I'm having the same issue when I use `saml2aws exec --exec-profile profileName`.

I believe there is a configuration that needs to be set to enable this from `<= v2.18.0`.

I believe 'AssumeRoleDuration` needs to be enabled [here](https://github.com/Versent/saml2aws/blob/master/cmd/saml2aws/commands/exec.go#L85-L89) .  I tried setting `duration_seconds` in my profile however it did not adhere to that.

**Comment by Apollorion** [comment]
`saml2aws configure --session-duration 2880` is what youre looking for.

**Comment by devator-22** [comment]
@Apollorion works like charm!

**Comment by thaifp** [comment]
Actually it should be 28800 (3600 * 8)

**Comment by ravi-cirium** [comment]
is it seconds, minutes, hours?

**Comment by ravi-cirium** [comment]
I figured it out. It's seconds.
