### ISSUE TITLE
AssumeRoleDuration for exec-profile sessions

### ISSUE THREAD

**Issue by tegamckinney** [Versent/saml2aws#378]
I'm having an issue when I use `saml2aws exec --exec-profile profileName` where the session times out after 15mins and the `--session-duration` flag does not seem to allow setting the AssumeRoleDuration.

I believe there is a configuration that needs to be set to enable this from `<= v2.18.0`.

I believe `AssumeRoleDuration` needs to be enabled [here](https://github.com/Versent/saml2aws/blob/master/cmd/saml2aws/commands/exec.go#L85-L89).  I tried setting `duration_seconds` in my profile however it did not adhere to that.

@85matthew or @elementalvoid - Am I overlooking anything regarding being able to set the assume role duration when using a profile?

_Originally posted by @tegamckinney in https://github.com/Versent/saml2aws/issues/375#issuecomment-554417851_

**Comment by 85matthew** [comment]
Hey @tegamckinney !

I've actually noticed this annoying quality the last few days myself. Didn't have time yet to dig into it and had assumed it might be my setup.

Looking at this now and will do some testing. Thanks for pinging me and reporting.

**Comment by wolfeidau** [comment]
fixed.

**Comment by 85matthew** [comment]
Thanks Mark!

**Comment by tegamckinney** [comment]
Thanks guys!
