### ISSUE TITLE
Add Duo support for JumpCloud

### ISSUE THREAD

**Issue by ahrenstein** [Versent/saml2aws#390]
JumpCloud has added Duo as an official MFA option. Would it be possible to get saml2aws to add support for JumpCloud+Duo?

Right now JumpCloud + TOTP works but if TOTP is disabled to enforce Duo security policies on user auth, users can no longer gain STS credentials for operating with the AWS API as saml2aws can no longer authenticate.

Thanks!

**Comment by sephynox** [comment]
Are there costs involved?

**Comment by ahrenstein** [comment]
#489 would resolve this

**Comment by logingood** [comment]
I updated some code from #489 in #626, and also added yubikey support via webauthn.

**Comment by ahrenstein** [comment]
Can we get #626 merged?

**Comment by ahrenstein** [comment]
Thanks for getting #626 merged!
