### ISSUE TITLE
Keychain issue in WSL2

### ISSUE THREAD

**Issue by hangjit-domain** [Versent/saml2aws#409]
When I run through the process of logging in, I encounter the following error.

`error storing password in keychain: No such interface 'org.freedesktop.DBus.Properties' on object at path /`

Here's the details of the OS:
```
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic
```

I'm running it on WSL2 on Windows 10. I had the same issue in WSL1.

Note: here's a help thread I created to see if the bug was related to Ubuntu https://askubuntu.com/questions/1161160/error-storing-password-in-keychain-no-such-interface-org-freedesktop-dbus-prop?noredirect=1#comment2020822_1161160

**Comment by wolfeidau** [comment]
Can you try with the `--disable-keychain` to turn off keychain integration.

**Comment by hrai-domain** [comment]
I get 401 now.

```
Authenticating as some@email.com ...
error authenticating to IdP: error retrieving auth response: request for url: https://blah.okta.com/api/v1/authn failed status: 401 Unauthorized
```

Also, when I type in `saml2aws login` it takes between 30 to 60 seconds to prompt me for username/password.

**Comment by kbergha** [comment]
A few newer issues (#561 and #563) also mentiones/dupes this problem.  

Regarding `--disable-keychain`; this works fine for me. 
I'm on WSL2 with Ubuntu 20.04, with saml2aws version 2.27.1

And I do not get @hangjit-domain's problem with 401 or long delay, but I'm connecting with KeyCloak, not Okta. 

I understand that this is not a problem with saml2aws itself, but ofcourse it would be nice to not have to enter my password every time.

So if anyone finds a way, please do share! 😃

**Comment by mapkon** [comment]
Closing as there is a workaround
