### ISSUE TITLE
Incorrect $Home path being used to store credentials

### ISSUE THREAD

**Issue by rohanpower** [Versent/saml2aws#411]
Just rebuilt my Windows machine and installed version v2.21.1 into the C:\Windows\System32 folder.

When I run up CYGWIN and run the 'saml2aws login' command, I notice that the .aws/credentials file is being created in my Windows HOMEPATH folder (e.g. C:\Users\%username%), and not in the CYGWIN home (/home/%username%).

Note: However v2.13.0 works as expected.

**Comment by valtaz** [comment]
👋 I just check the upstream lib which we use to get the homedir (mitchellh/go-homedir), nothing change for past couple of years.

Can you confirm how did you install the new and the old version?

**Comment by rohanpower** [comment]
👋👋 Grabbed the latest binary from the releases page, and dropped the executable into the System32 folder.  Did the same for both old and new versions.

**Comment by valtaz** [comment]
can you check USERPROFILE from your CYGWIN terminal? You might want to change this to match up with your CYGWIN home.

There was a change over a year back which get the right profile for the windows user. In your case, it still detect as windows platform even in the CYGWIN environment. (https://github.com/Versent/saml2aws/commit/daa48db80e7ef98c70fda74ee707ab9c346649df)

**Comment by rohanpower** [comment]
Yep, looks like the CYGWIN environment imports the USERPROFILE from the Windows machine - 
https://www.cygwin.com/cygwin-ug-net/setup-env.html
