### ISSUE TITLE
Incorrect use of gomodules

### ISSUE THREAD

**Issue by worr** [Versent/saml2aws#417]
Hey!

Unfortunately, it seems like using parts of this project are broken since the move to gomodules. When trying to update, I get:

```
18:23:20|1$ go get github.com/Versent/saml2aws@v2.22.0
go: finding github.com v2.22.0
go: finding github.com/Versent/saml2aws v2.22.0
go: finding github.com/Versent v2.22.0
go: finding github.com/Versent/saml2aws v2.22.0
go get github.com/Versent/saml2aws@v2.22.0: github.com/Versent/saml2aws@v2.22.0: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2
```

It appears that when the migration happened, the import paths weren't changed to reflect the v2 version. There's a section here that describes the issues I'm running into: https://github.com/golang/go/wiki/Modules#semantic-import-versioning

If y'all are open to a PR for it, I'm happy to make one to fix this issue. It will be a large and intrusive PR though, so I didn't want to jump in and open it without creating an issue first though.

Thanks!

**Comment by anoop2811** [comment]
It would be great if a v2 of the module was available. My use case would be to utilize this as a dependency in my own cli that I intend to write. Is this something the maintainers are planning to do soon? I would prefer not to fork, if the value can be built into the original repo. I understand this use case was probably not in consideration when building a cli.

**Comment by richardcase** [comment]
@worr - i'd also love for the v2 module to be available. Like @anoop2811 i want to use saml2aws as a package as well.

**Comment by richardcase** [comment]
This is a blocker for our usage of this. Would really love to see @worr changes incorporated into this.

**Comment by worr** [comment]
As a workaround until upstream resolves this issue, we forked the repo, and used a `replace` of this repo:

```
replace github.com/versent/saml2aws => xxx/saml2aws v1.8.5-0.20200716181822-644574e210af
```

Replace `xxx` with your own fork if you choose to go this route.

**Comment by richardcase** [comment]
Thanks @worr - i'll try that

**Comment by wolfeidau** [comment]
@worr @richardcase I really want to merge this just trying to clear out some PRs as it will break them all.

TBH I only recently figured out how this works myself, like most people I was pretty surprised by the changes required.

**Comment by wolfeidau** [comment]
You can now `go get -u -v github.com/versent/saml2aws` I have tested this in a new project with go 1.15.

Any issues ping me.

Cheers
