### ISSUE TITLE
Unable to configure saml2aws profile

### ISSUE THREAD

**Issue by srigumm** [Versent/saml2aws#418]
I am seeing this issue in my machine, I installed it through choco in my windows box.. looks like its a hidden bug triggered thorugh something. Fixing this issue could help someone.
![image](https://user-images.githubusercontent.com/44202047/73547426-e9bd1200-440c-11ea-8424-90f2a7c3b9f9.png)

**Comment by gliptak** [comment]
do you have an ```H:``` drive?

**Comment by srigumm** [comment]
I dont have H: drive actually.. anyways I switched to different desktop and its working without any issues.
