### ISSUE TITLE
Support hardware yubikey for okta provider with MFA

### ISSUE THREAD

**Issue by Richard-outreach** [Versent/saml2aws#419]
Just tried using this for okta based login with a yubkey for MFA and got a `unsupported mfa provider` response. Is it possible to support `mfaIdentifer="YUBICO TOKEN:HARDWARE"` by chance?

**Comment by wolfeidau** [comment]
To be honest I haven't tried using a yubikey with okta, there has been some work done in the google provider to support this device https://github.com/Versent/saml2aws/pull/398. 

Once that settles in I was planning to see if i could reuse it on other providers or come up with some common construct for these types of devices.

Cheers.

**Comment by Richard-outreach** [comment]
Solid. Sounds good. Happy to test anything out that we can get rolling.

**Comment by spoonerd** [comment]
+1 to this as we are running into the same issue as we use Yubikeys. Happy to do any testing required.

**Comment by dishbreak** [comment]
I've got an engineer with a Yubikey as well. Haven't contributed yet, but I'm sure I'd be able to help get testing done.

**Comment by edyesed** [comment]
I believe I solved this with #456

**Comment by rsclarke-vgw** [comment]
Using Yubikey 5c with Okta + MFA setting `mfa = FIDO` in `~/.saml2aws` configuration has been working for me.

**Comment by ylorenzati** [comment]
hello, just to let you know. It works very well on my MacBook.
But my coworkers are unable to make it work on Linux (specifically ArchLinux).

**Comment by mattzuba** [comment]
@ylorenzati, I ran into this same issue with Linux, appears to be an upstream limitation: marshallbrekka/go-u2fhost#1

**Comment by edyesed** [comment]
i don't have a linux machine with which to test/bring a different implementation.

**Comment by kunickiaj** [comment]
Using Okta with Webauthn (FIDO) and Yubikeys. Tried but get this error:

```
error authenticating to IdP: error verifying MFA: The provided key handle is not present on the device, or was created with a different application parameter.
```

I am wondering if this is because there is a FIDO PIN set on the key. I am wondering if something needs to be added to this tool similar to how it was necessary in `gimme-aws-creds` (https://github.com/Nike-Inc/gimme-aws-creds/pull/243)

**Comment by edyesed** [comment]
yeah, what `gimmie-aws-creds` is doing with the yubikey and what this PR is doing with the yubikey are quite different. Part of the difficulty with accommodating these devices are the many variants and configurations they can be put into. 

I do not have a yubikey with this config with which I could test/debug how to implement that operation.

**Comment by kunickiaj** [comment]
Yeah I'm realizing this issue may be for the "other" Yubikey integration. FIDO support should be generic for any FIDO2 capable keys. I have some extra keys without a PIN set and will try to confirm whether PIN is the issue here and open a separate issue to track that if its the case -- and hopefully work out a PR for it if that is the issue I'm hitting.

**Comment by ocraviotto** [comment]
Created a PR that should fix U2F/WebAuthn keys USB detection in Linux (#592).
@wolfeidau Not sure what's the regular process for PR review, so let me know how I should proceed.

**Comment by bstein-lattice** [comment]
> Yeah I'm realizing this issue may be for the "other" Yubikey integration. FIDO support should be generic for any FIDO2 capable keys. I have some extra keys without a PIN set and will try to confirm whether PIN is the issue here and open a separate issue to track that if its the case -- and hopefully work out a PR for it if that is the issue I'm hitting.

Was a separate issue ever created for the yubikey PIN? 
I'm running into an issue with Okta where their end us configured to ask for a PIN -based token, but saml2aws doesn't ask for it. I can't tell if it's a problem on Okta's side not specifying in the initial request that it's expecting a PIN, or if saml2aws just doesn't check.
The end result is that I get a `verify failed status: 400 Bad Request` and then a segfault on 
pkg/provider/http.go:168

Any suggestions on how to determine which end is doing the wrong thing, or a ticket I can follow along with?

**Comment by mapkon** [comment]
> > Yeah I'm realizing this issue may be for the "other" Yubikey integration. FIDO support should be generic for any FIDO2 capable keys. I have some extra keys without a PIN set and will try to confirm whether PIN is the issue here and open a separate issue to track that if its the case -- and hopefully work out a PR for it if that is the issue I'm hitting.
> 
> Was a separate issue ever created for the yubikey PIN? I'm running into an issue with Okta where their end us configured to ask for a PIN -based token, but saml2aws doesn't ask for it. I can't tell if it's a problem on Okta's side not specifying in the initial request that it's expecting a PIN, or if saml2aws just doesn't check. The end result is that I get a `verify failed status: 400 Bad Request` and then a segfault on pkg/provider/http.go:168
> 
> Any suggestions on how to determine which end is doing the wrong thing, or a ticket I can follow along with?

I don't think there is another issue to handle this. Feel free to create a new issue.

**Comment by cdoughty-r7** [comment]
> > Yeah I'm realizing this issue may be for the "other" Yubikey integration. FIDO support should be generic for any FIDO2 capable keys. I have some extra keys without a PIN set and will try to confirm whether PIN is the issue here and open a separate issue to track that if its the case -- and hopefully work out a PR for it if that is the issue I'm hitting.
> 
> Was a separate issue ever created for the yubikey PIN? I'm running into an issue with Okta where their end us configured to ask for a PIN -based token, but saml2aws doesn't ask for it. I can't tell if it's a problem on Okta's side not specifying in the initial request that it's expecting a PIN, or if saml2aws just doesn't check. The end result is that I get a `verify failed status: 400 Bad Request` and then a segfault on pkg/provider/http.go:168
> 
> Any suggestions on how to determine which end is doing the wrong thing, or a ticket I can follow along with?

Did you ever find a work around?  I have made this work by selecting "Browser" type and using `--download-browser-driver` however this is less than ideal as it downloads an entire browser just to handle prompting for user/pass/pin.  I'd love to find out how to configure saml2aws to work with FIDO2/yubikey and pin entirely from command line.

**Comment by bstein-lattice** [comment]
Unfortunately not. I never got around to making a ticket (I probably should have) because after fighting with Okta about it for six months I was never even clear where the issue was coming from, or if trying to do something in saml2aws would happen or move the needle.

But I'm happy to help provide additional information or experimentation as helpful.
I just gave `--download-browser-drive` and it does seem to work for me - I bet you could get some improvements by providing a specific browser path and autofill (though the latter didn't work for me when I just tried it), but I'd love to be able to set all of that in the .saml2aws config. It may need some more experimentation.

But I agree that something entirely from the command line would be ideal.
