### ISSUE TITLE
Selecting the first role does not work

### ISSUE THREAD

**Issue by hoegertn** [Versent/saml2aws#421]
If you login to AWS and have the permission to assume multiple roles, these are presented in a list titled `? Please choose the role`.

If you want to select the first one and just press return, this does not work any longer. Clicking the arrow keys down and up to select the first works perfectly.

So it seems that the internal state is not properly initialized.

This happens on 1.22.0 and 1.22.1

**Comment by moritzheiber** [comment]
This also happens on 2.23.0.

**Comment by georgeliaw** [comment]
This appears to be broken as of 2.21.1 (2.21.0 is fine).
