### ISSUE TITLE
Response did not contain a valid SAML assertion.Please check your username and password is correct

### ISSUE THREAD

**Issue by Ankitchandre** [Versent/saml2aws#423]
I have download saml2aws using choco. version is 2.17
I have configured okta on company id. aws is integrated as well in okta . 
I use saml2aws and configure with:
Please choose a provider: Okta
Please choose an MFA : OKTA
AWS Profile : abcd
URL : https://myid..../app/amazon_aws/bbiojonoahcouwhcow/sso/saml
Username abcde
Password **
Confirm **

i do a saml2aws login 
provide username and password
> get following error : 
Response did not contain a valid SAML assertion.Please check your username and password is correct

**Comment by spoonerd** [comment]
I had the same problem. Choco not using latest version with bug fixes.

Grab it here and try again.

https://github.com/Versent/saml2aws/releases/tag/v2.22.1

**Comment by Ankitchandre** [comment]
you are absolutely right. I forgot to update on this , but i also downloaded latest version and the saml assertion worked fine . 
Thanks
Ankit
