### ISSUE TITLE
Choco is out of date

### ISSUE THREAD

**Issue by spoonerd** [Versent/saml2aws#426]
Hi

Just started to use SAML2AWS this morning. The Choco version is 2.17.0 (3 Oct 2019) where as the latest version is 2.22.1 (Feb 2020) and I ran into this bug https://github.com/Versent/saml2aws/issues/118#issuecomment-546954093 which cost me a few hours of frustration before I realised what was going on.

Can the packages be updated please to prevent other users repeating what I experienced.

Thanks.

**Comment by duoshiro** [comment]
I'm having the same issue as well, could you please update de packages please?

**Comment by gliptak** [comment]
https://github.com/Versent/saml2aws/pull/432

**Comment by cheinema** [comment]
Any progress here? I currently have to use a manually installed up-to-date version.

**Comment by wolfeidau** [comment]
Now updated to the latest version.
