### ISSUE TITLE
Symantec VIP support: error authenticating to IdP, unable to classify response from auth server

### ISSUE THREAD

**Issue by RachelleJanssen** [Versent/saml2aws#439]
We migrated from the development ADFS server to the production ADFS server to get into AWS (in theory, only needed to remove the "-stage" in the URL). In chrome everything works fine and I'm able to login with my credentials, but saml2aws had some issues.

At first it simply said "Response did not contain a valid SAML assertion". I read that upgrading to the latest version might help. Now I'm getting "error authenticating to IdP: unable to classify response from auth server".

Any idea if I misconfigured something from the ADFS server?

**Comment by wolfeidau** [comment]
Take a look at https://github.com/Versent/saml2aws#debugging-issues-with-idps and see what is in the HTML output.

That should help you debug the issue!

**Comment by RachelleJanssen** [comment]
I was running in verbose mode for several hours but I was so frustrated that I must have looked passed the output.

I think I found the issue. Our company uses Symantec VIP for MFA. I can see the "welcome rachelle, we need additional information" bla bla bla in the HTML body.
Normally, this will start a loading animation until it either uses an existing token, sends a push notification to my phone or, when the push notification expires, asks for an authenticator code. saml2aws, however, doesn't recognize this in-between screen and goes for an early exit, stating that there was no valid SAML response.

It's strange how our dev ADFS didn't have this issue, but we have to move to the production server. I really like the simplicity of saml2aws, but until this is fixed somehow, it seems our saml2aws adventure ends here.

**Comment by RachelleJanssen** [comment]
hmm on second throught, maybe it's better to leave this issue open?

**Comment by JoaoVM** [comment]
Hi @RachelleJanssen, have you tried an older version of the saml2aws?
I had the same problem as you and I tried the version 2.7.0, it's worked with me.
I hope I could help.
