### ISSUE TITLE
GoogleApps: unsupported protocol scheme

### ISSUE THREAD

**Issue by Apollorion** [Versent/saml2aws#444]
Hello,

We use saml2aws on a daily basis and have suddenly started running into this error when logging in (about 1 in every 5 logins):
```Post ?hl=en&loc=US: unsupported protocol scheme ""```

After running in debug mode it looks like the `passwordURL` variable in the below url is intermittently not being set: https://github.com/Versent/saml2aws/blob/master/pkg/provider/googleapps/googleapps.go#L59

debug output:
```time="2020-02-27T13:41:34-05:00" level=debug msg="loginURL: " provider=googleapps```

After lots of digging by our dev team we saw that when a failure occurs, saml2aws is sent to the login page asking for a username. When it works, its sent to the login page asking for a password.

The function in googleapps.go `extractInputsByFormQuery` seems to be looking for an html element called `gaia_loginform` which looks like the below.
On failure:
```<form novalidate method="post" action="https://accounts.google.com/signin/v1/lookup" id="gaia_loginform">```
on success::
```<form novalidate method="post" action="https://accounts.google.com/signin/challenge/sl/password" id="gaia_loginform">```

We were able to work around the issue temporarily by adding an if on line 465 of `googleapps.go`:
```diff
diff --git a/pkg/provider/googleapps/googleapps.go b/pkg/provider/googleapps/googleapps.go
index 2af5a87..1017ec0 100644
--- a/pkg/provider/googleapps/googleapps.go
+++ b/pkg/provider/googleapps/googleapps.go
@@ -463,6 +463,10 @@ func extractInputsByFormQuery(doc *goquery.Document, formQuery string) (url.Valu
                actionURL = action
        })
 
+       if actionURL == ""{
+               actionURL = "https://accounts.google.com/signin/challenge/sl/password"
+       }
+
        query = fmt.Sprintf("form%s", formQuery)
 
        // extract form data to passthrough
```

But that work around is obviously not the best implementation.

**Comment by seantcanavan** [comment]
This has ground our work to a halt as well. Thanks for creating such a detailed ticket @Apollorion.

**Comment by nathandines** [comment]
I've just submitted PR #445 which should address this. Feel free to build from that and see how that goes for you.
