### ISSUE TITLE
Choco failed to install saml2aws

### ISSUE THREAD

**Issue by thunpin** [Versent/saml2aws#459]
**Step to reproduce**
- open PowerShell as administrator
- execute the command: `choco install saml2aws`

**Expected result**
- saml2aws installed

**Current result**
- saml2aws is not installed
- _error message:_ Received an unexpected EOF or 0 bytes from the transport stream. (at 96%)

**Comment by gliptak** [comment]
```choco``` does install (an older version) for me

```
PS C:\WINDOWS\system32> choco install saml2aws
Chocolatey v0.10.15
Installing the following packages:
saml2aws
By installing you accept licenses for the packages.
Progress: Downloading saml2aws 2.17.0... 100%

saml2aws v2.17.0 [Approved]
saml2aws package files install completed. Performing other installation steps.
 ShimGen has successfully created a shim for saml2aws.exe
 The install of saml2aws was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.

Chocolatey installed 1/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
```

**Comment by gliptak** [comment]
https://github.com/Versent/saml2aws/pull/432
https://github.com/Versent/saml2aws/issues/426
https://github.com/Versent/saml2aws/issues/374
https://github.com/Versent/saml2aws/issues/223
