### ISSUE TITLE
"unable to locate IDP oidc form submit URL" error

### ISSUE THREAD

**Issue by tipirk** [Versent/saml2aws#464]
I'm trying login using Azure AD but get an error

> unable to locate IDP oidc form submit URL
error authenticating to IdP
github.com/versent/saml2aws/cmd/saml2aws/commands.Login
        /Users/markw/Code/notgopath/saml2aws/cmd/saml2aws/commands/login.go:72
main.main
        /Users/markw/Code/notgopath/saml2aws/cmd/saml2aws/main.go:147
runtime.main
        /usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:203
runtime.goexit
        /usr/local/Cellar/go/1.14/libexec/src/runtime/asm_amd64.s:1373

It worked a couple of weeks ago

**Comment by tipirk** [comment]
The problem with version 2.24.0
Tested on 2.22.0 and it works as expected

**Comment by tirumalap** [comment]
any update on this issue? same issue here

**Comment by FelicityHughes** [comment]
This is still broken in 2.25.0.  Been unable to upgrade beyond 2.23.0 for AzureAD.

**Comment by leoddias** [comment]
I got same errors in 2.22.0, 2.23.0, 2.25.0

```
ubuntu@ip:~$ saml2aws --verbose login
DEBU[0000] Running                                       command=login
DEBU[0000] check if Creds Exist                          command=login
DEBU[0000] Expand                                        name=/home/ubuntu/.aws/credentials pkg=awsconfig
DEBU[0000] resolveSymlink                                name=/home/ubuntu/.aws/credentials pkg=awsconfig
DEBU[0000] ensureConfigExists                            filename=/home/ubuntu/.aws/credentials pkg=awsconfig
Using IDP Account default to access AzureAD https://account.activedirectory.windowsazure.com
To use saved password just hit enter.
? Username xxxxxx@xxxxx.com.br
? Password ***********

DEBU[0005] building provider                             command=login idpAccount="account {\n  AppID: XXXXXXX\n  URL: https://account.activedirectory.windowsazure.com\n  Username: xxxxxx@xxxxx.com.br\n  Provider: AzureAD\n  MFA: Auto\n  SkipVerify: false\n  AmazonWebservicesURN: urn:amazon:webservices\n  SessionDuration: 3600\n  Profile: saml\n  RoleARN: \n}"
Authenticating as xxxxxx@xxxxx.com.br ...
DEBU[0005] HTTP Req                                      URL="https://login.microsoftonline.com/common/login" http=client method=POST
DEBU[0005] HTTP Res                                      Status="200 OK" http=client
unable to locate IDP oidc form submit URL
error authenticating to IdP
github.com/versent/saml2aws/cmd/saml2aws/commands.Login
        /Users/markw/Code/notgopath/saml2aws/cmd/saml2aws/commands/login.go:72
main.main
        /Users/markw/Code/notgopath/saml2aws/cmd/saml2aws/main.go:146
runtime.main
        /usr/local/Cellar/go/1.13.6/libexec/src/runtime/proc.go:203
runtime.goexit
        /usr/local/Cellar/go/1.13.6/libexec/src/runtime/asm_amd64.s:1357

```

**Comment by lcrisci** [comment]
The flow is broken since this PR was merged: https://github.com/Versent/saml2aws/pull/435

It removed conditional code ( under MFA use ) which was needed to deal with /kmsi.

I tried to figure out how it fixed https://github.com/Versent/saml2aws/issues/350 but no clue so far.

This is effectively broken since https://github.com/Versent/saml2aws/releases/tag/v2.24.0.

**Comment by pwillie** [comment]
@leoddias did you get this to work?  I am seeing exactly the same output/behaviour with 2.23.0...

**Comment by tipirk** [comment]
> @leoddias did you get this to work? I am seeing exactly the same output/behaviour with 2.23.0...

2.23.0 is the last working version actually

**Comment by Mitko-Kerezov** [comment]
Hey @tipirk 
I think me and my team might have run into something very similar and I have submitted a PR with a fix for our use-case. Could you give it a try and see if it resolves your issue as well?
