### ISSUE TITLE
new type of verification when using Google app prompt for MFA

### ISSUE THREAD

**Issue by gilmoregrills** [Versent/saml2aws#477]
This issue wasn't found by me, rather by @tobystaines, but when using saml2aws to log in with his GSuite credentials he was presented with a new type of verification screen that I've not seen before: 

![IMG_0228](https://user-images.githubusercontent.com/11209344/78801798-03eb1180-79b5-11ea-9e44-d70a14a7c19a.PNG)

saml2aws didn't return any number in his terminal, which is unsurprising assuming this kind of verification step is super new. Anyone else seen this?

**Comment by FernandoMiguel** [comment]
I had open a similar one for Microsoft Authenticator 
https://github.com/Versent/saml2aws/issues/473

**Comment by testlnord** [comment]
I've faced a similar issue.
