### ISSUE TITLE
[Mac] Putting password on command line configure isn't stored in keychain

### ISSUE THREAD

**Issue by TechnicalMercenary** [Versent/saml2aws#485]
I was trying to setup a complete account via the command line.

```saml2aws configure --idp-account=test  --idp-provider=JumpCloud --username=gbonk@github.com --password="abc123" --url="https://sso.jumpcloud.com/saml2/github" --profile=default --session-duration=28800 --mfa=Auto --skip-prompt```

The command succeeds but the MacOs Keychain does not have the password stored in it.

**Comment by benaduggan** [comment]
+1 for experiencing this as of today. Ended up getting IP blocked from our SSO provider because of "unusual activity" for repeatedly attempting to login with old credentials :joy: 

Any updates on this or any potential workarounds aside from going through the prompt?

**Comment by benyitzhaki** [comment]
@benaduggan @TechnicalMercenary were you able to find a workaround?

**Comment by benaduggan** [comment]
@benyitzhaki We were using nix, so we just applied the patch from #547 through that and committed it to our repo 😅

**Comment by TechnicalMercenary** [comment]
> @benaduggan @TechnicalMercenary were you able to find a workaround?

I have not personally, but it sounds like [#547](https://github.com/Versent/saml2aws/pull/547) apparently does.  Sounds like this can be closed and forgotten.  I know I had :-)
