### ISSUE TITLE
pingfed regression between 2.25 and 2.26

### ISSUE THREAD

**Issue by gliptak** [Versent/saml2aws#494]
Running

```
saml2aws_2.26.exe list-roles
Using IDP Account default to access Ping https://pf.company.com
To use saved password just hit enter.
? Username user@company.com
? Password ****************

Failed to list roles: error parsing destination url: missing Response element
```

The above is successful with ```2.26```

https://github.com/Versent/saml2aws/compare/v2.25.0...v2.26.0

The failing lookup seems to be:

https://github.com/Versent/saml2aws/blob/master/saml.go#L90

There is no Destination XML element in the response.

**Comment by wolfeidau** [comment]
Yeah something is up with this change https://github.com/Versent/saml2aws/commit/1b67c795b2b12974c231bf21fa763ea0e525a01e I may need to revert it, or enable some sort of flag for it.

**Comment by michaelsauter** [comment]
I think I'm also running into this issue using `v2.27.1` and Ping. After login, I'm getting:

> Failed to assume role, please check whether you are permitted to assume the given role for the AWS service: error parsing destination url: missing Response element

Downgrading to `v2.25.0` solved the problem for me.
