### ISSUE TITLE
Okta Push not working after upgrading to 2.26 - OS X

### ISSUE THREAD

**Issue by pusherman** [Versent/saml2aws#497]
After upgrading to version 2.26, mfaIdentifer seems to always be set to `OKTA TOKEN:SOFTWARE:TOTP` rather than `OKTA PUSH`.

Sample from a verbose login in version 2.26
`DEBU[0012] MFA                                           factorID=12344929283 mfaIdentifer="OKTA TOKEN:SOFTWARE:TOTP" oktaVerify="https://oktaurl/verify" provider=okta`

Sample from verbose login in version 2.24
`DEBU[0012] MFA                                           factorID=12344929283 mfaIdentifer="OKTA PUSH" oktaVerify="https://oktaurl/verify" provider=okta`

Possibly related to this PR?
https://github.com/Versent/saml2aws/pull/486

This seems to *not* effect the Windows version.  OS X is effected.  Linux has not been tested.

**Comment by sagar-srivastava** [comment]
I can confirm that Okta push is now broken in 2.26 on Linux as well.

**Comment by mulvaney** [comment]
Check your ~/.saml2aws file. If you add a line like this the push should work again:

`mfa                  = PUSH`

Mine was set to OKTA, and it always made me enter the code.

It looks like before this setting was a default, and you had a chance to choose at runtime. Now it just uses whatever your setting is without asking.

**Comment by pusherman** [comment]
@mulvaney - thanks!  This resolved our issue.

**Comment by mulvaney** [comment]
Hmm, this isn't actually working for me. I mean, it does work -- once. But then when i have to login again, it always sets it back to OKTA and I have to manually change the config file.

Also, when I do log in, in my ~/.aws/credentials file, there is an empty 'region = ' block. I have to go add us-east-1 on the right side of that = every time, or the aws command line scripts dumps a few pages of python backtraces

**Comment by kpm4** [comment]
I have the same issue on linux with 2.26.1

Waiting for approval, please check your Okta Verify app .... Approved
error authenticating to IdP: error retrieving saml response: cannot find state token

it seems an issue with the regex here https://github.com/Versent/saml2aws/blob/006dda9952c2a92b62be7913cf2810654c1a8730/pkg/provider/okta/okta.go#L238

maybe something is changed in the okta response.

**Comment by aimeeu** [comment]
New user - I just installed saml2aws, v2.27.1 on Mac OS 10.15.7
mfa = PUSH 
```
Waiting for approval, please check your Okta Verify app ...... Approved
error authenticating to IdP: error retrieving saml response: cannot find state token
```

mfa = OKTA
```
error authenticating to IdP: error retrieving saml response: cannot find state token
```

**Comment by JohSchillerEmnify** [comment]
Seeing this issue as well with okta PUSH and OKTA same as @aimeeu

**Comment by MalaNimala** [comment]
I'm on saml2aws version 2.27.1 and on Mac OS 10.15.7. Experienced the same error but resolved it after remembering to connect to my VPN 😅

**Comment by netors** [comment]
I experienced this issue when adding a Sign-On rule under the AWS application in Okta, I suggest you check the Report Log in Okta, I saw that the Device was set to Unknown and it was causing a policy to deny it.
