### ISSUE TITLE
Support `--exec-profile` in `saml2aws script` command

### ISSUE THREAD

**Issue by richerve** [Versent/saml2aws#518]
I'm coming from using aws-okta and one of the most convenient feature is that it allows you to output the variables and then source them, actually as `saml2aws script` does, but the advantage in aws-okta is that it supports assuming roles in other AWS accounts following the pattern of one SSO account and then assume roles in others.

Reading the docs I noticed that `saml2aws exec` have the `--exec-profile` option to "jump" to the assumed role after login to the SSO account. It would be nice to have the same option for `saml2aws script`. I know that right now is possible to spawn a new shell using exec and $SHELL, but I'd prefer to stay in the same shell and just modify the ENV variables, having a new shell is not that convenient as history from parent shell is not accessible for example.

**Comment by richerve** [comment]
We moved to AWS SSO now, so don't see much point in keep tracking this issue

**Comment by lockwobr** [comment]
I also like this feature, and miss it from aws-okta, but this command should do what you're looking for.
```
eval `saml2aws exec --exec-profile <said-profile> "env | grep AWS |  sed -e 's/^/export /'"`
```
