### ISSUE TITLE
Strange console output

### ISSUE THREAD

**Issue by hoegertn** [Versent/saml2aws#53]
saml2aws print a strange output about osx helpers for every command.

```
$ saml2aws --version
Adding osx helper
1.8.2
```

**Comment by wolfeidau** [comment]
Just to clarify I have updated this message to read.

```
Loading osx keychain helper
```

This is a new feature which saves the password to keychain in OSX, I am about to merge changes to also support this in windows.

**Comment by hoegertn** [comment]
Is it really needed that this is printed to the console on every command?

**Comment by wolfeidau** [comment]
Good point I will drop it in lieu of a debug flag.
