### ISSUE TITLE
ValidationError: Principal ARN is invalid

### ISSUE THREAD

**Issue by pjaak** [Versent/saml2aws#536]
Hi,

I am using keycloak to authenticate to AWS. 

Currently have two roles setup and everything works through the AWS console. I have setup saml2aws to use keycloak and it lets me login and also shows me the 2 roles available to the user however I am receiving this error:

`Requesting AWS credentials using SAML assertion
ValidationError: Principal ARN is invalid
	status code: 400, request id: f35b8db9-92f2-4ea5-a2c4-624641cfa447
error retrieving STS credentials using SAML
github.com/versent/saml2aws/cmd/saml2aws/commands.loginToStsUsingRole
	/Users/markw/Code/notgopath/saml2aws/cmd/saml2aws/commands/login.go:276
github.com/versent/saml2aws/cmd/saml2aws/commands.Login
	/Users/markw/Code/notgopath/saml2aws/cmd/saml2aws/commands/login.go:97
main.main
	/Users/markw/Code/notgopath/saml2aws/cmd/saml2aws/main.go:163
runtime.main
	/usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/proc.go:203
runtime.goexit
	/usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/asm_amd64.s:1373
error logging into aws role using saml assertion
github.com/versent/saml2aws/cmd/saml2aws/commands.Login
	/Users/markw/Code/notgopath/saml2aws/cmd/saml2aws/commands/login.go:99
main.main
	/Users/markw/Code/notgopath/saml2aws/cmd/saml2aws/main.go:163
runtime.main
	/usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/proc.go:203
runtime.goexit
	/usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/asm_amd64.s:1373`

Has anyone seen this? I am running the latest brew version

Thanks

**Comment by pjaak** [comment]
Resolved.

**Comment by peterkowalski** [comment]
@pjaak How did you resolve this issue?
