### ISSUE TITLE
AWS role assumption with intermediary SAML IDP

### ISSUE THREAD

**Issue by CoreySmithRing** [Versent/saml2aws#550]
As the title describes we have two IDP. In our case we are using an exteranal IDP (Okta) and our own IDP (Okta). We allow external users to federate into our Okta. We are looking on a way to configure a profile to obtain role creds with their being an intermediary SSO provider. 

Example Worlfow Diagram of Login Flow: 
(user login) ORG IDP -> EXTERNAL IDP  OKTA -> (federate) ORG IDP -> AWS??

Is there support for authentication to another federated platform ?

**Comment by clausa** [comment]
I guess this would require support for a browser based login flow, as discussed in https://github.com/Versent/saml2aws/issues/455

**Comment by CoreySmithRing** [comment]
That does seem to be the case. 

Okay, please close/merge this and I will track #455 

Thank you.
