### ISSUE TITLE
list-roles should print to stdout and not stderr

### ISSUE THREAD

**Issue by grosser** [Versent/saml2aws#559]
2.22.1 printed the list of accounts to stdout, which allowed to pipe it to a file and still show the user some output
2.27.0 writes everything to stderr, so now I cannot separate them easily and things like `Success. Logging you in...` ends up in the output

please make the output go to stdout again

**Comment by LorisCazalon** [comment]
hello, as a workaround in our scripts that get saml2aws, i propose to also get the content of the stderr : https://github.com/zendesk/dotfiles_n_scripts/pull/81. 
We should revert the PR once this is fixed

**Comment by grosser** [comment]
Bug was added in https://github.com/Versent/saml2aws/pull/502
