### ISSUE TITLE
no buildable Go source files osxkeychain

### ISSUE THREAD

**Issue by debojitkakoti** [Versent/saml2aws#56]
How to reproduce.
OS: Ubuntu 16.04.1 LTS
How: initiate make command.
Output: 
```
1 errors occurred:
--> darwin/amd64 error: exit status 1
Stderr: go build github.com/versent/saml2aws/helper/osxkeychain: no buildable Go source files in /home/debojit/gocode/src/github.com/versent/saml2aws/helper/osxkeychain

Makefile:29: recipe for target 'compile' failed
make: *** [compile] Error 1

```

**Comment by wolfeidau** [comment]
Apologies, if you want to build on Linux use

```
make install
```

I need to update the Makefile to disable cross compile outside of OSX, I have started using `cgo` for integration with OSX keychain.

**Comment by wolfeidau** [comment]
I am always willing to accept PRs to refactor this.

**Comment by tomislacker** [comment]
_At the risk of sounding naive..._

@wolfeidau simply a clone and attempt at `make install` is not successful.

```
$ make install 
go install ./cmd/saml2aws
cmd/saml2aws/main.go:8:2: cannot find package "github.com/alecthomas/kingpin" in any of:
	/usr/lib/go/src/github.com/alecthomas/kingpin (from $GOROOT)
	/home/user/go/src/github.com/alecthomas/kingpin (from $GOPATH)
cmd/saml2aws/main.go:9:2: cannot find package "github.com/versent/saml2aws/cmd/saml2aws/commands" in any of:
	/usr/lib/go/src/github.com/versent/saml2aws/cmd/saml2aws/commands (from $GOROOT)
	/home/user/go/src/github.com/
```

```
 $ [ -z "$GOPATH" ] && echo "GOPATH is empty" || echo "GOPATH='${GOPATH}'"
GOPATH is empty
 $ [ -z "$GOROOT" ] && echo "GOROOT is empty" || echo "GOROOT='${GOROOT}'"
GOROOT is empty
```

If some sage words of advice could be offered to at least provide direction, I'd be willing to figure out the linux implications as that's what I predominately use. Then I can contribute a PR back to document what's all necessary.

**Comment by wolfeidau** [comment]
Just run `make test` once before running `make install` to install local dev dependencies.

This is something I need to tidy up, I have built the classic "works for me" build scripts, your feedback is a valuable sign in need to tidy this up.

**Comment by debojitkakoti** [comment]
It was trying to compile for all the arch when I do make install.
Simply removing `-osarch="darwin/amd64" \` works for me in Ubuntu.
I am very beginner in makefile correct me if I am wrong,  but if we can put a condition in `compile: deps` section !!
Check my PR, but I think it will break compile for darwin/amd64 [https://github.com/Versent/saml2aws/pull/59](url)
