### ISSUE TITLE
Add support for arm based CPUs

### ISSUE THREAD

**Issue by jack1902** [Versent/saml2aws#578]
It would be nice to have support for `arm` and `arm64` silicon, whilst it is possible to compile this myself, it would be helpful to have it already there for each release (i am currently using a raspberry pi but MacBooks will soon have arm :D )

For raspberry pi:
`GOOS=linux GOARCH=arm GOARM=5`

Also, why am i using a raspberry pi? (I'm using VS Code Remote SSH Extension since i don't want to install many developer tools on my windows machine)

**Comment by wolfeidau** [comment]
Yeah i need to look into this soon, updating the release process at the moment.

1.16 of Go will support apple ARM target I believe.

**Comment by wolfeidau** [comment]
I have added arm64 and armv6 builds for linux 🎉
