### ISSUE TITLE
Enable Session Duration

### ISSUE THREAD

**Issue by fogfish** [Versent/saml2aws#58]
AWS supports an optional request parameter to [prolong a SessionDuration](https://aws.amazon.com/blogs/security/enable-your-federated-users-to-work-in-the-aws-management-console-for-up-to-12-hours/)

The default session support is few hours... It would be nice to enhance the app... Do you have any idea how to implement such improvement in your app?

**Comment by fogfish** [comment]
I think I found the place:
https://github.com/Versent/saml2aws/blob/master/cmd/saml2aws/commands/login.go#L121

**Comment by nickkadams** [comment]
I would be interested to know if you solved this fogfish? I edited line 121 and compiled and am receiving:

```
ValidationError: 1 validation error detected: Value '43200' at 'durationSeconds' failed to satisfy constraint: Member must have value less than or equal to 3600
	status code: 400, request id: 
error retrieving STS credentials using SAML
```

**Comment by wolfeidau** [comment]
Yeah sadly I have tried a bunch of things to extend the session, and alas we are still at 3600 maximum. 

If you figure out a way to increase this please reopen this issue!

**Comment by fogfish** [comment]
Yeah, you are right! I've managed to change it to higher value.. I've not seen a crash but token is still valid for 1h only. I know that guys managed to increase a time to 12h with external IAM (Google). 

I'll try to squeeze more info...

**Comment by wolfeidau** [comment]
I added a section to the https://github.com/Versent/saml2aws#caveats just to help others!
