### ISSUE TITLE
saml2aws fails on Mac with M1 processor

### ISSUE THREAD

**Issue by mifitous** [Versent/saml2aws#597]
brew install saml2aws

saml2aws: The x86_64 architecture is required for this software.

**Comment by meve** [comment]
Workaround is to compile it yourself using the steps in https://github.com/Versent/saml2aws#building

**Comment by mifitous** [comment]
Hi @meve 

Didn't worked for me:
michael@Michaels-MacBook-Pro saml2aws % pwd                      
/usr/local/go/src/github.com/versent/saml2aws
michael@Michaels-MacBook-Pro saml2aws % make mod                 
michael@Michaels-MacBook-Pro saml2aws % make install             
go install ./cmd/saml2aws
michael@Michaels-MacBook-Pro saml2aws % make test   
/bin/sh: /usr/local/go/src/github.com/versent/saml2aws/bin/gocov: No such file or directory
/bin/sh: /usr/local/go/src/github.com/versent/saml2aws/bin/gocov: No such file or directory
make: *** [test] Error 127
michael@Michaels-MacBook-Pro saml2aws %

**Comment by meve** [comment]
Yeah, but, I see `go install` worked; just running the tests failed, right? If you execute `saml2aws` now, does it really not work?

So if you go to your `$GOPATH/bin` directory, there should be a `saml2aws` now.

**Comment by mifitous** [comment]
Indeed, there was an issue with my GO installation
Cleanned up all go packages etc...
re-installed
all is fine
Thanks a lot
