### ISSUE TITLE
SAML Role AttribueValue order imporant otherwise selection list dosen't include role

### ISSUE THREAD

**Issue by mcleane** [Versent/saml2aws#6]
saml2AWS expects the SAML Role (https://aws.amazon.com/SAML/Attributes/Role) AttributeValue to be formated as saml-provider,role 
eg `arn:aws:iam::456456456456:saml-provider/example-idp,arn:aws:iam::456456456456:role/admin`
otherwise if the order is reveresed the role selection list displays as follows:
```
Please choose the role you would like to assume:
[ 0 ]:  arn:aws:iam::123123123123:saml-provider/example-idp
[ 1 ]:  arn:aws:iam::123123123123:saml-provider/example-idp
[ 2 ]:  arn:aws:iam::123123123123:saml-provider/example-idp
[ 3 ]:  arn:aws:iam::123123123123:saml-provider/example-idp
[ 4 ]:  arn:aws:iam::123123123123:saml-provider/example-idp
```
AWS do not mandate an order for for the Role Attribute Value in the SAML assertion, as such identity providers can populate this attribute in any order and AWS will still be able to process the information. saml2AWS should follow the same behaviour.

**Comment by wolfeidau** [comment]
Yeah I have some code in a branch to help with this, I haven't pushed it yet as I am not happy with it yet. 

Walking you through the code Friday reminded me i need to do this. 

Will push something soon.

**Comment by mcleane** [comment]
Thanks @wolfeidau I see #9 includes changes to support AttributeValue in any order. eg saml-provider,role  or role/saml-provider
