### ISSUE TITLE
Run make fmt

### ISSUE THREAD

**Issue by sledigabel** [Versent/saml2aws#601]
When running make fmt, a few files are getting corrected.
It would be good to run this as a separate commit to avoid conflicting with future PRs:
- saml.go
- pkg/provider/adfs2/adfs2.go
- pkg/provider/keycloak/keycloak.go
- pkg/provider/netiq/netiq_test.go
- pkg/provider/okta/okta_test.go
- pkg/provider/pingone/pingone.go
- pkg/provider/shell/shell.go
- pkg/shell/env.go

**Comment by wolfeidau** [comment]
yeah i need to uplift the formating / linting to help vet PRs

I will add https://github.com/golangci/golangci-lint action once i fix all the errors.

**Comment by wolfeidau** [comment]
Should be sorted now
