### ISSUE TITLE
saved username is not used

### ISSUE THREAD

**Issue by archhacker** [Versent/saml2aws#61]
While the username is listed in the ~/.awas2saml.config file

Still getting prompted for username ( and not offered as a default value ) 

secondly, would like to skip prompt for hostname and username and only prompt for password.

using version 1.8.3

**Comment by superwg** [comment]
Same here version: saml2aws_1.8.3_linux_amd64.tar.gz

**Comment by wolfeidau** [comment]
New release which fixes this, reopen if you have issues.
