### ISSUE TITLE
Ability for multiple hostnames in .aws2saml.conf file

### ISSUE THREAD

**Issue by ghost** [Versent/saml2aws#63]
Would it be possible to create the option to have multiple hostnames for a single provider? Example if you have different roles and you wanted to switch between them with SAML2AWS you have to enter a different hostname in each time. If there was a way to read the config file with hostnames that you wanted to regularly use that would make things really easy for switch authenticating.

**Comment by mksquared** [comment]
```
  1 [JumpCloud]    
  2 [profile: admin]
  3 username = joeadmin@me.com
  4 hostname = sso.jumpcloud.com/saml2/SSO-AWS-admin
  5  
  6 [JumpCloud]
  7 [profile: read-only]
  8 username = joey@me.com
  8 hostname = sso.jumpcloud.com/saml2/SSO-AWS-read-only
```
