### ISSUE TITLE
ARM64 (aarch64) build

### ISSUE THREAD

**Issue by arnaudlacour** [Versent/saml2aws#652]
I am preparing to move everything over to ARM (our builds) and we rely on `saml2aws` to push to ECR.
I am ready to help and contribute to making build changes where necessary.
Build instructions would help greatly.

**Comment by sledigabel** [comment]
@arnaudlacour have you looked at the generated builds for most OS's and architectures?

https://github.com/Versent/saml2aws/releases/tag/v2.28.4

Is there something missing?

To build just run make build it should generate them all locally in the dist directory.

**Comment by arnaudlacour** [comment]
I apologize I had completely missed the arm64 binary, thanks, that's the ticket.

The build errored out with 
```
      • building                  binary=/home/ec2-user/projects/saml2aws/dist/saml2aws_linux_arm64/saml2aws
   ⨯ build failed after 0.06s error=failed to build for linux_arm_6:
make: *** [build] Error 1
```
