### ISSUE TITLE
QUESTION\ENHANCEMENT - retain okta auth code longer?

### ISSUE THREAD

**Issue by javamonkey79** [Versent/saml2aws#655]
Hello, thanks for this tool it works great! I've just started using it instead of [aws-okta](https://github.com/segmentio/aws-okta). 

However, with this tool, when the session times out, I must enter a new okta code, but, aws-okta somehow retained the code or some other part of the login much longer. So, when your session timed out, you only needed to run the command again and not fetch a new auth code from your MFA device. 

Is this something this app can do? Sorry if I am not describing it very well. 

Thanks in advance!

**Comment by mapkon** [comment]
If you are willing to implement it, I can merge - However, we don't envision designing that soon. 

Reopen the issue if you intend to work on it.
