### ISSUE TITLE
Release Cycle?

### ISSUE THREAD

**Issue by donofriov** [Versent/saml2aws#656]
Hey, I wasn't sure where to ask this, but is there a standard release cycle? I'm just wondering when the next release is going to be because it has a fix for Google Prompts that greatly helps our work flow. Currently the Google and Gmail apps on both iOS and Android will crash without being able to recover (always crash when re-opening the app) if a Google Prompt is sent and then not accepted. When it times out, the applications don't know what to do with it and crash.

**Comment by wolfeidau** [comment]
I try and do one every fortnight but i have been trying to track down a couple of issues.

Thanks for the bump I have pushed out a release now as it is well overdue :tada:
