### ISSUE TITLE
32bit windows

### ISSUE THREAD

**Issue by peter-chun** [Versent/saml2aws#66]
Hi, 
is it possible to add a 32bit windows version to the releases area?
Thanks

**Comment by davidobrien1985** [comment]
Surely the times of x86 Windows clients are over by now?

Sent from my iPhone

On 9 Oct 2017, at 5:12 pm, archhacker <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,
is it possible to add a 32bit windows version to the releases area?
Thanks

**Comment by archhacker** [comment]
unfortunately some companies are a little behind 
we also have offshore teams who are running 32bit windows ( outside our control )

thanks
