### ISSUE TITLE
Bug: using --credential-process with okta push verify not working

### ISSUE THREAD

**Issue by pseudo-su** [Versent/saml2aws#685]
I'm trying to use `--credential-process` with okta provider. The `saml2aws` command is outputting extra data/logging info to stdout that is causing issues (even though `--quiet` and `--skip-prompt` are passed as arguments).

AWS CLI Config file (`~/.aws/config`):

```ini
[profile my-acc-Admin]
region = ap-southeast-2
credential_process = saml2aws login --skip-prompt --quiet --credential-process --role=arn:aws:iam::XXX:role/Admin --profile=my-acc-Admin
```

Saml2AWS config file (`~/.saml2aws`):

```
[default]
url         = https://XXX.okta.com/home/amazon_aws/XXX/XXX
username    = username
provider    = Okta
mfa         = PUSH
skip_verify = false
timeout     = 0
aws_urn     = urn:amazon:webservices
```

When the AWS CLI runs the credential process I get the error:

```
Expecting value: line 1 column 1 (char 0)
```

I believe the problem is that the saml2aws CLI is sending more than just the required JSON payload to stdout. EG If I run the saml2aws command directly it's sending this to stdout:

```raw

Waiting for approval, please check your Okta Verify app ...... Approved

{<the credentials>}

```

## Possible solution

1. Remove uses of `fmt.Printf` and instead (presumably?) use the logger https://github.com/Versent/saml2aws/blob/a882ec419d0e47210fa49f5d30c793cd64dc3628/pkg/provider/okta/okta.go#L786
2. Add an extra CLI flag similar to `--quiet` called something like `--log-stderr` that defaults to sending all log output to stderr. when using `credential_process` that would mean the user could still see the output in the console but it wouldn't get sent to stdout and cause issues https://github.com/Versent/saml2aws/commit/3d5f4ffa6c844684a9235ed8e53b8f03a03e959b#diff-700f078cb6e14d20af7c09e73a1507604a85cfb66d6c54db727f45dc21a13d2aR155-R159

EDIT: After looking at the code it seems like it might default to using `os.Stderr` so the `--log-stderr` suggestion might not be helpful.

**Comment by iciclespider** [comment]
Use `--quiet`.
