### ISSUE TITLE
authenticating to IdP: error verifying MFA: Unsupported response from Okta

### ISSUE THREAD

**Issue by mcgonagle** [Versent/saml2aws#699]
Trying to auth with okta but receiving an error. This is a new behavior. 
Verbose Output is as follows:
Unsupported response from Okta, please raise ticket with saml2aws
github.com/versent/saml2aws/v2/pkg/provider/okta.verifyMfa
	github.com/versent/saml2aws/v2/pkg/provider/okta/okta.go:821
github.com/versent/saml2aws/v2/pkg/provider/okta.(*Client).Authenticate
	github.com/versent/saml2aws/v2/pkg/provider/okta/okta.go:479
github.com/versent/saml2aws/v2/cmd/saml2aws/commands.Login
	github.com/versent/saml2aws/v2/cmd/saml2aws/commands/login.go:105
main.main
	github.com/versent/saml2aws/v2/cmd/saml2aws/main.go:187
runtime.main
	runtime/proc.go:225
runtime.goexit
	runtime/asm_amd64.s:1371
error verifying MFA
github.com/versent/saml2aws/v2/pkg/provider/okta.(*Client).Authenticate
	github.com/versent/saml2aws/v2/pkg/provider/okta/okta.go:481
github.com/versent/saml2aws/v2/cmd/saml2aws/commands.Login
	github.com/versent/saml2aws/v2/cmd/saml2aws/commands/login.go:105
main.main
	github.com/versent/saml2aws/v2/cmd/saml2aws/main.go:187
runtime.main
	runtime/proc.go:225
runtime.goexit
	runtime/asm_amd64.s:1371
error authenticating to IdP
github.com/versent/saml2aws/v2/cmd/saml2aws/commands.Login
	github.com/versent/saml2aws/v2/cmd/saml2aws/commands/login.go:107
main.main
	github.com/versent/saml2aws/v2/cmd/saml2aws/main.go:187
runtime.main
	runtime/proc.go:225
runtime.goexit
	runtime/asm_amd64.s:1371

**Comment by alexsander-procore** [comment]
After upgrading from 2.30.0 to 2.32.0 Okta stop working. I just downgrade it back to 2.30.0 and now it's working properly.

**Comment by mcgonagle** [comment]
Hi @alexsander-procore did you downgrade via brew? I am having trouble figuring out how to do so...Your advice is greatly appreciated.

**Comment by alexsander-procore** [comment]
Hey @mcgonagle 
No, I just went to https://github.com/Versent/saml2aws/releases , under 2.30.0 release. I downloaded the asset saml2aws_2.30.0_linux_amd64.tar.gz (I'm using linux)
If you are running macOS, I think you are good with the the darwin asset (amd64 for Intel or arm64 for M1)

**Comment by BennyG93** [comment]
Is there any update in this error? Is the only solution so far to downgrade the version?

I am seeing this error with version `2.34.0` while trying to use Okta with Okta Verify Push notifications.

```
provider                = Okta
mfa                     = PUSH
```

Full error message:
```
Waiting for approval, please check your Okta Verify app ...
 Error
Error authenticating to IdP.: error verifying MFA: Unsupported response from Okta, please raise ticket with saml2aws
```
