### ISSUE TITLE
Is google prompt with extra number challenge supported?

### ISSUE THREAD

**Issue by miguelaferreira** [Versent/saml2aws#728]
I'm getting an extra numeric challenge, when authenticating using Google IdP and Google Prompt as the 2FA mechanism.
However, `saml2aws` is not giving me the number I need to select on my phone.

Is this extra challenge supported?

See this screenshot with the challenge has it happens in the browser:
![image](https://user-images.githubusercontent.com/4670993/134012748-bf5097a1-5ff0-4fdb-9bb1-02c4cd37bdfe.jpg)

**Comment by Enviii** [comment]
Do Google prompts work for you? I (and another colleague) have not received any today when attempting to authenticate.

**Comment by miguelaferreira** [comment]
Yes, I'm getting the prompt.

**Comment by msmenegol** [comment]
I've been having this issue as well. The challenge appears on my phone after I answer the prompt, but no number get displayed on the terminal. I tried running saml2aws with ```--verbose```, but it seems that the solution doesn't get printed anywhere as well.
![2fa_challenge](https://user-images.githubusercontent.com/23125726/134186494-07801db5-6f97-49da-aeca-8ffbc9cb4b71.jpg)
