### ISSUE TITLE
saml2aws: command  not found

### ISSUE THREAD

**Issue by ashwani29** [Versent/saml2aws#748]
I installed saml2aws following the below steps:

```
CURRENT_VERSION=$(curl -Ls https://api.github.com/repos/Versent/saml2aws/releases/latest | grep 'tag_name' | cut -d'v' -f2 | cut -d'"' -f1)
wget -c https://github.com/Versent/saml2aws/releases/download/v${CURRENT_VERSION}/saml2aws_${CURRENT_VERSION}_linux_amd64.tar.gz -O - | tar -xzv -C ~/.local/bin
chmod u+x ~/.local/bin/saml2aws
hash -r
saml2aws --version
```
 but getting saml2aws command not found errors. Please help in resolving this.

OS: ubuntu-18.04

**Comment by onecoldwhiteday** [comment]
I have the same issue. Does anyone know is there's required also some manipulation with adding this to PATH or something?

OS: ubuntu-20.04.4

**Comment by hcl1687** [comment]
@ashwani29 @onecoldwhiteday 
This works for me.
```
CURRENT_VERSION=$(curl -Ls https://api.github.com/repos/Versent/saml2aws/releases/latest | grep 't ag_name' | cut -d'v' -f2 | cut -d'"' -f1)
wget https://github.com/Versent/saml2aws/releases/download/v${CURRENT_VERSION}/saml2aws_${CURRENT_ VERSION}_linux_amd64.tar.gz
tar -xzvf saml2aws_${CURRENT_VERSION}_linux_amd64.tar.gz
mv saml2aws /usr/local/bin/
chmod u+x /usr/local/bin/saml2aws
```

**Comment by Asher24** [comment]
@hcl1687 The first line should be 
grep 'tag_name'
not
grep 't ag_name'

In full:
CURRENT_VERSION=$(curl -Ls https://api.github.com/repos/Versent/saml2aws/releases/latest | grep 'tag_name' | cut -d'v' -f2 | cut -d'"' -f1)

**Comment by ashwani29** [comment]
@hcl1687  minor correction here, replace the `t ag_name` , `CURRENT _VERSION` with `tag_name` and `CURRENT_VERSION`.

**Comment by hcl1687** [comment]
@Asher24 @ashwani29 
Done.
Thank you!

**Comment by Ahmad-HosseiniMighani** [comment]
> @ashwani29 @onecoldwhiteday This works for me.
> 
> ```
> CURRENT_VERSION=$(curl -Ls https://api.github.com/repos/Versent/saml2aws/releases/latest | grep 'tag_name' | cut -d'v' -f2 | cut -d'"' -f1)
> wget https://github.com/Versent/saml2aws/releases/download/v${CURRENT_VERSION}/saml2aws_${CURRENT_VERSION}_linux_amd64.tar.gz
> tar -xzvf saml2aws_${CURRENT_VERSION}_linux_amd64.tar.gz
> mv saml2aws /usr/local/bin/
> chmod u+x /usr/local/bin/saml2aws
> saml2aws --version
> ```

This did it or me however I needed to do `sudo mv saml2aws /usr/local/bin/`

**Comment by mdragoss** [comment]
> 

Just need to update PATH

`export PATH="$PATH:$HOME/.local/bin/"`

**Comment by tinaboyce** [comment]
Closing this issue as a recently merged PR has an update README to cover Ubuntu-specific instructions #1238 .

Thank you everyone who has contributed to this discussion.
