### ISSUE TITLE
saml2aws login fails when $HOME/.aws/credentials missing

### ISSUE THREAD

**Issue by w4-sjcho** [Versent/saml2aws#75]
`saml2aws login` fails with the following error when `$HOME/.aws/credentials` file is missing.

```
lstat /home/sjcho/.aws/credentials: no such file or directory
unable to resolve symlink
github.com/versent/saml2aws/pkg/awsconfig.(*CredentialsProvider).filename
        /opt/saml2aws/src/github.com/versent/saml2aws/pkg/awsconfig/awsconfig.go:144
github.com/versent/saml2aws/pkg/awsconfig.(*CredentialsProvider).Save
        /opt/saml2aws/src/github.com/versent/saml2aws/pkg/awsconfig/awsconfig.go:64
github.com/versent/saml2aws/cmd/saml2aws/commands.Login
        /opt/saml2aws/src/github.com/versent/saml2aws/cmd/saml2aws/commands/login.go:146
main.main
        /opt/saml2aws/src/github.com/versent/saml2aws/cmd/saml2aws/main.go:76
runtime.main
        /snap/go/922/src/runtime/proc.go:185
runtime.goexit
        /snap/go/922/src/runtime/asm_amd64.s:2337
error saving credentials
github.com/versent/saml2aws/cmd/saml2aws/commands.Login
        /opt/saml2aws/src/github.com/versent/saml2aws/cmd/saml2aws/commands/login.go:148
main.main
        /opt/saml2aws/src/github.com/versent/saml2aws/cmd/saml2aws/main.go:76
runtime.main
        /snap/go/922/src/runtime/proc.go:185
runtime.goexit
        /snap/go/922/src/runtime/asm_amd64.s:2337
```

The command works fine when I create an empty credentials file before running the command.

**Comment by wolfeidau** [comment]
Gday mate, 

The required setup is documented in the readme.

https://github.com/versent/saml2aws#setup 

Always happy to review a PR to make this easier for users.

Cheers

**Comment by w4-sjcho** [comment]
Hi.

`aws configure` only creates `.aws/config` and not `.aws/credentials` (on my linux machine), which is causing the problem.

**Comment by wolfeidau** [comment]
I just had a read over http://docs.aws.amazon.com/cli/latest/reference/configure/ and your correct, I probably never hit this case as I use accounts with tokens as well.

I am going to update it to some alternative setup which will hopefully create both files. The credentials entered will be overwritten the first time you log in using saml2aws if you use the default `saml` profile.

```
$ aws configure --profile saml
AWS Access Key ID [None]: test
AWS Secret Access Key [None]: test
Default region name [None]: us-west-2
Default output format [None]:
```

How does that sound?

**Comment by w4-sjcho** [comment]
Sounds good, though it would be really great if `saml2aws` can create the file if its missing.

Thanks for the great tool, BTW. It really helped us a lot.

**Comment by wolfeidau** [comment]
Now fixed with https://github.com/Versent/saml2aws#setup
