### ISSUE TITLE
Okta WebAuthN flow errors out after short time window

### ISSUE THREAD

**Issue by alsmola** [Versent/saml2aws#756]
For some reason, when signing in via Okta WebAuthN, after a second or so we receive the following error:

```
Touch the flashing U2F device to authenticate...
Error authenticating to IdP.: error verifying MFA: failed to perform U2F challenge: hidapi: hid_error is not implemented yet
```

A fix was attempted in another fork's PR (https://github.com/Versent/saml2aws/pull/668), but I created a more targeted/user-friendly PR to solve this particular problem - https://github.com/Versent/saml2aws/pull/755

**Comment by wolfeidau** [comment]
This is merged and shipped, could you test it and close this @alsmola 🙏
