### ISSUE TITLE
saml cache expiration not being dealt with correctly

### ISSUE THREAD

**Issue by archoversight** [Versent/saml2aws#759]
I use Keycloak with saml2aws, and the caching feature is greatly appreciated since it reduces the amount of round trips necessary when logging in to multiple accounts, however the cache expiration seems to be longer than the default expiration of the SAML response that Keycloak is sending back:

```
Requesting AWS credentials using SAML assertion.
Error logging into AWS role using SAML assertion.: Error retrieving STS credentials using SAML.: ExpiredTokenException: Response has expired
	status code: 400, request id: 4370fb7a-3407-4a93-b0b7-adac0147c352
```

It's about a 1 minute timeout which is set in the SAML response:

```
    <saml:Conditions NotBefore="2022-01-17T03:36:32.630Z" NotOnOrAfter="2022-01-17T03:37:32.630Z">
      <saml:AudienceRestriction>
        <saml:Audience>urn:amazon:webservices</saml:Audience>
      </saml:AudienceRestriction>
    </saml:Conditions>
```

The default set in `saml2aws` is 5 minutes:

https://github.com/Versent/saml2aws/blob/f872b40adad009b4bd3c8a497618fc8c2006a878/pkg/samlcache/samlcache.go#L23

It would be great if this is a flag we can pass in, or if it could get parsed from the SAML response.

**Comment by sledigabel** [comment]
Hi @archoversight ,

Thank you for reporting, your suggestion to parse it from the SAML response is an excellent idea.
