### ISSUE TITLE
Okta provider empty SAML Assertion

### ISSUE THREAD

**Issue by richardheath** [Versent/saml2aws#77]
We are using Okta+DUO for AWS authentication. I cannot get Okta provider to work. SAML Assertion is always empty. I got it to work by sending another get request to Okta APP to actually get SAML Assertion value (Code below). For now I just patch it and recompile so we can start using this awesome tool.

I am wondering if I am missing something to get Okta+DUO to work without code changes below?

If fix below is necessary then what is the proper way to setup extra config per provider? (Like for fix below it will need Okta APP parameter.)

Repo with the patch:
https://github.com/richardheath/saml2aws/blob/master/pkg/provider/okta/okta.go

I hardcoded the Okta APP since I am not sure how to properly make this a config option:
```
req, err = http.NewRequest("GET", oktaEntryURL+"/home/amazon_aws/0oagi9d4ouv6LpCWS0x7/272", nil)
if err != nil {
	return samlAssertion, errors.Wrap(err, "error building app request")
}

q = req.URL.Query()
q.Add("RelayState", "/")
q.Add("sessionToken", oktaSessionToken)
req.URL.RawQuery = q.Encode()

req.Header.Add("Accept", "*/*")
res, err = oc.client.Do(req)
if err != nil {
	return samlAssertion, errors.Wrap(err, "error retrieving app response")
}
```

**Comment by wolfeidau** [comment]
Gday

I think there is some confusion with the hostname field, at the moment I am using it for hostname and path. 

So in the case of okta when i get asked for the hostname i just enter.

```
Hostname: test.okta.com/home/amazon_aws/0oagi9d4ouv6LpCWS0x7/272
```

Hope that helps and thanks for reminding me i need to rename that field to URL.

**Comment by richardheath** [comment]
I tried that before but it failed since it's not parsing the host from URL. I tried the latest code and it works perfectly! Thank you for the update.
