### ISSUE TITLE
Auth error

### ISSUE THREAD

**Issue by OmerBlechman** [Versent/saml2aws#775]
Hi,
I'm using saml2aws for a few months and today I received the following error while trying to login:
```Error authenticating to IdP.: failed to saml request reprocess: error reprocess results: post "": unsupported protocol scheme ""```

I checked with my colleagues, and they are receiving the same error.
Can you assist?

**Comment by ericgomes56** [comment]
@OmerBlechman I have the same issue.

saml2aws --version
2.34.0

Error authenticating to IdP.: failed to saml request reprocess: error reprocess results: post "": unsupported protocol scheme ""
