### ISSUE TITLE
--role seems to be ignored

### ISSUE THREAD

**Issue by sandervanburken** [Versent/saml2aws#80]
## Works
* Login works with `saml2aws login`
* awscli works with multiple profiles defined in `~/.aws/config`. For example this non-default profile can be used: `aws -p dev ec2 describe-instances`.

## Does not work
* Login and specify the same arn role as defined in `~/.aws/config` for profile 'dev'. Error message:

```
Supplied RoleArn not found in saml assertion: <supplied arn role>
Failed to assume role, please check you are permitted to assume the given role for the AWS service
```

(1) As shown above, I am permitted to assume this role... Or is there a difference with logging in with a arn role specified via `--role` vs logging in and assuming that same arn role via `aws -p`?

* Using the same arn role as defined in `~/.aws/config` for profile 'dev' and then execute:

```shell
saml2aws exec --role '<arn role copied from aws config>' aws ec2 describe-instances
Running command as: arn:aws:sts::....:assumed-role/..../....
```

The `Running command as:` does not show the role specified by the `--role` parameter. It's even possible to add a bogus text value for the `--role` parameter, and it still executes with always the same role.

(2) How can I use `exec` with a different arn role?

**Comment by chamila-c** [comment]
See also: https://github.com/Versent/saml2aws/issues/60

**Comment by mapkon** [comment]
@chamila-c Are you still experiencing this issue?
