### ISSUE TITLE
[Browser Provider] Support browser type

### ISSUE THREAD

**Issue by eliat123** [Versent/saml2aws#815]
Whenever using the `Browser` idp-provider, the default launched browser is `Chromium,` which the `playwright-go` package supports by default.

This behaviour is acceptable in most cases; however, when there are specific self-signed trust certificates, the default `Chromium` does not recognize installed certificates and already trusted CAs, and there is a prompt to approve them.

To fix it, we would like to add to the `saml2aws` configuration a `browser_type` property for the `Browser` Idp-provider, which will set it in the playwright launch configuration.

**Comment by MatteoJoliveau** [comment]
Cross-linking my comment on the relevant PR: https://github.com/Versent/saml2aws/pull/816#issuecomment-1174781406

This feature would allow `saml2aws` to work flawlessly on NixOS/other non-FHS linux distributions

**Comment by merusso** [comment]
Personally, I'd love it if this feature would use the system's default browser instead of downloading a playwright browser, if that's possible.

**Comment by merusso** [comment]
> Cross-linking my comment on the relevant PR: [#816 (comment)](https://github.com/Versent/saml2aws/pull/816#issuecomment-1174781406)
> 
> This feature would allow `saml2aws` to work flawlessly on NixOS/other non-FHS linux distributions, which are broken at the moment.

@MatteoJoliveau, I'm not sure about this statement. I asked for clarification on the PR.

**Comment by eliat123** [comment]
Closing as https://github.com/Versent/saml2aws/pull/816 was merged
