### ISSUE TITLE
Updated version to Chocolatey

### ISSUE THREAD

**Issue by mikemartind** [Versent/saml2aws#820]
Newer versions are available here, but apparently not through the recommended (and the only documented) method for installing to Windows.

**Comment by briantist** [comment]
if #766 gets approved, MSI releases will also be available as part of the standard build, but unfortunately I haven't been able to get anyone to review it in over 6 months 😞

There's still a release on my fork; I think one version behind though it's still working fine in my environment. I could also update that to the latest. I was trying not to keep this fork, hoping the PR would be accepted.

**Comment by mikemartind** [comment]
Does your version include the fix for whatever broke Google integration w/ headless browsers? I think that came out around when I made this issue. The pull req for that was handled comparatively pdq.

**Comment by briantist** [comment]
I doubt it, that release is from February 3rd. I could look into bringing that up to date if you specifically want the MSI installer.

Note that the installer I generate with my PR is always based on the .exe that gets built by the normal release process, so if you don't care about an installer, you can grab the `saml2aws.exe` binary directly off the official release:
- https://github.com/Versent/saml2aws/releases/tag/v2.35.0
- https://github.com/Versent/saml2aws/releases/download/v2.35.0/saml2aws_2.35.0_windows_amd64.zip

**Comment by gliptak** [comment]
@wolfeidau please review linked PRs

**Comment by gliptak** [comment]
next release (tagged) might update https://community.chocolatey.org/packages?q=saml2aws
