### ISSUE TITLE
Display MFA factor type in the verification code prompt (Okta)

### ISSUE THREAD

**Issue by pwmcintyre** [Versent/saml2aws#83]
Current prompt says:
"Enter verification code:"

you can tell which type from the factorType field

From Okta SMS (no other factors enrolled)
`"factors\":[{\"id\":\"<redacted>\",\"factorType\":\"sms\",\"provider\":\"OKTA\"`

**Comment by pwmcintyre** [comment]
All possible factor types for Okta:
https://developer.okta.com/docs/api/resources/factors.html#factor-type

**Comment by dt-rush** [comment]
I was just affected by this. Baffled and I just went ahead and assumed it was my [google 2fa app](https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2&hl=en_CA)'s generated code i was to insert. But It could have been okta via sms as OP, or any number of other things.
