### ISSUE TITLE
Error authenticating to IdP.: page is missing saml assertion

### ISSUE THREAD

**Issue by viniciusps** [Versent/saml2aws#841]
Hi,

I am trying to login to AWS using `saml2aws login` however I am getting the following error message: `Error authenticating to IdP.: page is missing saml assertion`.

While investigating the HTML file from the response, this is what I get:
<img width="497" alt="Screen Shot 2022-06-26 at 6 58 46 pm" src="https://user-images.githubusercontent.com/1593929/175807040-3ef7d023-85f1-4358-be96-a722c4b472ff.png">

Could you please let me know how I can fix this?

Thank you.

**Comment by martin-shippit** [comment]
Hmm, yeah seems like something has changed in the response from Google. It was working for me last week, and today I get a captcha that doesn't work:
```
$ saml2aws --version 
2.35.0

$ saml2aws login
Using IdP Account default to access GoogleApps ...
? Captcha ...
Open this link in a browser:
 https://accounts.google.com/Captcha? ...
 
Error authenticating to IdP.: page is missing saml assertion
```

**Comment by jt-shippit** [comment]
It is broken for me too, and none of the captchas that I am introducing seems to work. 

Error authenticating to IdP.: page is missing saml assertion

**Comment by viniciusps** [comment]
> 

Weirdly today I tested it again and now instead of asking for captcha it asked for sms token and it worked!

```
➜  git:(master) ✗ saml2aws login
Using IdP Account default to access GoogleApps https://accounts.google.com/o/saml2/initsso?idpid=XXX&spid=XXX&forceauthn=false
To use saved password just hit enter.
? Username XXXXXX
? Password 

Authenticating as XXXX ...
? Enter SMS token: G- XXXX
? Please choose the role Account: aws (XXX) / Administrator
Selected role: XXX/Administrator
Requesting AWS credentials using SAML assertion.
Logged in as: XXXXXX

Your new access key pair has been stored in the AWS configuration.
Note that it will expire at 2022-06-27 22:11:09 +1000 AEST
```

**Comment by jt-shippit** [comment]
> > 
> 
> Weirdly today I tested it again and now instead of asking for captcha it asked for sms token and it worked!
> 
> ```
> ➜  git:(master) ✗ saml2aws login
> Using IdP Account default to access GoogleApps https://accounts.google.com/o/saml2/initsso?idpid=XXX&spid=XXX&forceauthn=false
> To use saved password just hit enter.
> ? Username XXXXXX
> ? Password 
> 
> Authenticating as XXXX ...
> ? Enter SMS token: G- XXXX
> ? Please choose the role Account: aws (XXX) / Administrator
> Selected role: XXX/Administrator
> Requesting AWS credentials using SAML assertion.
> Logged in as: XXXXXX
> 
> Your new access key pair has been stored in the AWS configuration.
> Note that it will expire at 2022-06-27 22:11:09 +1000 AEST
> ```

I just tested from my end, and seems to be working again

**Comment by martin-shippit** [comment]
Works for me too now. How weird :thinking:

**Comment by mathieuorhan** [comment]
Several persons reported this exact issue today (including myself). It's back!

**Comment by stephanschielke** [comment]
We can report the same issue and our workaround is to use the `Browser` mode instead of the `GoogleApps` mode by changing your configuration:
```
sed -i 's/GoogleApps/Browser/g' ~/.saml2aws
```

The previous fix by @jmctune doesn't seem to work anymore:
https://github.com/Versent/saml2aws/commit/b044230ac8a2ba5544ecf6927a4947a364910cef

**Comment by fredle** [comment]
> We can report the same issue and our workaround is to use the `Browser` mode instead of the `GoogleApps` mode by changing your configuration:
> 
> ```
> sed -i 's/GoogleApps/Browser/g' ~/.saml2aws
> ```
> 
> The previous fix by @jmctune doesn't seem to work anymore: [b044230](https://github.com/Versent/saml2aws/commit/b044230ac8a2ba5544ecf6927a4947a364910cef)

@stephanschielke thank you so much! works for me, saved my life too.

**Comment by jmctune** [comment]
See if https://github.com/Versent/saml2aws/pull/850 resolves the problem for those that are experiencing this.

**Comment by rustymagnet3000** [comment]
Hi @jmctune, I locally built the #850.  That didn't fix this issue:

`Error authenticating to IdP.: page is missing saml assertion`

```
▶ cat ~/.saml2aws
[default]
app_id                  = 
url                     = https://accounts.google.com/o/saml2/initsso?idpid=<id_provider>&spid=<service_provider_id>&forceauthn=false
username                = foo@foobar.com
provider                = GoogleApps
mfa                     = Auto
aws_urn                 = urn:amazon:webservices
aws_session_duration    = 7200
aws_profile             = saml
```
