### ISSUE TITLE
Ability to configure session expiry time

### ISSUE THREAD

**Issue by lukemundy** [Versent/saml2aws#85]
Currently when authenticating, the resulting credentials are only valid for an hour. Is there a way to configure this value so that we could have credentials expire after 6 hours?

When we first configured access to our AWS console via ADFS we were able to set up a claim rule that specified how long the session should last (see [this AWS blog post](https://aws.amazon.com/blogs/security/enable-your-federated-users-to-work-in-the-aws-management-console-for-up-to-12-hours/) for more info). It would be great if saml2aws could use of this same claim rule.

**Comment by jc-asdf** [comment]
Unfortunately, AssumeRoleWithSAML only supports 900 -
 3600 seconds -
 see http://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRoleWithSAML.html

There's a note in the docs above about how and why this is different than the Console session time too.

That said I would like to have configurable options for this and a few more things; ideally settable in the config file too.  I'll draft a PR with some ideas.

**Comment by wolfeidau** [comment]
Yeah https://github.com/Versent/saml2aws#caveats was added to ensure this is clear.

Any suggestions on how to work around this are appreciated.

**Comment by boak** [comment]
You guys are AWS partners right? Is this a feature request you could raise with them?

**Comment by kevbook** [comment]
https://github.com/Nextdoor/nd_okta_auth - they solve it w/ `Re-Up Mode`

> Amazon IAM only supports Federated Login sessions that last up to 1 hour. For developers, it can be painful to re-authenticate every hour during your work day. This is made much worse if your organization requires MFA on each login.
> 
> You may run the Okta Auth-er tool in "reup" mode to get around this. The tool will stay running in a daemon-like mode, and it will reach out regularly to Okta, generate a new SAML Assertion, and then generate updated Amazon AWS credentials. This can run for as long as your Okta administrator has allowed your Login Session to be - often a full work day.
> 
> See the --reup commandline option for help here!

**Comment by wolfeidau** [comment]
That is a pretty cool idea, i had considered building an agent but not like that.

The only challenge is it assumes there is no MFA as that would require user interaction.

**Comment by kevbook** [comment]
The admins would set MFA validity for each session. We do a full work day session. For most companies, I would think thats okay. 
You would also keep the same role as previous session when logging in.
