### ISSUE TITLE
Adding autocomplete line to .zshrc breaks aws autocomplete

### ISSUE THREAD

**Issue by MPH13** [Versent/saml2aws#868]
This may simply be an issue with my understanding of the "order" of items in my ~/.zshrc file, but adding the line you suggest for your auto-completion, `eval "$(saml2aws --completion-script-zsh)"` **after** the AWS CLI autocomplete lines as listed [here](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-completion.html), will break the usage of AWS CLI autocomplete. Thanks for any insight.

AWS asks to add these lines to your profile:
`autoload -Uz compinit && compinit`
`autoload -U +X bashcompinit && bashcompinit`

`complete -C '/usr/local/bin/aws_completer' aws`

**Comment by patrickli** [comment]
You can just use the bash version after you load the aws completion. Like this:
```
autoload -Uz compinit && compinit
autoload -U +X bashcompinit && bashcompinit

complete -C '/usr/local/bin/aws_completer' aws
eval "$(saml2aws --completion-script-bash)"
```

**Comment by MPH13** [comment]
Yep, fixed it! Thank you!

Any little tidbit of knowledge on WHY this worked? Thanks again.

**Comment by patrickli** [comment]
The only difference between `--completion-script-bash` and `--completion-script-zsh` is the `zsh` version adds the `autoload` lines you already have above.

So this should work as well:
```
eval "$(saml2aws --completion-script-zsh)"
complete -C '/usr/local/bin/aws_completer' aws
```

**Comment by MPH13** [comment]
Thank you. Really appreciate the insight. Cheers!
