### ISSUE TITLE
Google Apps support

### ISSUE THREAD

**Issue by estahn** [Versent/saml2aws#90]
We're using Google Apps as IdP. Would be great to see this supported.

**Comment by wolfeidau** [comment]
I really want to do this, however i have a couple of questions.

1. Have you seen any examples in python / bash / whatever?
2. Are you using MFA with google apps?

**Comment by estahn** [comment]
@wolfeidau 

1. I have not seen examples of this. However, I like how [GAM](https://github.com/jay0lee/GAM) does the authentication, e.g. It runs a local webserver temporarily to fetch the response.
2. Yes, we do.

**Comment by rverma-nikiai** [comment]
+1 on this. We are using https://github.com/cevoaustralia/aws-google-auth but would loved to switch to a go based agent.

**Comment by wolfeidau** [comment]
I have setup a test account and started porting this provider, the links were super helpful @rverma-nikiai thanks!
