### ISSUE TITLE
release not creating keychain secret

### ISSUE THREAD

**Issue by anden-dev** [Versent/saml2aws#900]
Hello,

if I directly use the latest release 
saml2aws_2.36.1_darwin_arm64.tar.gz 
saml2aws does not create a keychain secret **saml2aws Credentials**

If I use the forumla https://formulae.brew.sh/formula/saml2aws

```
brew install saml2aws
saml2aws --version   
2.36.1
```

the secret is created just fine.

You can reproduce this when going through a login with both versions and check for the keychain secrets:

```sh
saml2aws login
```

**Comment by joel-russell** [comment]
I can confirm this is happening with both 2.36.1 and the latest release (2.36.2).
