### ISSUE TITLE
Option --mfa not supported for AzureAD

### ISSUE THREAD

**Issue by arthurhobspice** [Versent/saml2aws#902]
I would like to use the saml2aws command line option --mfa=... with AzureAD, so that I can pass in the 6-digit token using oathtool. With ADFS that worked fine, for provider = AzureAD the mfa option is ignored. Do you have it on the roadmap for a future release, or are there technical reasons that the option cannot be supported?

**Comment by christoph-bauer-vf** [comment]
I mean the option --mfa-token. Cannot edit the issue...

**Comment by kitos9112** [comment]
I'm also interested in this feature. Are there any blockers that'd not allow it?

**Comment by kitos9112** [comment]
I've got a local version working of this by passing the loginCredentials struct to a few functions and then adding a local if statement. I'll share this with you @arthurhobspice

**Comment by christianmeyer** [comment]
@arthurhobspice eventually the option support the use of OATH TOTP SHA-1 tokens was not around when the MFA handler for the AzureAD provider was worked on. Currently it only supports server side triggered MFA tokens, thus no need to support handing in tokens via param. I quickly checked the implementation, and might be able to add that to the most recent AzureAD provider adoption tracked in #795
Any support would be welcome :)

**Comment by corleyscotte** [comment]
@christianmeyer thanks for working on this. Do you know if the --mfa-token=<token> option is now being utilized when the provider is set to AzureAD? I updated to saml2aws version 2.36.8 but am still being prompted to enter a verification code.

**Comment by hejfelix** [comment]
I thought it was already out https://github.com/Versent/saml2aws/discussions/135
?

**Comment by saitotqr** [comment]
@hejfelix 
branch https://github.com/Versent/saml2aws/tree/v2.36.18 does not appear to contain changes to pull request https://github.com/Versent/saml2aws/pull/1355 .
`--mfa-token` option on azuread is not recognized in the v2.36.18 binary.

**Comment by saitotqr** [comment]
How do you think? @hejfelix

**Comment by hejfelix** [comment]
Yeah I don't know what happened. I'm not a maintainer so I can't do much. Personally I just built my own binary. It was quite easy

**Comment by hejfelix** [comment]
I can see what went wrong. The release @tinaboyce announced was not based on the tip of the master branch, it was a commit from August (https://github.com/Versent/saml2aws/tree/v2.36.18). Not sure how that happened or if there was something later that they didn't want released yet.

It's not clear who is maintaining this project atm, but it seems they are going through some transition. Would be nice with a way to contact a maintainer

**Comment by corleyscotte** [comment]
@tinaboyce Thank you for this release! I've just tested the latest `2.36.19` build and was able to use the `--mfa-token=` argument successfully.

**Comment by tinaboyce** [comment]
Thank you for testing it and letting me know,  much appreciated.
