### ISSUE TITLE
How to use with awsapps.com

### ISSUE THREAD

**Issue by madpipeline** [Versent/saml2aws#916]
I've used previously `saml2aws` with Okta and that went smoothly. But now I need to use it with `awsapps.com` which I think is an AWS tool that allows a user to login once and then choose from a list what AWS account and role to use (Web UI or CLI).

I am unsure how to use `saml2aws` with this IDP. I have tried using the `Browser` IDP and provide it the URL for one of the AWS accounts/role combo, but it just opens a browser where I need to put in my credentials again (with MFA) after which I'm shown the AWS Console.

`awsapps.com` uses `signin.aws` when I'm authenticating and I think the accounts are part of AWS Organizations, but I'm not super familiar with it yet.

**Comment by arichtman-srt** [comment]
One distinction - if your IAM Identity Center is configured to SSO using a third party Identity Provider you'll need to configure and authenticate against that third party. For example, our AWS SSO is backed by Azure AD, which is where the App ID and URL come from. If you're using Identity Center users directly then you'd set up against AWS as you're doing now.
