### ISSUE TITLE
"page is missing saml assertion" when logging in with GoogleApps

### ISSUE THREAD

**Issue by jmctune** [Versent/saml2aws#933]
## version

`v2.36.2`

## problem

When logging in with GoogleApps using `saml2aws login`, receiving the following error after providing username / password (and before receiving an MFA / challenge):

```
DEBU[0009] loginURL: https://accounts.google.com/signin/challenge/pwd/2  provider=googleapps
DEBU[0009] HTTP Req                                      URL="https://accounts.google.com/signin/challenge/pwd/2?hl=en&loc=US" http=client method=POST
DEBU[0009] HTTP Res                                      Status="400 Bad Request" http=client
page is missing saml assertion
github.com/versent/saml2aws/v2/pkg/provider/googleapps.(*Client).Authenticate
	/Users/user/git/saml2aws/pkg/provider/googleapps/googleapps.go:164
github.com/versent/saml2aws/v2/cmd/saml2aws/commands.Login
	/Users/user/git/saml2aws/cmd/saml2aws/commands/login.go:105
main.main
	/Users/user/git/saml2aws/cmd/saml2aws/main.go:188
runtime.main
	/usr/local/Cellar/go/1.18.1/libexec/src/runtime/proc.go:250
runtime.goexit
	/usr/local/Cellar/go/1.18.1/libexec/src/runtime/asm_amd64.s:1571
Error authenticating to IdP.
github.com/versent/saml2aws/v2/cmd/saml2aws/commands.Login
	/Users/user/git/saml2aws/cmd/saml2aws/commands/login.go:107
main.main
	/Users/user/git/saml2aws/cmd/saml2aws/main.go:188
runtime.main
	/usr/local/Cellar/go/1.18.1/libexec/src/runtime/proc.go:250
runtime.goexit
	/usr/local/Cellar/go/1.18.1/libexec/src/runtime/asm_amd64.s:1571
```

All users of our organization are experiencing this error.

This has previously been working fine for months and just started to become a problem in the last day or so. Seems like the data being sent to Google may be invalid.

Dumping the page HTML and looking at the error, I'm seeing:

```
<p><b>400.</b> <ins>That’s an error.</ins><p>The server cannot process the request because it is malformed. It should not be retried. <ins>That’s all we know.</ins></main>
```

## workaround

Logging in with `SAML2AWS_IDP_PROVIDER=Browser saml2aws login` works when logging in through the Chromium browser, so Google must have changed something again.

**Comment by michaeljs1990** [comment]
Seeing the same thing although it's randomly happening for some users and then going away after 6-8 hours. I unfortunately haven't been hit by this making it very hard to debug.

**Comment by sedovalx** [comment]
The same here. I stably get this error every time I try to use the goog le auth

**Comment by jellevanhees** [comment]
Same for us. the entire company except one user has this error. we have version multiple users both mac and linux running 2.36.1 and 2.36.2 and google auth.

**Comment by shanukova** [comment]
Any updates on fixing this issue?

**Comment by amontalban** [comment]
Having the same issue, other users don't have this issue.

**Comment by michaeljs1990** [comment]
For a "workaround" switching to the browser based auth has unblocked us although I hate the workflow for that.

**Comment by phael90** [comment]
Same here, no workarounds seams to have an effect.

**Comment by amontalban** [comment]
@michaeljs1990 @jmctune how do you use browser based auth? I don't have a `--browser` option:

```
andresmontalban@Andres-MBP-M1 ~ % saml2aws --version
2.36.2
andresmontalban@Andres-MBP-M1 ~ % saml2aws login --browser
saml2aws: error: unknown long flag '--browser', try --help
```

**Comment by jmctune** [comment]
> @michaeljs1990 @jmctune how do you use browser based auth? I don't have a `--browser` option:

Apologies, I'm used to passing that flag with an internal tool I use.

You can log in through the browser method by passing:

`SAML2AWS_IDP_PROVIDER=Browser saml2aws login`

or updating your `~/.saml2aws` config's `Provider` parameter value to `Browser`.

i.e:

```
[default]
name                    = default
...
provider                = Browser
...
```

**Comment by amontalban** [comment]
Thank you @jmctune that workaround helped!

**Comment by phael90** [comment]
Thank you @jmctune it worked!

**Comment by nlopez** [comment]
If you're having trouble with the `Browser` provider not doing anything after you auth in Chromium, try https://github.com/Versent/saml2aws/pull/937

**Comment by vishnu-render** [comment]
hi guys it dosent work for me. I am working in windows 11 and I have installed chromium manually . I also tried this command saml2aws login --browser --verbose and its giving me this error saml2aws.exe: error: unknown long flag '--browser', try --help. 
this is my configuration file
> [default]
name                    = default
app_id                  = 
url                     = https://accounts.google.com/o/saml2/initsso?i*****************
username                = sdkjlfsdlk@skdjlsd.co.uk
provider                = GoogleApps
mfa                     = Auto
skip_verify             = false
timeout                 = 0
aws_urn                 = urn:amazon:webservices
aws_session_duration    = 3600
aws_profile             = developer
resource_id             = 
subdomain               = 
role_arn                = 
region                  = 
http_attempts_count     = 
http_retry_delay        = 
credentials_file        = 
saml_cache              = false
saml_cache_file         = 
target_url              = 
disable_remember_device = false
disable_sessions        = false
prompter                = 
provider                = Browser

this is the outcome of this command
PS C:\Windows\system32> SAML2AWS_IDP_PROVIDER=Browser saml2aws login


SAML2AWS_IDP_PROVIDER=Browser : The term 'SAML2AWS_IDP_PROVIDER=Browser' is not recognized as the name of a cmdlet,
function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the
path is correct and try again.
At line:1 char:1
+ SAML2AWS_IDP_PROVIDER=Browser saml2aws login
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (SAML2AWS_IDP_PROVIDER=Browser:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

thanks in advance

**Comment by jmctune** [comment]
> hi guys it dosent work for me. I am working in windows 11 and I have installed chromium manually . I also tried this command saml2aws login --browser --verbose and its giving me this error saml2aws.exe: error: unknown long flag '--browser', try --help.
this is my configuration file

@vishnu-render I don't think you can pass environment variables this way in Windows. Unsure of the correct way to do it, but I would just update your configuration file to swap "GoogleApps" with "Browser" [as outlined a few comments above](https://github.com/Versent/saml2aws/issues/933#issuecomment-1385517722).

**Comment by imesias** [comment]
Same here, had to configuration to "Browser" to workaround the issue in the meanwhile. We have quite a few people on the latest version `2.36.2` within our organisation that have had to do the same.

What we're seeing is...
```

DEBU[0006] loginURL: https://accounts.google.com/signin/challenge/pwd/2  provider=googleapps
DEBU[0006] HTTP Req                                      URL="https://accounts.google.com/signin/challenge/pwd/2?hl=en&loc=US" http=client method=POST
DEBU[0007] HTTP Res                                      Status="400 Bad Request" http=client
page is missing saml assertion
github.com/versent/saml2aws/v2/pkg/provider/googleapps.(*Client).Authenticate
        github.com/versent/saml2aws/v2/pkg/provider/googleapps/googleapps.go:164
github.com/versent/saml2aws/v2/cmd/saml2aws/commands.Login
        github.com/versent/saml2aws/v2/cmd/saml2aws/commands/login.go:105
main.main
        github.com/versent/saml2aws/v2/cmd/saml2aws/main.go:188
runtime.main
        runtime/proc.go:250
runtime.goexit
        runtime/asm_amd64.s:1594
Error authenticating to IdP.
github.com/versent/saml2aws/v2/cmd/saml2aws/commands.Login
        github.com/versent/saml2aws/v2/cmd/saml2aws/commands/login.go:107
main.main
        github.com/versent/saml2aws/v2/cmd/saml2aws/main.go:188
runtime.main
        runtime/proc.go:250
runtime.goexit
        runtime/asm_amd64.s:1594
```

**Comment by jmctune** [comment]
Still a problem here.

I've looked at it a little bit and tracked it down to either the `authForm` or `submitURL` in the [loadChallengePage](https://github.com/Versent/saml2aws/blob/master/pkg/provider/googleapps/googleapps.go#L341) function. I'm not familiar with how Google does things, but when the call is made in the [Authenticate](https://github.com/Versent/saml2aws/blob/master/pkg/provider/googleapps/googleapps.go#L83) function, it returns a 400. The rest of the code doesn't handle failure status codes and continues to parse the bad request, but can't find anything.

**Comment by jamesyale** [comment]
The [patch above](https://github.com/Versent/saml2aws/pull/954) worked for me 👍
