### ISSUE TITLE
Log into AWS SSO using Azure AD for authentication

### ISSUE THREAD

**Issue by iainelder** [Versent/saml2aws#947]
My organization uses AWS SSO to log into AWS accounts.

Authentication to AWS SSO is handed by Azure AD.

Does saml2aws handle this use case?

I have read the [Azure AD provider documentation](https://github.com/Versent/saml2aws/tree/master/doc/provider/aad). I'm stuck at the first step:

> When configuring saml2aws to work with Azure AD, you must first acquire the Azure AD Enterprise App Id.
>
> This can be easily achieved by browsing MyApps at https://myapps.microsoft.com/ and logging in. Click your AWS app, and immediately copy the URL that it loads, before the redirect.

When I go to the [My Apps](https://myapps.microsoft.com/) page, I see hundreds of apps (It's a big organization). None is clearly named as AWS.

Is there another way to determine the application ID?

Is that even what I need to do for this use case?

**Comment by wtfiwtz** [comment]
You probably need to look in the AzureAD SSO Identity Platform settings. Someone else at my company does this so I don't have a sample but check this:
https://learn.microsoft.com/en-us/azure/active-directory/develop/active-directory-saml-protocol-reference

It does work, although recently someone reported an issue with needing to type a token code on a push notification. If that's the case, have a look at `aws-runas` instead - v3.5 and above handles this using a temporary web browser (modern auth) login. `saml2aws` does this in a hidden browser window that isn't exposed.

**Comment by iainelder** [comment]
Thanks, @wtfiwtz . You helped me to find an application ID that corresponds to my AWS SSO instance.

From the linked document:

> In the [Azure portal](https://portal.azure.com/);
>
> * Open the app in Azure Active Directory and select App registrations

I click the "All applications" tab and I see "1000+ applications found", even more than before.

I type "AWS" into the display name filter and then I see the app I needed that didn't appear using the other method.

From here I can just copy the value in the "Application (client) ID" column.

But I haven't taken this any further or tried to understand the rest of the document.

[AWS SSO CLI](https://github.com/synfinatic/aws-sso-cli) seems to be a better tool for my workflow. 

I don't have to know anything about the configuration of Azure or SAML to get it working.

It uses [granted](https://github.com/common-fate/granted) to launch a [Firefox container tab](https://github.com/mozilla/multi-account-containers) dedicated to the CLI login procedure.

 After logging in once via the container tab, Firefox manages the session state for me and I hardly ever see the Azure AD page.
