### ISSUE TITLE
How to get the SP identifier for Google?

### ISSUE THREAD

**Issue by Raboo** [Versent/saml2aws#950]
Hi!

I want to setup saml2aws with our Google account but have not been able to succeed.

I'm not an admin in our Google Workspace account, neither in our AWS SSO setup.
I have been provided with an URL to login to our AWS account that redirects to Google for account login, i.e. https://OURCOMPANY.awsapps.com/start/.

Checking the Network tab in the Firefox Web Developer tools I am able to extract the IdP ID during browser login.
But from where can I extract the needed SP identifier for enabling auth via Google?

**Comment by morancj** [comment]
You're probably looking in the wrong place, don't think this project is what you want. [Docs](https://docs.aws.amazon.com/cli/latest/userguide/sso-configure-profile-token.html)

**Comment by Raboo** [comment]
Ok
