### ISSUE TITLE
move Choco package upload under GHA

### ISSUE THREAD

**Issue by gliptak** [Versent/saml2aws#985]
replacing https://github.com/Versent/saml2aws/blob/master/.appveyor/appveyor.yml

maybe with https://github.com/crazy-max/ghaction-chocolatey

**Comment by mapkon** [comment]
@gliptak Closing this, as I know it is fixed. Reopen if you agree

**Comment by gliptak** [comment]
@mapkon this is still outstanding, currently https://ci.appveyor.com/project/davidobrien1985/saml2aws/branch/master used to publish

**Comment by tinaboyce** [comment]
Re-opening this as I agree it is currently outstanding.

**Comment by tinaboyce** [comment]
Another instance of chocolately containing outdated package version has occurred. After talking to the owner of the CI, it has been agreed upon to either
1. Set up a new appveyor under my account
2. GHA
Decided its time to try GHA first.
